// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/platform/player_auth/playerauth_v1.proto

package improbable_platform_player_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "improbable.io/proto/improbable/ext/plugin/auth"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PlayerIdentityToken) Validate() error {
	if this.Expiry != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Expiry); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Expiry", err)
		}
	}
	return nil
}

var _regex_GenerateTokenRequest_ProjectName = regexp.MustCompile(`^[a-z0-9_]{3,32}$`)

func (this *GenerateTokenRequest) Validate() error {
	if this.PlayerIdentifier == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("PlayerIdentifier", fmt.Errorf(`value '%v' must not be an empty string`, this.PlayerIdentifier))
	}
	if !_regex_GenerateTokenRequest_ProjectName.MatchString(this.ProjectName) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectName", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z0-9_]{3,32}$"`, this.ProjectName))
	}
	return nil
}
func (this *GenerateTokenResponse) Validate() error {
	return nil
}
func (this *DecodeTokenRequest) Validate() error {
	if this.PlayerIdentityToken == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("PlayerIdentityToken", fmt.Errorf(`value '%v' must not be an empty string`, this.PlayerIdentityToken))
	}
	return nil
}
func (this *DecodeTokenResponse) Validate() error {
	if this.PlayerIdentityToken != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PlayerIdentityToken); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PlayerIdentityToken", err)
		}
	}
	return nil
}
