// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/platform/deployment/configuration.proto

package improbable_platform_deployment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *DeploymentConfiguration) Validate() error {
	for _, item := range this.Javaparams {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Javaparams", err)
			}
		}
	}
	for _, item := range this.Flagz {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Flagz", err)
			}
		}
	}
	for _, item := range this.Nodes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Nodes", err)
			}
		}
	}
	for _, item := range this.WorkerFlagz {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("WorkerFlagz", err)
			}
		}
	}
	for _, item := range this.WorkerNodes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("WorkerNodes", err)
			}
		}
	}
	return nil
}
func (this *DeploymentConfiguration_Parameter) Validate() error {
	return nil
}
func (this *DeploymentConfiguration_Module) Validate() error {
	for _, item := range this.Params {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Params", err)
			}
		}
	}
	return nil
}

var _regex_DeploymentConfiguration_Node_Name = regexp.MustCompile(`^[a-z0-9][a-z0-9_]{1,24}$`)

func (this *DeploymentConfiguration_Node) Validate() error {
	if !_regex_DeploymentConfiguration_Node_Name.MatchString(this.Name) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z0-9][a-z0-9_]{1,24}$"`, this.Name))
	}
	for _, item := range this.Modules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Modules", err)
			}
		}
	}
	return nil
}

var _regex_DeploymentConfiguration_WorkerNode_Name = regexp.MustCompile(`^[a-z0-9][a-z0-9_]{1,24}$`)

func (this *DeploymentConfiguration_WorkerNode) Validate() error {
	if !_regex_DeploymentConfiguration_WorkerNode_Name.MatchString(this.Name) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z0-9][a-z0-9_]{1,24}$"`, this.Name))
	}
	return nil
}
func (this *DeploymentConfiguration_WorkerFlagz) Validate() error {
	for _, item := range this.Flagz {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Flagz", err)
			}
		}
	}
	return nil
}

var _regex_FlagValue_Name = regexp.MustCompile(`^[a-zA-Z0-9_-]{3,128}$`)

func (this *FlagValue) Validate() error {
	if !_regex_FlagValue_Name.MatchString(this.Name) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9_-]{3,128}$"`, this.Name))
	}
	return nil
}
