// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/platform/deployment/configuration.proto

package improbable_platform_deployment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *DeploymentConfiguration) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeploymentConfiguration) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeploymentConfiguration_Parameter) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeploymentConfiguration_Parameter) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeploymentConfiguration_Module) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeploymentConfiguration_Module) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeploymentConfiguration_Node) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeploymentConfiguration_Node) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeploymentConfiguration_WorkerNode) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeploymentConfiguration_WorkerNode) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeploymentConfiguration_WorkerFlagz) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeploymentConfiguration_WorkerFlagz) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *FlagValue) LogFields() map[string]string {
	return map[string]string{}
}

func (this *FlagValue) ExtractRequestFields(dst map[string]interface{}) {
}
