// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/platform/runtime/component_diff.proto

package improbable_platform_runtime

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ComponentDiff) LogFields() map[string]string {
	return map[string]string{}
}

func (this *ComponentDiff) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *Encoding) LogFields() map[string]string {
	return map[string]string{}
}

func (this *Encoding) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *EncodingStrategyToFormatEntry) LogFields() map[string]string {
	return map[string]string{}
}

func (this *EncodingStrategyToFormatEntry) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *EncodingStrategyToFormat) LogFields() map[string]string {
	return map[string]string{}
}

func (this *EncodingStrategyToFormat) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *ComponentDiffFormats) LogFields() map[string]string {
	return map[string]string{}
}

func (this *ComponentDiffFormats) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *ComponentDiffSettings) LogFields() map[string]string {
	return map[string]string{}
}

func (this *ComponentDiffSettings) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *FieldDiffs) LogFields() map[string]string {
	return map[string]string{}
}

func (this *FieldDiffs) ExtractRequestFields(dst map[string]interface{}) {
}
