// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/inner/fabric_bundle/fabric_bundle.proto

package improbable_inner_bundle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/improbable-io/go-proto-logfields"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1alpha1 "improbable.io/proto/improbable/spatialos/runtimeversion/v1alpha1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bundle struct {
	FabricVersion        *FabricVersion       `protobuf:"bytes,1,opt,name=fabric_version,json=fabricVersion,proto3" json:"fabric_version,omitempty"`
	Tags                 []string             `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	StorageUrl           string               `protobuf:"bytes,4,opt,name=storage_url,json=storageUrl,proto3" json:"storage_url,omitempty"`
	Checksum             []byte               `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Metadata             *BundleMetadata      `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Bundle) Reset()         { *m = Bundle{} }
func (m *Bundle) String() string { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()    {}
func (*Bundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{0}
}

func (m *Bundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bundle.Unmarshal(m, b)
}
func (m *Bundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bundle.Marshal(b, m, deterministic)
}
func (m *Bundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle.Merge(m, src)
}
func (m *Bundle) XXX_Size() int {
	return xxx_messageInfo_Bundle.Size(m)
}
func (m *Bundle) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle proto.InternalMessageInfo

func (m *Bundle) GetFabricVersion() *FabricVersion {
	if m != nil {
		return m.FabricVersion
	}
	return nil
}

func (m *Bundle) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Bundle) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *Bundle) GetStorageUrl() string {
	if m != nil {
		return m.StorageUrl
	}
	return ""
}

func (m *Bundle) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *Bundle) GetMetadata() *BundleMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type FabricVersion struct {
	FabricVersion        string   `protobuf:"bytes,1,opt,name=fabric_version,json=fabricVersion,proto3" json:"fabric_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FabricVersion) Reset()         { *m = FabricVersion{} }
func (m *FabricVersion) String() string { return proto.CompactTextString(m) }
func (*FabricVersion) ProtoMessage()    {}
func (*FabricVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{1}
}

func (m *FabricVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FabricVersion.Unmarshal(m, b)
}
func (m *FabricVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FabricVersion.Marshal(b, m, deterministic)
}
func (m *FabricVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FabricVersion.Merge(m, src)
}
func (m *FabricVersion) XXX_Size() int {
	return xxx_messageInfo_FabricVersion.Size(m)
}
func (m *FabricVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_FabricVersion.DiscardUnknown(m)
}

var xxx_messageInfo_FabricVersion proto.InternalMessageInfo

func (m *FabricVersion) GetFabricVersion() string {
	if m != nil {
		return m.FabricVersion
	}
	return ""
}

type BundleMetadata struct {
	Major         uint32   `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Commit        string   `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`                                    // Deprecated: Do not use.
	ReleaseTicket string   `protobuf:"bytes,3,opt,name=release_ticket,json=releaseTicket,proto3" json:"release_ticket,omitempty"` // Deprecated: Do not use.
	Templates     []string `protobuf:"bytes,4,rep,name=templates,proto3" json:"templates,omitempty"`
	// Types that are valid to be assigned to Purpose:
	//	*BundleMetadata_Release
	//	*BundleMetadata_Experiment
	Purpose              isBundleMetadata_Purpose `protobuf_oneof:"purpose"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BundleMetadata) Reset()         { *m = BundleMetadata{} }
func (m *BundleMetadata) String() string { return proto.CompactTextString(m) }
func (*BundleMetadata) ProtoMessage()    {}
func (*BundleMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{2}
}

func (m *BundleMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleMetadata.Unmarshal(m, b)
}
func (m *BundleMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleMetadata.Marshal(b, m, deterministic)
}
func (m *BundleMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleMetadata.Merge(m, src)
}
func (m *BundleMetadata) XXX_Size() int {
	return xxx_messageInfo_BundleMetadata.Size(m)
}
func (m *BundleMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BundleMetadata proto.InternalMessageInfo

func (m *BundleMetadata) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

// Deprecated: Do not use.
func (m *BundleMetadata) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

// Deprecated: Do not use.
func (m *BundleMetadata) GetReleaseTicket() string {
	if m != nil {
		return m.ReleaseTicket
	}
	return ""
}

func (m *BundleMetadata) GetTemplates() []string {
	if m != nil {
		return m.Templates
	}
	return nil
}

type isBundleMetadata_Purpose interface {
	isBundleMetadata_Purpose()
}

type BundleMetadata_Release struct {
	Release *BundleMetadata_ReleaseInfo `protobuf:"bytes,6,opt,name=release,proto3,oneof"`
}

type BundleMetadata_Experiment struct {
	Experiment *BundleMetadata_ExperimentInfo `protobuf:"bytes,7,opt,name=experiment,proto3,oneof"`
}

func (*BundleMetadata_Release) isBundleMetadata_Purpose() {}

func (*BundleMetadata_Experiment) isBundleMetadata_Purpose() {}

func (m *BundleMetadata) GetPurpose() isBundleMetadata_Purpose {
	if m != nil {
		return m.Purpose
	}
	return nil
}

func (m *BundleMetadata) GetRelease() *BundleMetadata_ReleaseInfo {
	if x, ok := m.GetPurpose().(*BundleMetadata_Release); ok {
		return x.Release
	}
	return nil
}

func (m *BundleMetadata) GetExperiment() *BundleMetadata_ExperimentInfo {
	if x, ok := m.GetPurpose().(*BundleMetadata_Experiment); ok {
		return x.Experiment
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BundleMetadata) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BundleMetadata_Release)(nil),
		(*BundleMetadata_Experiment)(nil),
	}
}

type BundleMetadata_ReleaseInfo struct {
	JiraTicket           string   `protobuf:"bytes,1,opt,name=jira_ticket,json=jiraTicket,proto3" json:"jira_ticket,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BundleMetadata_ReleaseInfo) Reset()         { *m = BundleMetadata_ReleaseInfo{} }
func (m *BundleMetadata_ReleaseInfo) String() string { return proto.CompactTextString(m) }
func (*BundleMetadata_ReleaseInfo) ProtoMessage()    {}
func (*BundleMetadata_ReleaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{2, 0}
}

func (m *BundleMetadata_ReleaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleMetadata_ReleaseInfo.Unmarshal(m, b)
}
func (m *BundleMetadata_ReleaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleMetadata_ReleaseInfo.Marshal(b, m, deterministic)
}
func (m *BundleMetadata_ReleaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleMetadata_ReleaseInfo.Merge(m, src)
}
func (m *BundleMetadata_ReleaseInfo) XXX_Size() int {
	return xxx_messageInfo_BundleMetadata_ReleaseInfo.Size(m)
}
func (m *BundleMetadata_ReleaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleMetadata_ReleaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BundleMetadata_ReleaseInfo proto.InternalMessageInfo

func (m *BundleMetadata_ReleaseInfo) GetJiraTicket() string {
	if m != nil {
		return m.JiraTicket
	}
	return ""
}

func (m *BundleMetadata_ReleaseInfo) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

type BundleMetadata_ExperimentInfo struct {
	ExpiryEpochSeconds   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expiry_epoch_seconds,json=expiryEpochSeconds,proto3" json:"expiry_epoch_seconds,omitempty"`
	Commit               string               `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BundleMetadata_ExperimentInfo) Reset()         { *m = BundleMetadata_ExperimentInfo{} }
func (m *BundleMetadata_ExperimentInfo) String() string { return proto.CompactTextString(m) }
func (*BundleMetadata_ExperimentInfo) ProtoMessage()    {}
func (*BundleMetadata_ExperimentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{2, 1}
}

func (m *BundleMetadata_ExperimentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleMetadata_ExperimentInfo.Unmarshal(m, b)
}
func (m *BundleMetadata_ExperimentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleMetadata_ExperimentInfo.Marshal(b, m, deterministic)
}
func (m *BundleMetadata_ExperimentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleMetadata_ExperimentInfo.Merge(m, src)
}
func (m *BundleMetadata_ExperimentInfo) XXX_Size() int {
	return xxx_messageInfo_BundleMetadata_ExperimentInfo.Size(m)
}
func (m *BundleMetadata_ExperimentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleMetadata_ExperimentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BundleMetadata_ExperimentInfo proto.InternalMessageInfo

func (m *BundleMetadata_ExperimentInfo) GetExpiryEpochSeconds() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiryEpochSeconds
	}
	return nil
}

func (m *BundleMetadata_ExperimentInfo) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

type DeleteRequest struct {
	FabricVersion        *FabricVersion `protobuf:"bytes,1,opt,name=fabric_version,json=fabricVersion,proto3" json:"fabric_version,omitempty"`
	Force                bool           `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetFabricVersion() *FabricVersion {
	if m != nil {
		return m.FabricVersion
	}
	return nil
}

func (m *DeleteRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type CreationRequest struct {
	FabricVersion        *FabricVersion  `protobuf:"bytes,1,opt,name=fabric_version,json=fabricVersion,proto3" json:"fabric_version,omitempty"`
	Checksum             string          `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Tags                 []string        `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata             *BundleMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreationRequest) Reset()         { *m = CreationRequest{} }
func (m *CreationRequest) String() string { return proto.CompactTextString(m) }
func (*CreationRequest) ProtoMessage()    {}
func (*CreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{4}
}

func (m *CreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationRequest.Unmarshal(m, b)
}
func (m *CreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationRequest.Marshal(b, m, deterministic)
}
func (m *CreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationRequest.Merge(m, src)
}
func (m *CreationRequest) XXX_Size() int {
	return xxx_messageInfo_CreationRequest.Size(m)
}
func (m *CreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreationRequest proto.InternalMessageInfo

func (m *CreationRequest) GetFabricVersion() *FabricVersion {
	if m != nil {
		return m.FabricVersion
	}
	return nil
}

func (m *CreationRequest) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *CreationRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreationRequest) GetMetadata() *BundleMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreationResponse struct {
	FabricVersion        *FabricVersion `protobuf:"bytes,1,opt,name=fabric_version,json=fabricVersion,proto3" json:"fabric_version,omitempty"`
	UploadUrl            string         `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreationResponse) Reset()         { *m = CreationResponse{} }
func (m *CreationResponse) String() string { return proto.CompactTextString(m) }
func (*CreationResponse) ProtoMessage()    {}
func (*CreationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{5}
}

func (m *CreationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationResponse.Unmarshal(m, b)
}
func (m *CreationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationResponse.Marshal(b, m, deterministic)
}
func (m *CreationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationResponse.Merge(m, src)
}
func (m *CreationResponse) XXX_Size() int {
	return xxx_messageInfo_CreationResponse.Size(m)
}
func (m *CreationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreationResponse proto.InternalMessageInfo

func (m *CreationResponse) GetFabricVersion() *FabricVersion {
	if m != nil {
		return m.FabricVersion
	}
	return nil
}

func (m *CreationResponse) GetUploadUrl() string {
	if m != nil {
		return m.UploadUrl
	}
	return ""
}

type BundleTagAddRequest struct {
	FabricVersion        *FabricVersion `protobuf:"bytes,1,opt,name=fabric_version,json=fabricVersion,proto3" json:"fabric_version,omitempty"`
	Tag                  string         `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BundleTagAddRequest) Reset()         { *m = BundleTagAddRequest{} }
func (m *BundleTagAddRequest) String() string { return proto.CompactTextString(m) }
func (*BundleTagAddRequest) ProtoMessage()    {}
func (*BundleTagAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{6}
}

func (m *BundleTagAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleTagAddRequest.Unmarshal(m, b)
}
func (m *BundleTagAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleTagAddRequest.Marshal(b, m, deterministic)
}
func (m *BundleTagAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleTagAddRequest.Merge(m, src)
}
func (m *BundleTagAddRequest) XXX_Size() int {
	return xxx_messageInfo_BundleTagAddRequest.Size(m)
}
func (m *BundleTagAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleTagAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BundleTagAddRequest proto.InternalMessageInfo

func (m *BundleTagAddRequest) GetFabricVersion() *FabricVersion {
	if m != nil {
		return m.FabricVersion
	}
	return nil
}

func (m *BundleTagAddRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type BundleTagRemoveRequest struct {
	FabricVersion        *FabricVersion `protobuf:"bytes,1,opt,name=fabric_version,json=fabricVersion,proto3" json:"fabric_version,omitempty"`
	Tag                  string         `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BundleTagRemoveRequest) Reset()         { *m = BundleTagRemoveRequest{} }
func (m *BundleTagRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*BundleTagRemoveRequest) ProtoMessage()    {}
func (*BundleTagRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{7}
}

func (m *BundleTagRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleTagRemoveRequest.Unmarshal(m, b)
}
func (m *BundleTagRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleTagRemoveRequest.Marshal(b, m, deterministic)
}
func (m *BundleTagRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleTagRemoveRequest.Merge(m, src)
}
func (m *BundleTagRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_BundleTagRemoveRequest.Size(m)
}
func (m *BundleTagRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleTagRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BundleTagRemoveRequest proto.InternalMessageInfo

func (m *BundleTagRemoveRequest) GetFabricVersion() *FabricVersion {
	if m != nil {
		return m.FabricVersion
	}
	return nil
}

func (m *BundleTagRemoveRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type SearchBundleRequest struct {
	Tags                 []string             `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	BeforeTime           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=before_time,json=beforeTime,proto3" json:"before_time,omitempty"`
	AfterTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=after_time,json=afterTime,proto3" json:"after_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchBundleRequest) Reset()         { *m = SearchBundleRequest{} }
func (m *SearchBundleRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBundleRequest) ProtoMessage()    {}
func (*SearchBundleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{8}
}

func (m *SearchBundleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBundleRequest.Unmarshal(m, b)
}
func (m *SearchBundleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBundleRequest.Marshal(b, m, deterministic)
}
func (m *SearchBundleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBundleRequest.Merge(m, src)
}
func (m *SearchBundleRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBundleRequest.Size(m)
}
func (m *SearchBundleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBundleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBundleRequest proto.InternalMessageInfo

func (m *SearchBundleRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SearchBundleRequest) GetBeforeTime() *timestamp.Timestamp {
	if m != nil {
		return m.BeforeTime
	}
	return nil
}

func (m *SearchBundleRequest) GetAfterTime() *timestamp.Timestamp {
	if m != nil {
		return m.AfterTime
	}
	return nil
}

type ResolveFabricVersionRequest struct {
	SpatialVersion        string   `protobuf:"bytes,1,opt,name=spatial_version,json=spatialVersion,proto3" json:"spatial_version,omitempty"`
	FabricVersionOverride string   `protobuf:"bytes,2,opt,name=fabric_version_override,json=fabricVersionOverride,proto3" json:"fabric_version_override,omitempty"`
	TemplateName          string   `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ResolveFabricVersionRequest) Reset()         { *m = ResolveFabricVersionRequest{} }
func (m *ResolveFabricVersionRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveFabricVersionRequest) ProtoMessage()    {}
func (*ResolveFabricVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9dc26f5631393f, []int{9}
}

func (m *ResolveFabricVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveFabricVersionRequest.Unmarshal(m, b)
}
func (m *ResolveFabricVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveFabricVersionRequest.Marshal(b, m, deterministic)
}
func (m *ResolveFabricVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveFabricVersionRequest.Merge(m, src)
}
func (m *ResolveFabricVersionRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveFabricVersionRequest.Size(m)
}
func (m *ResolveFabricVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveFabricVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveFabricVersionRequest proto.InternalMessageInfo

func (m *ResolveFabricVersionRequest) GetSpatialVersion() string {
	if m != nil {
		return m.SpatialVersion
	}
	return ""
}

func (m *ResolveFabricVersionRequest) GetFabricVersionOverride() string {
	if m != nil {
		return m.FabricVersionOverride
	}
	return ""
}

func (m *ResolveFabricVersionRequest) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func init() {
	proto.RegisterType((*Bundle)(nil), "improbable.inner.bundle.Bundle")
	proto.RegisterType((*FabricVersion)(nil), "improbable.inner.bundle.FabricVersion")
	proto.RegisterType((*BundleMetadata)(nil), "improbable.inner.bundle.BundleMetadata")
	proto.RegisterType((*BundleMetadata_ReleaseInfo)(nil), "improbable.inner.bundle.BundleMetadata.ReleaseInfo")
	proto.RegisterType((*BundleMetadata_ExperimentInfo)(nil), "improbable.inner.bundle.BundleMetadata.ExperimentInfo")
	proto.RegisterType((*DeleteRequest)(nil), "improbable.inner.bundle.DeleteRequest")
	proto.RegisterType((*CreationRequest)(nil), "improbable.inner.bundle.CreationRequest")
	proto.RegisterType((*CreationResponse)(nil), "improbable.inner.bundle.CreationResponse")
	proto.RegisterType((*BundleTagAddRequest)(nil), "improbable.inner.bundle.BundleTagAddRequest")
	proto.RegisterType((*BundleTagRemoveRequest)(nil), "improbable.inner.bundle.BundleTagRemoveRequest")
	proto.RegisterType((*SearchBundleRequest)(nil), "improbable.inner.bundle.SearchBundleRequest")
	proto.RegisterType((*ResolveFabricVersionRequest)(nil), "improbable.inner.bundle.ResolveFabricVersionRequest")
}

func init() {
	proto.RegisterFile("improbable/inner/fabric_bundle/fabric_bundle.proto", fileDescriptor_7d9dc26f5631393f)
}

var fileDescriptor_7d9dc26f5631393f = []byte{
	// 1289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xef, 0x3a, 0xa9, 0x1b, 0xbf, 0xc4, 0x69, 0x99, 0x24, 0xad, 0xeb, 0xb4, 0x71, 0xb4, 0xa0,
	0x92, 0xa6, 0xf5, 0x6e, 0x9a, 0x96, 0xd2, 0x3f, 0xa8, 0x10, 0x97, 0xb6, 0x14, 0x02, 0x55, 0x37,
	0x09, 0xa0, 0x56, 0xc5, 0x1a, 0xdb, 0x63, 0x67, 0xdb, 0xdd, 0x9d, 0x65, 0x66, 0xec, 0xb6, 0x84,
	0x48, 0x08, 0x0e, 0xf4, 0x58, 0x89, 0x13, 0x12, 0x17, 0x72, 0xe1, 0x90, 0xaf, 0xc0, 0x57, 0xe0,
	0x80, 0x10, 0xe7, 0x48, 0x11, 0x57, 0xf8, 0x0c, 0x68, 0x67, 0x66, 0x1d, 0xdb, 0x8d, 0x1d, 0x03,
	0x8d, 0xc4, 0x6d, 0x66, 0xde, 0x9f, 0xf9, 0xbd, 0xdf, 0x7b, 0xf3, 0xde, 0xc0, 0xbc, 0xeb, 0x87,
	0x8c, 0x96, 0x70, 0xc9, 0x23, 0xb6, 0x1b, 0x04, 0x84, 0xd9, 0x55, 0x5c, 0x62, 0x6e, 0xb9, 0x58,
	0xaa, 0x07, 0x15, 0x8f, 0xb4, 0xef, 0xac, 0x90, 0x51, 0x41, 0xd1, 0xb1, 0x1d, 0x1b, 0x4b, 0xda,
	0x58, 0x4a, 0x9c, 0xbd, 0x58, 0x73, 0xc5, 0x6a, 0xbd, 0x64, 0x95, 0xa9, 0x6f, 0xfb, 0x8f, 0x5d,
	0xf1, 0x88, 0x3e, 0xb6, 0x6b, 0x34, 0x2f, 0xad, 0xf2, 0x0d, 0xec, 0xb9, 0x15, 0x2c, 0x28, 0xe3,
	0x76, 0x73, 0xa9, 0x1c, 0x66, 0x4f, 0xd4, 0x28, 0xad, 0x79, 0xc4, 0xc6, 0xa1, 0x6b, 0xe3, 0x20,
	0xa0, 0x02, 0x0b, 0x97, 0x06, 0x5c, 0x4b, 0x27, 0xb5, 0x54, 0xee, 0x4a, 0xf5, 0xaa, 0x4d, 0xfc,
	0x50, 0x3c, 0xd5, 0xc2, 0x5c, 0xa7, 0x50, 0xb8, 0x3e, 0xe1, 0x02, 0xfb, 0xa1, 0x56, 0xb8, 0xda,
	0x82, 0x69, 0x07, 0x77, 0xde, 0xa5, 0x3b, 0xc8, 0x3c, 0x5a, 0xab, 0xba, 0xc4, 0xab, 0x70, 0xbb,
	0xb9, 0xd2, 0xc6, 0x85, 0x16, 0x76, 0x78, 0x88, 0x85, 0x8b, 0x3d, 0xca, 0x6d, 0x56, 0x0f, 0xa2,
	0x5b, 0x1a, 0x84, 0x71, 0x97, 0x06, 0x76, 0xe3, 0x1c, 0xf6, 0xc2, 0x55, 0x7c, 0x2e, 0x3e, 0x2f,
	0x6a, 0x81, 0xf2, 0x61, 0xfe, 0x9a, 0x80, 0x64, 0x41, 0xf2, 0x83, 0x56, 0x60, 0x54, 0xf3, 0xa9,
	0x55, 0x32, 0xc6, 0xb4, 0x31, 0x33, 0x3c, 0x7f, 0xca, 0xea, 0xc2, 0xa8, 0x75, 0x53, 0xaa, 0x7f,
	0xac, 0xb4, 0x0b, 0xc9, 0xed, 0xad, 0x5c, 0x62, 0xda, 0x70, 0xd2, 0xd5, 0xd6, 0x63, 0x94, 0x87,
	0x41, 0x81, 0x6b, 0x3c, 0x93, 0x98, 0x1e, 0x98, 0x49, 0x15, 0x8e, 0x6f, 0x6f, 0xe5, 0x26, 0x60,
	0xec, 0xb3, 0xfb, 0x38, 0xff, 0xc5, 0x5c, 0xfe, 0x72, 0xd1, 0xca, 0x3f, 0x58, 0x9b, 0x3b, 0x7b,
	0xe1, 0xd2, 0xfa, 0x6b, 0x8e, 0x54, 0x43, 0x6f, 0x43, 0xba, 0xcc, 0x88, 0xa4, 0xb8, 0x18, 0xe1,
	0xcd, 0x0c, 0x48, 0x10, 0x59, 0x4b, 0x51, 0x69, 0xc5, 0x54, 0x5a, 0xcb, 0x31, 0x95, 0xce, 0x48,
	0x6c, 0x10, 0x1d, 0xa1, 0x1c, 0x0c, 0x73, 0x41, 0x19, 0xae, 0x91, 0x62, 0x9d, 0x79, 0x99, 0xc1,
	0x69, 0x63, 0x26, 0xe5, 0x80, 0x3e, 0x5a, 0x61, 0x1e, 0xca, 0xc2, 0x50, 0x79, 0x95, 0x94, 0x1f,
	0xf1, 0xba, 0x9f, 0x39, 0x38, 0x6d, 0xcc, 0x8c, 0x38, 0xcd, 0x3d, 0xba, 0x0e, 0x43, 0x3e, 0x11,
	0xb8, 0x82, 0x05, 0xce, 0x24, 0xe5, 0xc5, 0xaf, 0x77, 0x8d, 0x5e, 0xd1, 0xf6, 0xa1, 0x56, 0x77,
	0x9a, 0x86, 0xe6, 0x22, 0xa4, 0xdb, 0x98, 0x41, 0x57, 0x77, 0x65, 0x36, 0x55, 0x18, 0xdf, 0xd8,
	0x9c, 0x3a, 0xd2, 0x29, 0xeb, 0xe0, 0xcf, 0xfc, 0x65, 0x10, 0x46, 0xdb, 0xaf, 0x42, 0xe3, 0x70,
	0xd0, 0xc7, 0x0f, 0x29, 0x93, 0x6e, 0xd2, 0x8e, 0xda, 0xa0, 0x2c, 0x24, 0xcb, 0xd4, 0xf7, 0x5d,
	0x91, 0x49, 0x48, 0xef, 0x89, 0x8c, 0xe1, 0xe8, 0x13, 0x74, 0x1a, 0x46, 0x19, 0xf1, 0x08, 0xe6,
	0xa4, 0x28, 0xdc, 0xf2, 0x23, 0x22, 0x24, 0xad, 0x4a, 0x27, 0xad, 0x25, 0xcb, 0x52, 0x80, 0x4e,
	0x40, 0x4a, 0x10, 0x3f, 0xf4, 0xb0, 0x20, 0x3c, 0x33, 0x18, 0x25, 0xcd, 0xd9, 0x39, 0x40, 0x77,
	0xe0, 0x90, 0x56, 0xd7, 0xfc, 0x9c, 0xef, 0x93, 0x1f, 0xcb, 0x51, 0x66, 0xb7, 0x83, 0x2a, 0x7d,
	0xef, 0x80, 0x13, 0x7b, 0x41, 0x9f, 0x02, 0x90, 0x27, 0x21, 0x61, 0xae, 0x4f, 0x02, 0x91, 0x39,
	0x24, 0x7d, 0x5e, 0xec, 0xd7, 0xe7, 0x8d, 0xa6, 0xa5, 0x76, 0xdb, 0xe2, 0x2b, 0xfb, 0x18, 0x86,
	0x5b, 0xee, 0x44, 0x6f, 0xc1, 0xf0, 0x43, 0x97, 0xe1, 0x38, 0x7e, 0x95, 0x81, 0xc9, 0xed, 0xad,
	0xdc, 0x31, 0x98, 0xb8, 0xbf, 0x90, 0xbf, 0xf7, 0x60, 0x6d, 0xfe, 0xec, 0x85, 0xf5, 0xfc, 0xfd,
	0xb9, 0xfc, 0xe5, 0x68, 0xf9, 0xc6, 0xba, 0x03, 0x91, 0xbe, 0x66, 0x65, 0xb6, 0x83, 0x5c, 0xb4,
	0xbd, 0x95, 0x1b, 0x85, 0x91, 0x48, 0x1b, 0xe7, 0xab, 0x0b, 0xf9, 0x9b, 0x0f, 0xce, 0xc4, 0x64,
	0x67, 0x9f, 0x1b, 0x30, 0xda, 0x8e, 0x0c, 0x2d, 0xc2, 0x38, 0x79, 0x12, 0xba, 0xec, 0x69, 0x91,
	0x84, 0xb4, 0xbc, 0x5a, 0xe4, 0xa4, 0x4c, 0x83, 0x0a, 0x97, 0xce, 0x7a, 0x17, 0x37, 0x52, 0x76,
	0x37, 0x22, 0xb3, 0x25, 0x65, 0xd5, 0x02, 0x66, 0x60, 0x2f, 0x30, 0xef, 0x0f, 0x0e, 0x19, 0x47,
	0x12, 0x85, 0x14, 0x1c, 0x0a, 0xeb, 0x2c, 0xa4, 0x9c, 0x98, 0x5f, 0x42, 0xfa, 0x5d, 0xe2, 0x11,
	0x41, 0x1c, 0xf2, 0x79, 0x9d, 0x70, 0xb1, 0x5f, 0xef, 0x7e, 0x1c, 0x0e, 0x56, 0x29, 0x2b, 0x13,
	0x19, 0xe3, 0x90, 0xa3, 0x36, 0xe6, 0x57, 0x09, 0x38, 0x7c, 0x5d, 0x3f, 0xd7, 0x7d, 0x06, 0x60,
	0xb6, 0xbc, 0x73, 0x95, 0xb4, 0x58, 0x71, 0xe7, 0xbd, 0xc7, 0xcd, 0x69, 0xa0, 0xbf, 0xe6, 0xd4,
	0xda, 0x1e, 0x06, 0xff, 0x6d, 0x7b, 0x78, 0x66, 0xc0, 0x91, 0x1d, 0x0a, 0x78, 0x48, 0x03, 0xbe,
	0x6f, 0xcd, 0xf7, 0x24, 0x40, 0x3d, 0xf4, 0x28, 0xae, 0xc8, 0x5e, 0x28, 0x59, 0x70, 0x52, 0xea,
	0x64, 0x85, 0x79, 0xe6, 0xf7, 0x06, 0x8c, 0x29, 0x9c, 0xcb, 0xb8, 0xb6, 0x50, 0xa9, 0xec, 0x73,
	0x46, 0xce, 0xc0, 0x80, 0xc0, 0x35, 0x9d, 0x8c, 0x1e, 0x64, 0x47, 0x5a, 0xe6, 0x0f, 0x06, 0x1c,
	0x6d, 0x62, 0x73, 0x88, 0x4f, 0x1b, 0xe4, 0xff, 0x04, 0xef, 0x67, 0x03, 0xc6, 0x96, 0x08, 0x66,
	0xe5, 0x55, 0x05, 0x32, 0xc6, 0x16, 0x57, 0x94, 0xd1, 0x5f, 0x45, 0x5d, 0x85, 0xe1, 0x12, 0xa9,
	0x52, 0x46, 0xd4, 0xb0, 0xdb, 0xbb, 0x1f, 0x80, 0x52, 0x97, 0xa3, 0xee, 0x32, 0x00, 0xae, 0x0a,
	0xc2, 0xfa, 0x1d, 0x94, 0x29, 0xa9, 0x1d, 0xed, 0xcd, 0xbf, 0x0c, 0x98, 0x74, 0x08, 0xa7, 0x5e,
	0x83, 0xb4, 0x71, 0x13, 0x87, 0x71, 0x0d, 0x0e, 0xeb, 0x2f, 0x45, 0xc7, 0xcc, 0x9a, 0xd8, 0xd8,
	0x9c, 0x7a, 0xe5, 0x05, 0xa1, 0x33, 0xaa, 0x0f, 0x62, 0x2e, 0x57, 0xe0, 0x58, 0x7b, 0x8a, 0x8a,
	0xb4, 0x41, 0x18, 0x73, 0x2b, 0x44, 0xf3, 0x7b, 0x72, 0x63, 0x73, 0xea, 0x78, 0x57, 0x25, 0x67,
	0xa2, 0x2d, 0x35, 0x77, 0xf4, 0x31, 0xba, 0x04, 0xe9, 0x78, 0x16, 0x15, 0x03, 0xac, 0x83, 0x4e,
	0x15, 0xc6, 0x36, 0x36, 0xa7, 0x0e, 0x77, 0x88, 0x9c, 0x91, 0x78, 0xfb, 0x11, 0xf6, 0xc9, 0xfc,
	0xef, 0x00, 0x63, 0x2a, 0x52, 0x95, 0xaf, 0x25, 0xc2, 0x1a, 0x6e, 0x99, 0xa0, 0x67, 0x06, 0x24,
	0xe5, 0x6b, 0x24, 0x68, 0xa6, 0x6b, 0xf9, 0x74, 0x74, 0xac, 0xec, 0xe9, 0x3e, 0x34, 0xd5, 0xc3,
	0x36, 0x4f, 0x7f, 0xfd, 0xdb, 0x1f, 0xdf, 0x25, 0x5e, 0x35, 0xa7, 0xda, 0x3e, 0xb0, 0xfa, 0xff,
	0xda, 0x38, 0x6f, 0xab, 0x15, 0xbf, 0x62, 0xcc, 0xa2, 0x6f, 0x0d, 0x18, 0xb8, 0x45, 0x04, 0xea,
	0xb3, 0x8c, 0xb3, 0xb9, 0x3d, 0x7a, 0x8f, 0xf9, 0xa6, 0xbc, 0xfb, 0x1c, 0xb2, 0x7b, 0xdf, 0x6d,
	0xaf, 0xb5, 0x67, 0x61, 0x1d, 0xdd, 0x83, 0xf4, 0x2d, 0x22, 0x3e, 0x71, 0xc5, 0x2a, 0xad, 0x8b,
	0x15, 0x67, 0xf1, 0xe5, 0x41, 0x3a, 0x80, 0x9e, 0x1b, 0x90, 0x54, 0x03, 0xa8, 0x87, 0xd7, 0xb6,
	0x09, 0x95, 0x3d, 0xfa, 0x42, 0x4d, 0xdf, 0x88, 0x3e, 0xd9, 0xe6, 0x4d, 0x19, 0xdf, 0x3b, 0xb3,
	0xd7, 0xfe, 0x59, 0x7c, 0x56, 0x67, 0xb8, 0xdf, 0x18, 0x90, 0x54, 0x6f, 0x19, 0x9d, 0xed, 0x0a,
	0x69, 0x97, 0xc7, 0xbe, 0x77, 0xb8, 0x33, 0x12, 0xa1, 0x69, 0x9e, 0xec, 0x82, 0x90, 0x4b, 0xa7,
	0x57, 0x8c, 0xd9, 0x39, 0x03, 0xfd, 0x69, 0xc0, 0x89, 0x45, 0x97, 0x8b, 0xa5, 0x7a, 0x18, 0x52,
	0x26, 0x48, 0xc5, 0x51, 0x3f, 0x76, 0xcd, 0x2d, 0x47, 0x77, 0x5b, 0x6f, 0x6b, 0x7e, 0xf8, 0xad,
	0xf6, 0x0f, 0xbf, 0x15, 0x7f, 0xf8, 0xad, 0x5e, 0xbe, 0xe2, 0x00, 0x9c, 0x97, 0xe9, 0x52, 0x57,
	0xfc, 0x29, 0x19, 0xf3, 0xb4, 0x39, 0xd9, 0x25, 0x66, 0xcf, 0xe5, 0x22, 0x2a, 0xf7, 0x06, 0x8c,
	0xef, 0xd6, 0x81, 0xd0, 0x85, 0xae, 0xa4, 0xf6, 0x68, 0x58, 0xd9, 0x3e, 0x2b, 0xd4, 0x3c, 0x80,
	0x7e, 0x34, 0x20, 0xb9, 0x50, 0xa9, 0x2c, 0xe3, 0x5a, 0x8f, 0x6c, 0xef, 0x32, 0x15, 0xbb, 0x96,
	0xe1, 0x5d, 0x19, 0xf0, 0x07, 0xd9, 0xdb, 0xff, 0xad, 0x0c, 0xed, 0x68, 0x20, 0xd8, 0x6b, 0x02,
	0xd7, 0xd6, 0xd1, 0x4f, 0x06, 0xa4, 0xd4, 0xcc, 0x8b, 0x60, 0xda, 0x7b, 0xc3, 0x6c, 0x1b, 0x90,
	0x7b, 0x21, 0x9d, 0x7d, 0x79, 0x48, 0x4b, 0x49, 0x79, 0xc5, 0xf9, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2b, 0x99, 0x65, 0xfb, 0xab, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FabricBundleServiceClient is the client API for FabricBundleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FabricBundleServiceClient interface {
	Create(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*CreationResponse, error)
	Get(ctx context.Context, in *FabricVersion, opts ...grpc.CallOption) (*Bundle, error)
	GetWithoutURL(ctx context.Context, in *FabricVersion, opts ...grpc.CallOption) (*Bundle, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Search(ctx context.Context, in *SearchBundleRequest, opts ...grpc.CallOption) (FabricBundleService_SearchClient, error)
	ListSupportedRuntimeVersions(ctx context.Context, in *v1alpha1.ListSupportedRuntimeVersionsRequest, opts ...grpc.CallOption) (*v1alpha1.ListSupportedRuntimeVersionsResponse, error)
	ResolveFabricVersion(ctx context.Context, in *ResolveFabricVersionRequest, opts ...grpc.CallOption) (*FabricVersion, error)
	AddTag(ctx context.Context, in *BundleTagAddRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveTag(ctx context.Context, in *BundleTagRemoveRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type fabricBundleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricBundleServiceClient(cc grpc.ClientConnInterface) FabricBundleServiceClient {
	return &fabricBundleServiceClient{cc}
}

func (c *fabricBundleServiceClient) Create(ctx context.Context, in *CreationRequest, opts ...grpc.CallOption) (*CreationResponse, error) {
	out := new(CreationResponse)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricBundleServiceClient) Get(ctx context.Context, in *FabricVersion, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricBundleServiceClient) GetWithoutURL(ctx context.Context, in *FabricVersion, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/GetWithoutURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricBundleServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricBundleServiceClient) Search(ctx context.Context, in *SearchBundleRequest, opts ...grpc.CallOption) (FabricBundleService_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FabricBundleService_serviceDesc.Streams[0], "/improbable.inner.bundle.FabricBundleService/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &fabricBundleServiceSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FabricBundleService_SearchClient interface {
	Recv() (*Bundle, error)
	grpc.ClientStream
}

type fabricBundleServiceSearchClient struct {
	grpc.ClientStream
}

func (x *fabricBundleServiceSearchClient) Recv() (*Bundle, error) {
	m := new(Bundle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fabricBundleServiceClient) ListSupportedRuntimeVersions(ctx context.Context, in *v1alpha1.ListSupportedRuntimeVersionsRequest, opts ...grpc.CallOption) (*v1alpha1.ListSupportedRuntimeVersionsResponse, error) {
	out := new(v1alpha1.ListSupportedRuntimeVersionsResponse)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/ListSupportedRuntimeVersions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricBundleServiceClient) ResolveFabricVersion(ctx context.Context, in *ResolveFabricVersionRequest, opts ...grpc.CallOption) (*FabricVersion, error) {
	out := new(FabricVersion)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/ResolveFabricVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricBundleServiceClient) AddTag(ctx context.Context, in *BundleTagAddRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/AddTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricBundleServiceClient) RemoveTag(ctx context.Context, in *BundleTagRemoveRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/improbable.inner.bundle.FabricBundleService/RemoveTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabricBundleServiceServer is the server API for FabricBundleService service.
type FabricBundleServiceServer interface {
	Create(context.Context, *CreationRequest) (*CreationResponse, error)
	Get(context.Context, *FabricVersion) (*Bundle, error)
	GetWithoutURL(context.Context, *FabricVersion) (*Bundle, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	Search(*SearchBundleRequest, FabricBundleService_SearchServer) error
	ListSupportedRuntimeVersions(context.Context, *v1alpha1.ListSupportedRuntimeVersionsRequest) (*v1alpha1.ListSupportedRuntimeVersionsResponse, error)
	ResolveFabricVersion(context.Context, *ResolveFabricVersionRequest) (*FabricVersion, error)
	AddTag(context.Context, *BundleTagAddRequest) (*empty.Empty, error)
	RemoveTag(context.Context, *BundleTagRemoveRequest) (*empty.Empty, error)
}

// UnimplementedFabricBundleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFabricBundleServiceServer struct {
}

func (*UnimplementedFabricBundleServiceServer) Create(ctx context.Context, req *CreationRequest) (*CreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedFabricBundleServiceServer) Get(ctx context.Context, req *FabricVersion) (*Bundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedFabricBundleServiceServer) GetWithoutURL(ctx context.Context, req *FabricVersion) (*Bundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithoutURL not implemented")
}
func (*UnimplementedFabricBundleServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedFabricBundleServiceServer) Search(req *SearchBundleRequest, srv FabricBundleService_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedFabricBundleServiceServer) ListSupportedRuntimeVersions(ctx context.Context, req *v1alpha1.ListSupportedRuntimeVersionsRequest) (*v1alpha1.ListSupportedRuntimeVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSupportedRuntimeVersions not implemented")
}
func (*UnimplementedFabricBundleServiceServer) ResolveFabricVersion(ctx context.Context, req *ResolveFabricVersionRequest) (*FabricVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveFabricVersion not implemented")
}
func (*UnimplementedFabricBundleServiceServer) AddTag(ctx context.Context, req *BundleTagAddRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTag not implemented")
}
func (*UnimplementedFabricBundleServiceServer) RemoveTag(ctx context.Context, req *BundleTagRemoveRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTag not implemented")
}

func RegisterFabricBundleServiceServer(s *grpc.Server, srv FabricBundleServiceServer) {
	s.RegisterService(&_FabricBundleService_serviceDesc, srv)
}

func _FabricBundleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).Create(ctx, req.(*CreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricBundleService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).Get(ctx, req.(*FabricVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricBundleService_GetWithoutURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).GetWithoutURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/GetWithoutURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).GetWithoutURL(ctx, req.(*FabricVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricBundleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricBundleService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchBundleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FabricBundleServiceServer).Search(m, &fabricBundleServiceSearchServer{stream})
}

type FabricBundleService_SearchServer interface {
	Send(*Bundle) error
	grpc.ServerStream
}

type fabricBundleServiceSearchServer struct {
	grpc.ServerStream
}

func (x *fabricBundleServiceSearchServer) Send(m *Bundle) error {
	return x.ServerStream.SendMsg(m)
}

func _FabricBundleService_ListSupportedRuntimeVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1alpha1.ListSupportedRuntimeVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).ListSupportedRuntimeVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/ListSupportedRuntimeVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).ListSupportedRuntimeVersions(ctx, req.(*v1alpha1.ListSupportedRuntimeVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricBundleService_ResolveFabricVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveFabricVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).ResolveFabricVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/ResolveFabricVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).ResolveFabricVersion(ctx, req.(*ResolveFabricVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricBundleService_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BundleTagAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/AddTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).AddTag(ctx, req.(*BundleTagAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricBundleService_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BundleTagRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricBundleServiceServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.inner.bundle.FabricBundleService/RemoveTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricBundleServiceServer).RemoveTag(ctx, req.(*BundleTagRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FabricBundleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "improbable.inner.bundle.FabricBundleService",
	HandlerType: (*FabricBundleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _FabricBundleService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _FabricBundleService_Get_Handler,
		},
		{
			MethodName: "GetWithoutURL",
			Handler:    _FabricBundleService_GetWithoutURL_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FabricBundleService_Delete_Handler,
		},
		{
			MethodName: "ListSupportedRuntimeVersions",
			Handler:    _FabricBundleService_ListSupportedRuntimeVersions_Handler,
		},
		{
			MethodName: "ResolveFabricVersion",
			Handler:    _FabricBundleService_ResolveFabricVersion_Handler,
		},
		{
			MethodName: "AddTag",
			Handler:    _FabricBundleService_AddTag_Handler,
		},
		{
			MethodName: "RemoveTag",
			Handler:    _FabricBundleService_RemoveTag_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _FabricBundleService_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "improbable/inner/fabric_bundle/fabric_bundle.proto",
}
