// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/ext/plugin/auth/test/example.proto

package improbable_ext_plugin_auth_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	github_com_improbable_io_go_proto_logfields "github.com/improbable-io/go-proto-logfields"
	_ "improbable.io/proto/improbable/ext/plugin/auth"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *MyDeployment) LogFields() map[string]string {
	return map[string]string{}
}

func (this *MyDeployment) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *MyRequest) LogFields() map[string]string {
	// Handle being called on nil message.
	if this == nil {
		return map[string]string{}
	}
	// Gather fields from oneofs and child messages.
	var hasInner bool
	projectFields := github_com_improbable_io_go_proto_logfields.ExtractLogFieldsFromMessage(this.Project)
	hasInner = hasInner || len(projectFields) > 0
	dplFields := github_com_improbable_io_go_proto_logfields.ExtractLogFieldsFromMessage(this.Dpl)
	hasInner = hasInner || len(dplFields) > 0
	if !hasInner {
		// If no inner messages added any fields, avoid merging maps.
		return map[string]string{}
	}
	// Merge all the field maps.
	res := map[string]string{}
	for k, v := range projectFields {
		res[k] = v
	}
	for k, v := range dplFields {
		res[k] = v
	}
	return res
}

func (this *MyRequest) ExtractRequestFields(dst map[string]interface{}) {
	// Handle being called on nil message.
	if this == nil {
		return
	}

	github_com_improbable_io_go_proto_logfields.ExtractRequestFieldsFromMessage(this.Project, dst)
	github_com_improbable_io_go_proto_logfields.ExtractRequestFieldsFromMessage(this.Dpl, dst)
}

func (this *MyRequest_MyProject) LogFields() map[string]string {
	return map[string]string{}
}

func (this *MyRequest_MyProject) ExtractRequestFields(dst map[string]interface{}) {
}
