// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/platform/inner/worker_nanny_status.proto

package improbable_platform_inner

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	deployment "improbable.io/proto/improbable/platform/deployment"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterWorkerNannyRequest struct {
	WorkerNodeId         *deployment.WorkerNodeId `protobuf:"bytes,1,opt,name=worker_node_id,json=workerNodeId,proto3" json:"worker_node_id,omitempty"`
	ApiPort              int32                    `protobuf:"varint,2,opt,name=api_port,json=apiPort,proto3" json:"api_port,omitempty"`
	PsdashPort           int32                    `protobuf:"varint,3,opt,name=psdash_port,json=psdashPort,proto3" json:"psdash_port,omitempty"`
	FsdashPort           int32                    `protobuf:"varint,4,opt,name=fsdash_port,json=fsdashPort,proto3" json:"fsdash_port,omitempty"`
	ApiTlsPort           int32                    `protobuf:"varint,5,opt,name=api_tls_port,json=apiTlsPort,proto3" json:"api_tls_port,omitempty"`
	StatusPort           int32                    `protobuf:"varint,6,opt,name=status_port,json=statusPort,proto3" json:"status_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RegisterWorkerNannyRequest) Reset()         { *m = RegisterWorkerNannyRequest{} }
func (m *RegisterWorkerNannyRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterWorkerNannyRequest) ProtoMessage()    {}
func (*RegisterWorkerNannyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5600dde07bf8e240, []int{0}
}

func (m *RegisterWorkerNannyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWorkerNannyRequest.Unmarshal(m, b)
}
func (m *RegisterWorkerNannyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWorkerNannyRequest.Marshal(b, m, deterministic)
}
func (m *RegisterWorkerNannyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWorkerNannyRequest.Merge(m, src)
}
func (m *RegisterWorkerNannyRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterWorkerNannyRequest.Size(m)
}
func (m *RegisterWorkerNannyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWorkerNannyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWorkerNannyRequest proto.InternalMessageInfo

func (m *RegisterWorkerNannyRequest) GetWorkerNodeId() *deployment.WorkerNodeId {
	if m != nil {
		return m.WorkerNodeId
	}
	return nil
}

func (m *RegisterWorkerNannyRequest) GetApiPort() int32 {
	if m != nil {
		return m.ApiPort
	}
	return 0
}

func (m *RegisterWorkerNannyRequest) GetPsdashPort() int32 {
	if m != nil {
		return m.PsdashPort
	}
	return 0
}

func (m *RegisterWorkerNannyRequest) GetFsdashPort() int32 {
	if m != nil {
		return m.FsdashPort
	}
	return 0
}

func (m *RegisterWorkerNannyRequest) GetApiTlsPort() int32 {
	if m != nil {
		return m.ApiTlsPort
	}
	return 0
}

func (m *RegisterWorkerNannyRequest) GetStatusPort() int32 {
	if m != nil {
		return m.StatusPort
	}
	return 0
}

type RegisterWorkerNannyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterWorkerNannyResponse) Reset()         { *m = RegisterWorkerNannyResponse{} }
func (m *RegisterWorkerNannyResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterWorkerNannyResponse) ProtoMessage()    {}
func (*RegisterWorkerNannyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5600dde07bf8e240, []int{1}
}

func (m *RegisterWorkerNannyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWorkerNannyResponse.Unmarshal(m, b)
}
func (m *RegisterWorkerNannyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWorkerNannyResponse.Marshal(b, m, deterministic)
}
func (m *RegisterWorkerNannyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWorkerNannyResponse.Merge(m, src)
}
func (m *RegisterWorkerNannyResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterWorkerNannyResponse.Size(m)
}
func (m *RegisterWorkerNannyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWorkerNannyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWorkerNannyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterWorkerNannyRequest)(nil), "improbable.platform.inner.RegisterWorkerNannyRequest")
	proto.RegisterType((*RegisterWorkerNannyResponse)(nil), "improbable.platform.inner.RegisterWorkerNannyResponse")
}

func init() {
	proto.RegisterFile("improbable/platform/inner/worker_nanny_status.proto", fileDescriptor_5600dde07bf8e240)
}

var fileDescriptor_5600dde07bf8e240 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0x53, 0xee, 0x05, 0xcd, 0x40, 0x4c, 0xac, 0x1b, 0xa8, 0x31, 0x34, 0xac, 0x58, 0xc8,
	0xd4, 0x40, 0xe4, 0x01, 0xdc, 0xb9, 0x31, 0xa6, 0x9a, 0x98, 0xb8, 0x69, 0xa6, 0xce, 0x00, 0x13,
	0xda, 0x39, 0xe3, 0xcc, 0xc1, 0x86, 0xbd, 0x0f, 0x61, 0x7c, 0x39, 0x13, 0x9f, 0xc4, 0xd0, 0x11,
	0xe8, 0xa2, 0x2c, 0xdc, 0x35, 0xe7, 0x7c, 0xdf, 0xdf, 0x3f, 0x73, 0xc8, 0x44, 0xe6, 0xda, 0x40,
	0xca, 0xd2, 0x4c, 0x44, 0x3a, 0x63, 0x38, 0x03, 0x93, 0x47, 0x52, 0x29, 0x61, 0xa2, 0x02, 0xcc,
	0x52, 0x98, 0x44, 0x31, 0xa5, 0xd6, 0x89, 0x45, 0x86, 0x2b, 0x4b, 0xb5, 0x01, 0x04, 0xbf, 0xb7,
	0x97, 0xe8, 0x56, 0xa2, 0xa5, 0x14, 0x4c, 0xe7, 0x12, 0x17, 0xab, 0x94, 0xbe, 0x40, 0x1e, 0xe5,
	0x85, 0xc4, 0x25, 0x14, 0xd1, 0x1c, 0x46, 0xa5, 0x37, 0x7a, 0x63, 0x99, 0xe4, 0x0c, 0xc1, 0xd8,
	0x68, 0xf7, 0xe9, 0x22, 0x83, 0xab, 0xba, 0x1e, 0x5c, 0xe8, 0x0c, 0xd6, 0xb9, 0x50, 0xb8, 0x2b,
	0x03, 0x5c, 0x38, 0x63, 0xf0, 0xd1, 0x20, 0x41, 0x2c, 0xe6, 0xd2, 0xa2, 0x30, 0x4f, 0xe5, 0xf6,
	0x6e, 0xd3, 0x34, 0x16, 0xaf, 0x2b, 0x61, 0xd1, 0x7f, 0x26, 0x27, 0x15, 0x27, 0x91, 0xbc, 0xeb,
	0x85, 0xde, 0xb0, 0x3d, 0xbe, 0xa4, 0x75, 0xe5, 0xf7, 0x7f, 0xa2, 0xbf, 0x59, 0xc0, 0xc5, 0x2d,
	0xbf, 0x69, 0x7d, 0x7f, 0xf5, 0x1b, 0xa1, 0x17, 0x77, 0x8a, 0xca, 0xd4, 0xef, 0x91, 0x63, 0xa6,
	0x65, 0xa2, 0xc1, 0x60, 0xb7, 0x11, 0x7a, 0xc3, 0x66, 0x7c, 0xc4, 0xb4, 0xbc, 0x07, 0x83, 0x7e,
	0x9f, 0xb4, 0xb5, 0xe5, 0xcc, 0x2e, 0xdc, 0xf6, 0x5f, 0xb9, 0x25, 0x6e, 0xb4, 0x05, 0x66, 0x15,
	0xe0, 0xbf, 0x03, 0x66, 0x7b, 0x20, 0x24, 0x9d, 0x4d, 0x38, 0x66, 0xd6, 0x11, 0x4d, 0x47, 0x30,
	0x2d, 0x1f, 0x33, 0xbb, 0x8d, 0x70, 0xe7, 0x70, 0x40, 0xcb, 0x01, 0x6e, 0xb4, 0x01, 0x06, 0x17,
	0xe4, 0xbc, 0xf6, 0x65, 0xac, 0x06, 0x65, 0xc5, 0xf8, 0xd3, 0x23, 0xa7, 0x95, 0xf9, 0x43, 0x29,
	0xfa, 0xef, 0x1e, 0x39, 0xab, 0xb1, 0xfc, 0x6b, 0x7a, 0xf0, 0xda, 0xf4, 0xf0, 0xfb, 0x07, 0xd3,
	0xbf, 0x6a, 0xae, 0x5c, 0xda, 0x2a, 0xaf, 0x3b, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x23, 0x37,
	0x44, 0x06, 0x99, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorkerNannyStatusClient is the client API for WorkerNannyStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerNannyStatusClient interface {
	RegisterWorkerNanny(ctx context.Context, in *RegisterWorkerNannyRequest, opts ...grpc.CallOption) (*RegisterWorkerNannyResponse, error)
}

type workerNannyStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerNannyStatusClient(cc grpc.ClientConnInterface) WorkerNannyStatusClient {
	return &workerNannyStatusClient{cc}
}

func (c *workerNannyStatusClient) RegisterWorkerNanny(ctx context.Context, in *RegisterWorkerNannyRequest, opts ...grpc.CallOption) (*RegisterWorkerNannyResponse, error) {
	out := new(RegisterWorkerNannyResponse)
	err := c.cc.Invoke(ctx, "/improbable.platform.inner.WorkerNannyStatus/RegisterWorkerNanny", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerNannyStatusServer is the server API for WorkerNannyStatus service.
type WorkerNannyStatusServer interface {
	RegisterWorkerNanny(context.Context, *RegisterWorkerNannyRequest) (*RegisterWorkerNannyResponse, error)
}

// UnimplementedWorkerNannyStatusServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerNannyStatusServer struct {
}

func (*UnimplementedWorkerNannyStatusServer) RegisterWorkerNanny(ctx context.Context, req *RegisterWorkerNannyRequest) (*RegisterWorkerNannyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorkerNanny not implemented")
}

func RegisterWorkerNannyStatusServer(s *grpc.Server, srv WorkerNannyStatusServer) {
	s.RegisterService(&_WorkerNannyStatus_serviceDesc, srv)
}

func _WorkerNannyStatus_RegisterWorkerNanny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerNannyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNannyStatusServer).RegisterWorkerNanny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.platform.inner.WorkerNannyStatus/RegisterWorkerNanny",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNannyStatusServer).RegisterWorkerNanny(ctx, req.(*RegisterWorkerNannyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkerNannyStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "improbable.platform.inner.WorkerNannyStatus",
	HandlerType: (*WorkerNannyStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorkerNanny",
			Handler:    _WorkerNannyStatus_RegisterWorkerNanny_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "improbable/platform/inner/worker_nanny_status.proto",
}
