// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/ext/postie/options/options.proto

package improbable_ext_postie_options

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ESGrpcCoordinates struct {
	QueryName            string   `protobuf:"bytes,1,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	ServiceName          string   `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName           string   `protobuf:"bytes,4,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ESGrpcCoordinates) Reset()         { *m = ESGrpcCoordinates{} }
func (m *ESGrpcCoordinates) String() string { return proto.CompactTextString(m) }
func (*ESGrpcCoordinates) ProtoMessage()    {}
func (*ESGrpcCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5c52210d0d8048, []int{0}
}

func (m *ESGrpcCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ESGrpcCoordinates.Unmarshal(m, b)
}
func (m *ESGrpcCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ESGrpcCoordinates.Marshal(b, m, deterministic)
}
func (m *ESGrpcCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ESGrpcCoordinates.Merge(m, src)
}
func (m *ESGrpcCoordinates) XXX_Size() int {
	return xxx_messageInfo_ESGrpcCoordinates.Size(m)
}
func (m *ESGrpcCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_ESGrpcCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_ESGrpcCoordinates proto.InternalMessageInfo

func (m *ESGrpcCoordinates) GetQueryName() string {
	if m != nil {
		return m.QueryName
	}
	return ""
}

func (m *ESGrpcCoordinates) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ESGrpcCoordinates) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ESGrpcCoordinates) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

type ESField struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ESField) Reset()         { *m = ESField{} }
func (m *ESField) String() string { return proto.CompactTextString(m) }
func (*ESField) ProtoMessage()    {}
func (*ESField) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5c52210d0d8048, []int{1}
}

func (m *ESField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ESField.Unmarshal(m, b)
}
func (m *ESField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ESField.Marshal(b, m, deterministic)
}
func (m *ESField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ESField.Merge(m, src)
}
func (m *ESField) XXX_Size() int {
	return xxx_messageInfo_ESField.Size(m)
}
func (m *ESField) XXX_DiscardUnknown() {
	xxx_messageInfo_ESField.DiscardUnknown(m)
}

var xxx_messageInfo_ESField proto.InternalMessageInfo

func (m *ESField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BQTableReference struct {
	DatasetId            string   `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	TableId              string   `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BQTableReference) Reset()         { *m = BQTableReference{} }
func (m *BQTableReference) String() string { return proto.CompactTextString(m) }
func (*BQTableReference) ProtoMessage()    {}
func (*BQTableReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5c52210d0d8048, []int{2}
}

func (m *BQTableReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BQTableReference.Unmarshal(m, b)
}
func (m *BQTableReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BQTableReference.Marshal(b, m, deterministic)
}
func (m *BQTableReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BQTableReference.Merge(m, src)
}
func (m *BQTableReference) XXX_Size() int {
	return xxx_messageInfo_BQTableReference.Size(m)
}
func (m *BQTableReference) XXX_DiscardUnknown() {
	xxx_messageInfo_BQTableReference.DiscardUnknown(m)
}

var xxx_messageInfo_BQTableReference proto.InternalMessageInfo

func (m *BQTableReference) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func (m *BQTableReference) GetTableId() string {
	if m != nil {
		return m.TableId
	}
	return ""
}

type BQColumn struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BQColumn) Reset()         { *m = BQColumn{} }
func (m *BQColumn) String() string { return proto.CompactTextString(m) }
func (*BQColumn) ProtoMessage()    {}
func (*BQColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5c52210d0d8048, []int{3}
}

func (m *BQColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BQColumn.Unmarshal(m, b)
}
func (m *BQColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BQColumn.Marshal(b, m, deterministic)
}
func (m *BQColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BQColumn.Merge(m, src)
}
func (m *BQColumn) XXX_Size() int {
	return xxx_messageInfo_BQColumn.Size(m)
}
func (m *BQColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_BQColumn.DiscardUnknown(m)
}

var xxx_messageInfo_BQColumn proto.InternalMessageInfo

func (m *BQColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

var E_EsGrpcCoordinates = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*ESGrpcCoordinates)(nil),
	Field:         50001,
	Name:          "improbable.ext.postie.options.es_grpc_coordinates",
	Tag:           "bytes,50001,opt,name=es_grpc_coordinates",
	Filename:      "improbable/ext/postie/options/options.proto",
}

var E_EsField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*ESField)(nil),
	Field:         50002,
	Name:          "improbable.ext.postie.options.es_field",
	Tag:           "bytes,50002,opt,name=es_field",
	Filename:      "improbable/ext/postie/options/options.proto",
}

var E_BqTableReference = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*BQTableReference)(nil),
	Field:         50003,
	Name:          "improbable.ext.postie.options.bq_table_reference",
	Tag:           "bytes,50003,opt,name=bq_table_reference",
	Filename:      "improbable/ext/postie/options/options.proto",
}

var E_BqColumn = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*BQColumn)(nil),
	Field:         50004,
	Name:          "improbable.ext.postie.options.bq_column",
	Tag:           "bytes,50004,opt,name=bq_column",
	Filename:      "improbable/ext/postie/options/options.proto",
}

func init() {
	proto.RegisterType((*ESGrpcCoordinates)(nil), "improbable.ext.postie.options.ESGrpcCoordinates")
	proto.RegisterType((*ESField)(nil), "improbable.ext.postie.options.ESField")
	proto.RegisterType((*BQTableReference)(nil), "improbable.ext.postie.options.BQTableReference")
	proto.RegisterType((*BQColumn)(nil), "improbable.ext.postie.options.BQColumn")
	proto.RegisterExtension(E_EsGrpcCoordinates)
	proto.RegisterExtension(E_EsField)
	proto.RegisterExtension(E_BqTableReference)
	proto.RegisterExtension(E_BqColumn)
}

func init() {
	proto.RegisterFile("improbable/ext/postie/options/options.proto", fileDescriptor_1b5c52210d0d8048)
}

var fileDescriptor_1b5c52210d0d8048 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0xab, 0xd3, 0x40,
	0x14, 0xc5, 0x89, 0xef, 0x61, 0xd3, 0x5b, 0x17, 0x7d, 0xe3, 0xa6, 0x0a, 0xd5, 0x9a, 0x85, 0x0a,
	0xc2, 0x44, 0x74, 0x97, 0x65, 0x4b, 0x95, 0x82, 0x28, 0x4d, 0xdd, 0x87, 0x4c, 0xe6, 0x36, 0x0e,
	0x24, 0x99, 0x64, 0x66, 0x2a, 0x75, 0x23, 0xb8, 0x11, 0xbf, 0x9e, 0x7f, 0x3e, 0x90, 0x64, 0x26,
	0xa5, 0xb5, 0x3e, 0x9a, 0x55, 0x6e, 0xce, 0x9c, 0x3b, 0xbf, 0x3b, 0xe7, 0xc2, 0x0b, 0x51, 0xd6,
	0x4a, 0xb2, 0x94, 0x15, 0x18, 0xe2, 0xde, 0x84, 0xb5, 0xd4, 0x46, 0x60, 0x28, 0x6b, 0x23, 0x64,
	0xa5, 0x0f, 0x5f, 0x5a, 0x2b, 0x69, 0x24, 0x99, 0x1e, 0xcd, 0x14, 0xf7, 0x86, 0x3a, 0x33, 0xed,
	0x4c, 0x0f, 0x67, 0xb9, 0x94, 0x79, 0x81, 0xa1, 0x35, 0xb3, 0xdd, 0x36, 0xe4, 0xa8, 0x33, 0x25,
	0x6a, 0x23, 0x95, 0xbb, 0x20, 0xf8, 0xe1, 0xc1, 0xcd, 0x72, 0xf3, 0x56, 0xd5, 0xd9, 0x42, 0x4a,
	0xc5, 0x45, 0x95, 0x1a, 0xd4, 0x64, 0x0a, 0xd0, 0xec, 0x50, 0x7d, 0x49, 0xaa, 0xb4, 0xc4, 0x89,
	0x37, 0xf3, 0x9e, 0x0f, 0xe3, 0xa1, 0x55, 0xde, 0xa7, 0x25, 0x92, 0x31, 0x5c, 0x99, 0x34, 0x9f,
	0xdc, 0xb1, 0x7a, 0x5b, 0x92, 0x27, 0x70, 0x4f, 0xa3, 0xfa, 0x2c, 0x32, 0x74, 0x2d, 0x57, 0xf6,
	0x68, 0xd4, 0x69, 0xb6, 0xe9, 0x31, 0x8c, 0x4a, 0x34, 0x9f, 0x24, 0x77, 0x8e, 0x6b, 0xeb, 0x00,
	0x27, 0xb5, 0x86, 0x60, 0x0a, 0x83, 0xe5, 0xe6, 0x8d, 0xc0, 0x82, 0x13, 0x02, 0xd7, 0x27, 0x64,
	0x5b, 0x07, 0xef, 0x60, 0x3c, 0x5f, 0x7f, 0x6c, 0x5f, 0x1a, 0xe3, 0x16, 0x15, 0x56, 0x19, 0xb6,
	0x73, 0xf2, 0xd4, 0xa4, 0x1a, 0x4d, 0x22, 0xf8, 0x61, 0xce, 0x4e, 0x59, 0x71, 0xf2, 0x00, 0x7c,
	0xd3, 0x36, 0xb4, 0x87, 0x6e, 0xd8, 0x81, 0xfd, 0x5f, 0xf1, 0xe0, 0x11, 0xf8, 0xf3, 0xf5, 0x42,
	0x16, 0xbb, 0xb2, 0xba, 0x8d, 0x16, 0x7d, 0xf3, 0xe0, 0x3e, 0xea, 0x24, 0x57, 0x75, 0x96, 0x64,
	0xa7, 0xc9, 0x50, 0x17, 0x29, 0x3d, 0x44, 0x4a, 0xed, 0xc4, 0x1f, 0x5c, 0xe0, 0x93, 0x9f, 0xdf,
	0xdb, 0x97, 0x8f, 0x5e, 0xbd, 0xa4, 0x17, 0x17, 0x43, 0xff, 0x8b, 0x3c, 0xbe, 0x41, 0x7d, 0x26,
	0x45, 0x0c, 0x7c, 0xd4, 0xc9, 0xd6, 0x26, 0xd2, 0xc3, 0xfd, 0xd5, 0x71, 0x9f, 0xf6, 0x72, 0x6d,
	0x5b, 0x3c, 0x40, 0x6d, 0x8b, 0xe8, 0x2b, 0x10, 0xd6, 0x24, 0x2e, 0x25, 0x75, 0xcc, 0xf5, 0x32,
	0xed, 0x77, 0x47, 0x0b, 0x7b, 0x68, 0xe7, 0xfb, 0x8a, 0xc7, 0xac, 0xf9, 0x57, 0x89, 0x10, 0x86,
	0xac, 0x49, 0x32, 0xb7, 0x88, 0x1e, 0xec, 0x9f, 0x0e, 0xfb, 0xac, 0x17, 0xeb, 0x16, 0x1b, 0xfb,
	0xac, 0x71, 0x15, 0xbb, 0x6b, 0x6f, 0x7c, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xd1, 0xa7,
	0x68, 0x5d, 0x03, 0x00, 0x00,
}
