// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/platform/assembly/bridge_config.proto

package improbable_platform_assembly

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	runtime "improbable.io/proto/improbable/platform/runtime"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageDelivery int32

const (
	MessageDelivery_RELIABLE_ORDERED   MessageDelivery = 0
	MessageDelivery_UNRELIABLE_ORDERED MessageDelivery = 1
)

var MessageDelivery_name = map[int32]string{
	0: "RELIABLE_ORDERED",
	1: "UNRELIABLE_ORDERED",
}

var MessageDelivery_value = map[string]int32{
	"RELIABLE_ORDERED":   0,
	"UNRELIABLE_ORDERED": 1,
}

func (x MessageDelivery) String() string {
	return proto.EnumName(MessageDelivery_name, int32(x))
}

func (MessageDelivery) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{0}
}

type EncodingType int32

const (
	EncodingType_BASIC                       EncodingType = 0
	EncodingType_BINARY_DELTA_COMPRESSION    EncodingType = 1
	EncodingType_QUEUE_DELTA_COMPRESSION     EncodingType = 2
	EncodingType_HEURISTIC_DELTA_COMPRESSION EncodingType = 3
)

var EncodingType_name = map[int32]string{
	0: "BASIC",
	1: "BINARY_DELTA_COMPRESSION",
	2: "QUEUE_DELTA_COMPRESSION",
	3: "HEURISTIC_DELTA_COMPRESSION",
}

var EncodingType_value = map[string]int32{
	"BASIC":                       0,
	"BINARY_DELTA_COMPRESSION":    1,
	"QUEUE_DELTA_COMPRESSION":     2,
	"HEURISTIC_DELTA_COMPRESSION": 3,
}

func (x EncodingType) String() string {
	return proto.EnumName(EncodingType_name, int32(x))
}

func (EncodingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{1}
}

type RangeEntityInterest struct {
	Radius               float64  `protobuf:"fixed64,1,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeEntityInterest) Reset()         { *m = RangeEntityInterest{} }
func (m *RangeEntityInterest) String() string { return proto.CompactTextString(m) }
func (*RangeEntityInterest) ProtoMessage()    {}
func (*RangeEntityInterest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{0}
}

func (m *RangeEntityInterest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeEntityInterest.Unmarshal(m, b)
}
func (m *RangeEntityInterest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeEntityInterest.Marshal(b, m, deterministic)
}
func (m *RangeEntityInterest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeEntityInterest.Merge(m, src)
}
func (m *RangeEntityInterest) XXX_Size() int {
	return xxx_messageInfo_RangeEntityInterest.Size(m)
}
func (m *RangeEntityInterest) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeEntityInterest.DiscardUnknown(m)
}

var xxx_messageInfo_RangeEntityInterest proto.InternalMessageInfo

func (m *RangeEntityInterest) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type EntityInterest struct {
	// Types that are valid to be assigned to EntityInterest:
	//	*EntityInterest_RangeEntityInterest
	EntityInterest       isEntityInterest_EntityInterest `protobuf_oneof:"entity_interest"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *EntityInterest) Reset()         { *m = EntityInterest{} }
func (m *EntityInterest) String() string { return proto.CompactTextString(m) }
func (*EntityInterest) ProtoMessage()    {}
func (*EntityInterest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{1}
}

func (m *EntityInterest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityInterest.Unmarshal(m, b)
}
func (m *EntityInterest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityInterest.Marshal(b, m, deterministic)
}
func (m *EntityInterest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityInterest.Merge(m, src)
}
func (m *EntityInterest) XXX_Size() int {
	return xxx_messageInfo_EntityInterest.Size(m)
}
func (m *EntityInterest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityInterest.DiscardUnknown(m)
}

var xxx_messageInfo_EntityInterest proto.InternalMessageInfo

type isEntityInterest_EntityInterest interface {
	isEntityInterest_EntityInterest()
}

type EntityInterest_RangeEntityInterest struct {
	RangeEntityInterest *RangeEntityInterest `protobuf:"bytes,1,opt,name=range_entity_interest,json=rangeEntityInterest,proto3,oneof"`
}

func (*EntityInterest_RangeEntityInterest) isEntityInterest_EntityInterest() {}

func (m *EntityInterest) GetEntityInterest() isEntityInterest_EntityInterest {
	if m != nil {
		return m.EntityInterest
	}
	return nil
}

func (m *EntityInterest) GetRangeEntityInterest() *RangeEntityInterest {
	if x, ok := m.GetEntityInterest().(*EntityInterest_RangeEntityInterest); ok {
		return x.RangeEntityInterest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EntityInterest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EntityInterest_RangeEntityInterest)(nil),
	}
}

type ComponentDelivery struct {
	CheckoutInitially    bool            `protobuf:"varint,1,opt,name=checkout_initially,json=checkoutInitially,proto3" json:"checkout_initially,omitempty"`
	MessageDelivery      MessageDelivery `protobuf:"varint,2,opt,name=message_delivery,json=messageDelivery,proto3,enum=improbable.platform.assembly.MessageDelivery" json:"message_delivery,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ComponentDelivery) Reset()         { *m = ComponentDelivery{} }
func (m *ComponentDelivery) String() string { return proto.CompactTextString(m) }
func (*ComponentDelivery) ProtoMessage()    {}
func (*ComponentDelivery) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{2}
}

func (m *ComponentDelivery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentDelivery.Unmarshal(m, b)
}
func (m *ComponentDelivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentDelivery.Marshal(b, m, deterministic)
}
func (m *ComponentDelivery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentDelivery.Merge(m, src)
}
func (m *ComponentDelivery) XXX_Size() int {
	return xxx_messageInfo_ComponentDelivery.Size(m)
}
func (m *ComponentDelivery) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentDelivery.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentDelivery proto.InternalMessageInfo

func (m *ComponentDelivery) GetCheckoutInitially() bool {
	if m != nil {
		return m.CheckoutInitially
	}
	return false
}

func (m *ComponentDelivery) GetMessageDelivery() MessageDelivery {
	if m != nil {
		return m.MessageDelivery
	}
	return MessageDelivery_RELIABLE_ORDERED
}

type ComponentDeliveryConfiguration struct {
	Default              MessageDelivery               `protobuf:"varint,1,opt,name=default,proto3,enum=improbable.platform.assembly.MessageDelivery" json:"default,omitempty"`
	CheckoutAllInitially bool                          `protobuf:"varint,2,opt,name=checkout_all_initially,json=checkoutAllInitially,proto3" json:"checkout_all_initially,omitempty"`
	Override             map[string]*ComponentDelivery `protobuf:"bytes,3,rep,name=override,proto3" json:"override,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ComponentDeliveryConfiguration) Reset()         { *m = ComponentDeliveryConfiguration{} }
func (m *ComponentDeliveryConfiguration) String() string { return proto.CompactTextString(m) }
func (*ComponentDeliveryConfiguration) ProtoMessage()    {}
func (*ComponentDeliveryConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{3}
}

func (m *ComponentDeliveryConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentDeliveryConfiguration.Unmarshal(m, b)
}
func (m *ComponentDeliveryConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentDeliveryConfiguration.Marshal(b, m, deterministic)
}
func (m *ComponentDeliveryConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentDeliveryConfiguration.Merge(m, src)
}
func (m *ComponentDeliveryConfiguration) XXX_Size() int {
	return xxx_messageInfo_ComponentDeliveryConfiguration.Size(m)
}
func (m *ComponentDeliveryConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentDeliveryConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentDeliveryConfiguration proto.InternalMessageInfo

func (m *ComponentDeliveryConfiguration) GetDefault() MessageDelivery {
	if m != nil {
		return m.Default
	}
	return MessageDelivery_RELIABLE_ORDERED
}

func (m *ComponentDeliveryConfiguration) GetCheckoutAllInitially() bool {
	if m != nil {
		return m.CheckoutAllInitially
	}
	return false
}

func (m *ComponentDeliveryConfiguration) GetOverride() map[string]*ComponentDelivery {
	if m != nil {
		return m.Override
	}
	return nil
}

type AssetContextConfiguration struct {
	UsePlayerContextIfAuthoritative bool     `protobuf:"varint,1,opt,name=use_player_context_if_authoritative,json=usePlayerContextIfAuthoritative,proto3" json:"use_player_context_if_authoritative,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *AssetContextConfiguration) Reset()         { *m = AssetContextConfiguration{} }
func (m *AssetContextConfiguration) String() string { return proto.CompactTextString(m) }
func (*AssetContextConfiguration) ProtoMessage()    {}
func (*AssetContextConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{4}
}

func (m *AssetContextConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetContextConfiguration.Unmarshal(m, b)
}
func (m *AssetContextConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetContextConfiguration.Marshal(b, m, deterministic)
}
func (m *AssetContextConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetContextConfiguration.Merge(m, src)
}
func (m *AssetContextConfiguration) XXX_Size() int {
	return xxx_messageInfo_AssetContextConfiguration.Size(m)
}
func (m *AssetContextConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetContextConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_AssetContextConfiguration proto.InternalMessageInfo

func (m *AssetContextConfiguration) GetUsePlayerContextIfAuthoritative() bool {
	if m != nil {
		return m.UsePlayerContextIfAuthoritative
	}
	return false
}

type BoundedTagsStreamingQuery struct {
	Radius               float64  `protobuf:"fixed64,1,opt,name=radius,proto3" json:"radius,omitempty"`
	Tag                  []string `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoundedTagsStreamingQuery) Reset()         { *m = BoundedTagsStreamingQuery{} }
func (m *BoundedTagsStreamingQuery) String() string { return proto.CompactTextString(m) }
func (*BoundedTagsStreamingQuery) ProtoMessage()    {}
func (*BoundedTagsStreamingQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{5}
}

func (m *BoundedTagsStreamingQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoundedTagsStreamingQuery.Unmarshal(m, b)
}
func (m *BoundedTagsStreamingQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoundedTagsStreamingQuery.Marshal(b, m, deterministic)
}
func (m *BoundedTagsStreamingQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoundedTagsStreamingQuery.Merge(m, src)
}
func (m *BoundedTagsStreamingQuery) XXX_Size() int {
	return xxx_messageInfo_BoundedTagsStreamingQuery.Size(m)
}
func (m *BoundedTagsStreamingQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BoundedTagsStreamingQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BoundedTagsStreamingQuery proto.InternalMessageInfo

func (m *BoundedTagsStreamingQuery) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *BoundedTagsStreamingQuery) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type GlobalTagStreamingQuery struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalTagStreamingQuery) Reset()         { *m = GlobalTagStreamingQuery{} }
func (m *GlobalTagStreamingQuery) String() string { return proto.CompactTextString(m) }
func (*GlobalTagStreamingQuery) ProtoMessage()    {}
func (*GlobalTagStreamingQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{6}
}

func (m *GlobalTagStreamingQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalTagStreamingQuery.Unmarshal(m, b)
}
func (m *GlobalTagStreamingQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalTagStreamingQuery.Marshal(b, m, deterministic)
}
func (m *GlobalTagStreamingQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalTagStreamingQuery.Merge(m, src)
}
func (m *GlobalTagStreamingQuery) XXX_Size() int {
	return xxx_messageInfo_GlobalTagStreamingQuery.Size(m)
}
func (m *GlobalTagStreamingQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalTagStreamingQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalTagStreamingQuery proto.InternalMessageInfo

func (m *GlobalTagStreamingQuery) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type GlobalComponentStreamingQuery struct {
	ComponentName        string   `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalComponentStreamingQuery) Reset()         { *m = GlobalComponentStreamingQuery{} }
func (m *GlobalComponentStreamingQuery) String() string { return proto.CompactTextString(m) }
func (*GlobalComponentStreamingQuery) ProtoMessage()    {}
func (*GlobalComponentStreamingQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{7}
}

func (m *GlobalComponentStreamingQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalComponentStreamingQuery.Unmarshal(m, b)
}
func (m *GlobalComponentStreamingQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalComponentStreamingQuery.Marshal(b, m, deterministic)
}
func (m *GlobalComponentStreamingQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalComponentStreamingQuery.Merge(m, src)
}
func (m *GlobalComponentStreamingQuery) XXX_Size() int {
	return xxx_messageInfo_GlobalComponentStreamingQuery.Size(m)
}
func (m *GlobalComponentStreamingQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalComponentStreamingQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalComponentStreamingQuery proto.InternalMessageInfo

func (m *GlobalComponentStreamingQuery) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

type BoundedComponentStreamingQuery struct {
	ComponentName        string   `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Radius               float64  `protobuf:"fixed64,2,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoundedComponentStreamingQuery) Reset()         { *m = BoundedComponentStreamingQuery{} }
func (m *BoundedComponentStreamingQuery) String() string { return proto.CompactTextString(m) }
func (*BoundedComponentStreamingQuery) ProtoMessage()    {}
func (*BoundedComponentStreamingQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{8}
}

func (m *BoundedComponentStreamingQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoundedComponentStreamingQuery.Unmarshal(m, b)
}
func (m *BoundedComponentStreamingQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoundedComponentStreamingQuery.Marshal(b, m, deterministic)
}
func (m *BoundedComponentStreamingQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoundedComponentStreamingQuery.Merge(m, src)
}
func (m *BoundedComponentStreamingQuery) XXX_Size() int {
	return xxx_messageInfo_BoundedComponentStreamingQuery.Size(m)
}
func (m *BoundedComponentStreamingQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BoundedComponentStreamingQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BoundedComponentStreamingQuery proto.InternalMessageInfo

func (m *BoundedComponentStreamingQuery) GetComponentName() string {
	if m != nil {
		return m.ComponentName
	}
	return ""
}

func (m *BoundedComponentStreamingQuery) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type StreamingQuery struct {
	// Types that are valid to be assigned to StreamingQuery:
	//	*StreamingQuery_BoundedTagsStreamingQuery
	//	*StreamingQuery_GlobalTagStreamingQuery
	//	*StreamingQuery_GlobalComponentStreamingQuery
	//	*StreamingQuery_BoundedComponentStreamingQuery
	StreamingQuery       isStreamingQuery_StreamingQuery `protobuf_oneof:"streaming_query"`
	ComponentsStreamed   *ComponentsSet                  `protobuf:"bytes,5,opt,name=components_streamed,json=componentsStreamed,proto3" json:"components_streamed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *StreamingQuery) Reset()         { *m = StreamingQuery{} }
func (m *StreamingQuery) String() string { return proto.CompactTextString(m) }
func (*StreamingQuery) ProtoMessage()    {}
func (*StreamingQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{9}
}

func (m *StreamingQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingQuery.Unmarshal(m, b)
}
func (m *StreamingQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingQuery.Marshal(b, m, deterministic)
}
func (m *StreamingQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingQuery.Merge(m, src)
}
func (m *StreamingQuery) XXX_Size() int {
	return xxx_messageInfo_StreamingQuery.Size(m)
}
func (m *StreamingQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingQuery.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingQuery proto.InternalMessageInfo

type isStreamingQuery_StreamingQuery interface {
	isStreamingQuery_StreamingQuery()
}

type StreamingQuery_BoundedTagsStreamingQuery struct {
	BoundedTagsStreamingQuery *BoundedTagsStreamingQuery `protobuf:"bytes,1,opt,name=bounded_tags_streaming_query,json=boundedTagsStreamingQuery,proto3,oneof"`
}

type StreamingQuery_GlobalTagStreamingQuery struct {
	GlobalTagStreamingQuery *GlobalTagStreamingQuery `protobuf:"bytes,2,opt,name=global_tag_streaming_query,json=globalTagStreamingQuery,proto3,oneof"`
}

type StreamingQuery_GlobalComponentStreamingQuery struct {
	GlobalComponentStreamingQuery *GlobalComponentStreamingQuery `protobuf:"bytes,3,opt,name=global_component_streaming_query,json=globalComponentStreamingQuery,proto3,oneof"`
}

type StreamingQuery_BoundedComponentStreamingQuery struct {
	BoundedComponentStreamingQuery *BoundedComponentStreamingQuery `protobuf:"bytes,4,opt,name=bounded_component_streaming_query,json=boundedComponentStreamingQuery,proto3,oneof"`
}

func (*StreamingQuery_BoundedTagsStreamingQuery) isStreamingQuery_StreamingQuery() {}

func (*StreamingQuery_GlobalTagStreamingQuery) isStreamingQuery_StreamingQuery() {}

func (*StreamingQuery_GlobalComponentStreamingQuery) isStreamingQuery_StreamingQuery() {}

func (*StreamingQuery_BoundedComponentStreamingQuery) isStreamingQuery_StreamingQuery() {}

func (m *StreamingQuery) GetStreamingQuery() isStreamingQuery_StreamingQuery {
	if m != nil {
		return m.StreamingQuery
	}
	return nil
}

func (m *StreamingQuery) GetBoundedTagsStreamingQuery() *BoundedTagsStreamingQuery {
	if x, ok := m.GetStreamingQuery().(*StreamingQuery_BoundedTagsStreamingQuery); ok {
		return x.BoundedTagsStreamingQuery
	}
	return nil
}

func (m *StreamingQuery) GetGlobalTagStreamingQuery() *GlobalTagStreamingQuery {
	if x, ok := m.GetStreamingQuery().(*StreamingQuery_GlobalTagStreamingQuery); ok {
		return x.GlobalTagStreamingQuery
	}
	return nil
}

func (m *StreamingQuery) GetGlobalComponentStreamingQuery() *GlobalComponentStreamingQuery {
	if x, ok := m.GetStreamingQuery().(*StreamingQuery_GlobalComponentStreamingQuery); ok {
		return x.GlobalComponentStreamingQuery
	}
	return nil
}

func (m *StreamingQuery) GetBoundedComponentStreamingQuery() *BoundedComponentStreamingQuery {
	if x, ok := m.GetStreamingQuery().(*StreamingQuery_BoundedComponentStreamingQuery); ok {
		return x.BoundedComponentStreamingQuery
	}
	return nil
}

func (m *StreamingQuery) GetComponentsStreamed() *ComponentsSet {
	if m != nil {
		return m.ComponentsStreamed
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamingQuery) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamingQuery_BoundedTagsStreamingQuery)(nil),
		(*StreamingQuery_GlobalTagStreamingQuery)(nil),
		(*StreamingQuery_GlobalComponentStreamingQuery)(nil),
		(*StreamingQuery_BoundedComponentStreamingQuery)(nil),
	}
}

type ComponentsSet struct {
	// Types that are valid to be assigned to ComponentSet:
	//	*ComponentsSet_AllComponents
	//	*ComponentsSet_SpecificComponents
	ComponentSet         isComponentsSet_ComponentSet `protobuf_oneof:"component_set"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ComponentsSet) Reset()         { *m = ComponentsSet{} }
func (m *ComponentsSet) String() string { return proto.CompactTextString(m) }
func (*ComponentsSet) ProtoMessage()    {}
func (*ComponentsSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{10}
}

func (m *ComponentsSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentsSet.Unmarshal(m, b)
}
func (m *ComponentsSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentsSet.Marshal(b, m, deterministic)
}
func (m *ComponentsSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentsSet.Merge(m, src)
}
func (m *ComponentsSet) XXX_Size() int {
	return xxx_messageInfo_ComponentsSet.Size(m)
}
func (m *ComponentsSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentsSet.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentsSet proto.InternalMessageInfo

type isComponentsSet_ComponentSet interface {
	isComponentsSet_ComponentSet()
}

type ComponentsSet_AllComponents struct {
	AllComponents *AllComponents `protobuf:"bytes,1,opt,name=all_components,json=allComponents,proto3,oneof"`
}

type ComponentsSet_SpecificComponents struct {
	SpecificComponents *SpecificComponents `protobuf:"bytes,2,opt,name=specific_components,json=specificComponents,proto3,oneof"`
}

func (*ComponentsSet_AllComponents) isComponentsSet_ComponentSet() {}

func (*ComponentsSet_SpecificComponents) isComponentsSet_ComponentSet() {}

func (m *ComponentsSet) GetComponentSet() isComponentsSet_ComponentSet {
	if m != nil {
		return m.ComponentSet
	}
	return nil
}

func (m *ComponentsSet) GetAllComponents() *AllComponents {
	if x, ok := m.GetComponentSet().(*ComponentsSet_AllComponents); ok {
		return x.AllComponents
	}
	return nil
}

func (m *ComponentsSet) GetSpecificComponents() *SpecificComponents {
	if x, ok := m.GetComponentSet().(*ComponentsSet_SpecificComponents); ok {
		return x.SpecificComponents
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ComponentsSet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ComponentsSet_AllComponents)(nil),
		(*ComponentsSet_SpecificComponents)(nil),
	}
}

type AllComponents struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllComponents) Reset()         { *m = AllComponents{} }
func (m *AllComponents) String() string { return proto.CompactTextString(m) }
func (*AllComponents) ProtoMessage()    {}
func (*AllComponents) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{11}
}

func (m *AllComponents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllComponents.Unmarshal(m, b)
}
func (m *AllComponents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllComponents.Marshal(b, m, deterministic)
}
func (m *AllComponents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllComponents.Merge(m, src)
}
func (m *AllComponents) XXX_Size() int {
	return xxx_messageInfo_AllComponents.Size(m)
}
func (m *AllComponents) XXX_DiscardUnknown() {
	xxx_messageInfo_AllComponents.DiscardUnknown(m)
}

var xxx_messageInfo_AllComponents proto.InternalMessageInfo

type SpecificComponents struct {
	Components           []string `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpecificComponents) Reset()         { *m = SpecificComponents{} }
func (m *SpecificComponents) String() string { return proto.CompactTextString(m) }
func (*SpecificComponents) ProtoMessage()    {}
func (*SpecificComponents) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{12}
}

func (m *SpecificComponents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecificComponents.Unmarshal(m, b)
}
func (m *SpecificComponents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecificComponents.Marshal(b, m, deterministic)
}
func (m *SpecificComponents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecificComponents.Merge(m, src)
}
func (m *SpecificComponents) XXX_Size() int {
	return xxx_messageInfo_SpecificComponents.Size(m)
}
func (m *SpecificComponents) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecificComponents.DiscardUnknown(m)
}

var xxx_messageInfo_SpecificComponents proto.InternalMessageInfo

func (m *SpecificComponents) GetComponents() []string {
	if m != nil {
		return m.Components
	}
	return nil
}

type ComponentEncodingSetting struct {
	Type                 EncodingType `protobuf:"varint,1,opt,name=type,proto3,enum=improbable.platform.assembly.EncodingType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ComponentEncodingSetting) Reset()         { *m = ComponentEncodingSetting{} }
func (m *ComponentEncodingSetting) String() string { return proto.CompactTextString(m) }
func (*ComponentEncodingSetting) ProtoMessage()    {}
func (*ComponentEncodingSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{13}
}

func (m *ComponentEncodingSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentEncodingSetting.Unmarshal(m, b)
}
func (m *ComponentEncodingSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentEncodingSetting.Marshal(b, m, deterministic)
}
func (m *ComponentEncodingSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentEncodingSetting.Merge(m, src)
}
func (m *ComponentEncodingSetting) XXX_Size() int {
	return xxx_messageInfo_ComponentEncodingSetting.Size(m)
}
func (m *ComponentEncodingSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentEncodingSetting.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentEncodingSetting proto.InternalMessageInfo

func (m *ComponentEncodingSetting) GetType() EncodingType {
	if m != nil {
		return m.Type
	}
	return EncodingType_BASIC
}

type PerComponentSettings struct {
	// Types that are valid to be assigned to AuthorityHandoverTimeout:
	//	*PerComponentSettings_AuthorityHandoverTimeoutMs
	AuthorityHandoverTimeout isPerComponentSettings_AuthorityHandoverTimeout `protobuf_oneof:"authority_handover_timeout"`
	Encoding                 *ComponentEncodingSetting                       `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                                        `json:"-"`
	XXX_unrecognized         []byte                                          `json:"-"`
	XXX_sizecache            int32                                           `json:"-"`
}

func (m *PerComponentSettings) Reset()         { *m = PerComponentSettings{} }
func (m *PerComponentSettings) String() string { return proto.CompactTextString(m) }
func (*PerComponentSettings) ProtoMessage()    {}
func (*PerComponentSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{14}
}

func (m *PerComponentSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerComponentSettings.Unmarshal(m, b)
}
func (m *PerComponentSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerComponentSettings.Marshal(b, m, deterministic)
}
func (m *PerComponentSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerComponentSettings.Merge(m, src)
}
func (m *PerComponentSettings) XXX_Size() int {
	return xxx_messageInfo_PerComponentSettings.Size(m)
}
func (m *PerComponentSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_PerComponentSettings.DiscardUnknown(m)
}

var xxx_messageInfo_PerComponentSettings proto.InternalMessageInfo

type isPerComponentSettings_AuthorityHandoverTimeout interface {
	isPerComponentSettings_AuthorityHandoverTimeout()
}

type PerComponentSettings_AuthorityHandoverTimeoutMs struct {
	AuthorityHandoverTimeoutMs uint32 `protobuf:"varint,1,opt,name=authority_handover_timeout_ms,json=authorityHandoverTimeoutMs,proto3,oneof"`
}

func (*PerComponentSettings_AuthorityHandoverTimeoutMs) isPerComponentSettings_AuthorityHandoverTimeout() {
}

func (m *PerComponentSettings) GetAuthorityHandoverTimeout() isPerComponentSettings_AuthorityHandoverTimeout {
	if m != nil {
		return m.AuthorityHandoverTimeout
	}
	return nil
}

func (m *PerComponentSettings) GetAuthorityHandoverTimeoutMs() uint32 {
	if x, ok := m.GetAuthorityHandoverTimeout().(*PerComponentSettings_AuthorityHandoverTimeoutMs); ok {
		return x.AuthorityHandoverTimeoutMs
	}
	return 0
}

func (m *PerComponentSettings) GetEncoding() *ComponentEncodingSetting {
	if m != nil {
		return m.Encoding
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PerComponentSettings) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PerComponentSettings_AuthorityHandoverTimeoutMs)(nil),
	}
}

type ComponentsSettings struct {
	Default              *PerComponentSettings            `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	PerComponentSettings map[string]*PerComponentSettings `protobuf:"bytes,2,rep,name=per_component_settings,json=perComponentSettings,proto3" json:"per_component_settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ComponentsSettings) Reset()         { *m = ComponentsSettings{} }
func (m *ComponentsSettings) String() string { return proto.CompactTextString(m) }
func (*ComponentsSettings) ProtoMessage()    {}
func (*ComponentsSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{15}
}

func (m *ComponentsSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentsSettings.Unmarshal(m, b)
}
func (m *ComponentsSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentsSettings.Marshal(b, m, deterministic)
}
func (m *ComponentsSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentsSettings.Merge(m, src)
}
func (m *ComponentsSettings) XXX_Size() int {
	return xxx_messageInfo_ComponentsSettings.Size(m)
}
func (m *ComponentsSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentsSettings.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentsSettings proto.InternalMessageInfo

func (m *ComponentsSettings) GetDefault() *PerComponentSettings {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *ComponentsSettings) GetPerComponentSettings() map[string]*PerComponentSettings {
	if m != nil {
		return m.PerComponentSettings
	}
	return nil
}

type BridgeConfiguration struct {
	WorkerAttributeSet   *runtime.WorkerAttributeSet        `protobuf:"bytes,2,opt,name=worker_attribute_set,json=workerAttributeSet,proto3" json:"worker_attribute_set,omitempty"`
	EntityInterest       *EntityInterest                    `protobuf:"bytes,3,opt,name=entity_interest,json=entityInterest,proto3" json:"entity_interest,omitempty"`
	StreamingQuery       []*StreamingQuery                  `protobuf:"bytes,4,rep,name=streaming_query,json=streamingQuery,proto3" json:"streaming_query,omitempty"`
	Loadbalancing        *runtime.WorkerLoadbalancingConfig `protobuf:"bytes,5,opt,name=loadbalancing,proto3" json:"loadbalancing,omitempty"`
	ComponentDelivery    *ComponentDeliveryConfiguration    `protobuf:"bytes,6,opt,name=component_delivery,json=componentDelivery,proto3" json:"component_delivery,omitempty"`
	Permission           []*runtime.WorkerPermission        `protobuf:"bytes,7,rep,name=permission,proto3" json:"permission,omitempty"`
	ComponentSettings    *ComponentsSettings                `protobuf:"bytes,8,opt,name=component_settings,json=componentSettings,proto3" json:"component_settings,omitempty"`
	AssetContext         *AssetContextConfiguration         `protobuf:"bytes,1000,opt,name=asset_context,json=assetContext,proto3" json:"asset_context,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *BridgeConfiguration) Reset()         { *m = BridgeConfiguration{} }
func (m *BridgeConfiguration) String() string { return proto.CompactTextString(m) }
func (*BridgeConfiguration) ProtoMessage()    {}
func (*BridgeConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_27987b65ee8403f8, []int{16}
}

func (m *BridgeConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeConfiguration.Unmarshal(m, b)
}
func (m *BridgeConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeConfiguration.Marshal(b, m, deterministic)
}
func (m *BridgeConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeConfiguration.Merge(m, src)
}
func (m *BridgeConfiguration) XXX_Size() int {
	return xxx_messageInfo_BridgeConfiguration.Size(m)
}
func (m *BridgeConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeConfiguration proto.InternalMessageInfo

func (m *BridgeConfiguration) GetWorkerAttributeSet() *runtime.WorkerAttributeSet {
	if m != nil {
		return m.WorkerAttributeSet
	}
	return nil
}

func (m *BridgeConfiguration) GetEntityInterest() *EntityInterest {
	if m != nil {
		return m.EntityInterest
	}
	return nil
}

func (m *BridgeConfiguration) GetStreamingQuery() []*StreamingQuery {
	if m != nil {
		return m.StreamingQuery
	}
	return nil
}

func (m *BridgeConfiguration) GetLoadbalancing() *runtime.WorkerLoadbalancingConfig {
	if m != nil {
		return m.Loadbalancing
	}
	return nil
}

func (m *BridgeConfiguration) GetComponentDelivery() *ComponentDeliveryConfiguration {
	if m != nil {
		return m.ComponentDelivery
	}
	return nil
}

func (m *BridgeConfiguration) GetPermission() []*runtime.WorkerPermission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *BridgeConfiguration) GetComponentSettings() *ComponentsSettings {
	if m != nil {
		return m.ComponentSettings
	}
	return nil
}

// Deprecated: Do not use.
func (m *BridgeConfiguration) GetAssetContext() *AssetContextConfiguration {
	if m != nil {
		return m.AssetContext
	}
	return nil
}

func init() {
	proto.RegisterEnum("improbable.platform.assembly.MessageDelivery", MessageDelivery_name, MessageDelivery_value)
	proto.RegisterEnum("improbable.platform.assembly.EncodingType", EncodingType_name, EncodingType_value)
	proto.RegisterType((*RangeEntityInterest)(nil), "improbable.platform.assembly.RangeEntityInterest")
	proto.RegisterType((*EntityInterest)(nil), "improbable.platform.assembly.EntityInterest")
	proto.RegisterType((*ComponentDelivery)(nil), "improbable.platform.assembly.ComponentDelivery")
	proto.RegisterType((*ComponentDeliveryConfiguration)(nil), "improbable.platform.assembly.ComponentDeliveryConfiguration")
	proto.RegisterMapType((map[string]*ComponentDelivery)(nil), "improbable.platform.assembly.ComponentDeliveryConfiguration.OverrideEntry")
	proto.RegisterType((*AssetContextConfiguration)(nil), "improbable.platform.assembly.AssetContextConfiguration")
	proto.RegisterType((*BoundedTagsStreamingQuery)(nil), "improbable.platform.assembly.BoundedTagsStreamingQuery")
	proto.RegisterType((*GlobalTagStreamingQuery)(nil), "improbable.platform.assembly.GlobalTagStreamingQuery")
	proto.RegisterType((*GlobalComponentStreamingQuery)(nil), "improbable.platform.assembly.GlobalComponentStreamingQuery")
	proto.RegisterType((*BoundedComponentStreamingQuery)(nil), "improbable.platform.assembly.BoundedComponentStreamingQuery")
	proto.RegisterType((*StreamingQuery)(nil), "improbable.platform.assembly.StreamingQuery")
	proto.RegisterType((*ComponentsSet)(nil), "improbable.platform.assembly.ComponentsSet")
	proto.RegisterType((*AllComponents)(nil), "improbable.platform.assembly.AllComponents")
	proto.RegisterType((*SpecificComponents)(nil), "improbable.platform.assembly.SpecificComponents")
	proto.RegisterType((*ComponentEncodingSetting)(nil), "improbable.platform.assembly.ComponentEncodingSetting")
	proto.RegisterType((*PerComponentSettings)(nil), "improbable.platform.assembly.PerComponentSettings")
	proto.RegisterType((*ComponentsSettings)(nil), "improbable.platform.assembly.ComponentsSettings")
	proto.RegisterMapType((map[string]*PerComponentSettings)(nil), "improbable.platform.assembly.ComponentsSettings.PerComponentSettingsEntry")
	proto.RegisterType((*BridgeConfiguration)(nil), "improbable.platform.assembly.BridgeConfiguration")
}

func init() {
	proto.RegisterFile("improbable/platform/assembly/bridge_config.proto", fileDescriptor_27987b65ee8403f8)
}

var fileDescriptor_27987b65ee8403f8 = []byte{
	// 1277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0xda, 0x49, 0x9a, 0x9e, 0xd4, 0x8e, 0x33, 0x09, 0xe9, 0xc6, 0x4d, 0xd3, 0xb0, 0x08,
	0xa9, 0x6a, 0x89, 0x53, 0x4c, 0x0b, 0x08, 0x10, 0xc8, 0x76, 0x96, 0xda, 0x95, 0x73, 0xe9, 0xd8,
	0x16, 0x17, 0x21, 0xad, 0xc6, 0xf6, 0x78, 0x33, 0xca, 0x5e, 0xcc, 0xee, 0x6c, 0x8a, 0xe1, 0x85,
	0x27, 0x04, 0x88, 0x9f, 0xc0, 0x5f, 0xe2, 0x17, 0xf0, 0xc6, 0x13, 0x7f, 0x80, 0x77, 0xb4, 0x57,
	0xef, 0xfa, 0xb2, 0x71, 0xe1, 0xcd, 0x9e, 0x39, 0xdf, 0x77, 0xae, 0x73, 0xce, 0x59, 0x78, 0xc2,
	0xf4, 0x91, 0x65, 0xf6, 0x48, 0x4f, 0xa3, 0xc7, 0x23, 0x8d, 0xf0, 0xa1, 0x69, 0xe9, 0xc7, 0xc4,
	0xb6, 0xa9, 0xde, 0xd3, 0xc6, 0xc7, 0x3d, 0x8b, 0x0d, 0x54, 0xaa, 0xf4, 0x4d, 0x63, 0xc8, 0xd4,
	0xf2, 0xc8, 0x32, 0xb9, 0x89, 0xf6, 0x27, 0x88, 0x72, 0x88, 0x28, 0x87, 0x88, 0xd2, 0xb3, 0x79,
	0x7c, 0x96, 0x63, 0x70, 0xa6, 0xd3, 0x63, 0xcd, 0x24, 0x83, 0x1e, 0xd1, 0x88, 0xd1, 0xa7, 0x56,
	0x82, 0xb4, 0x54, 0x49, 0x83, 0xbd, 0x32, 0xad, 0x2b, 0x6a, 0x29, 0x84, 0x73, 0x8b, 0xf5, 0x1c,
	0x4e, 0x03, 0xcc, 0xd3, 0x25, 0x30, 0x23, 0x6a, 0xe9, 0xcc, 0xb6, 0x99, 0x69, 0xd8, 0x3e, 0x4a,
	0x3a, 0x82, 0x6d, 0x4c, 0x0c, 0x95, 0xca, 0x06, 0x67, 0x7c, 0xdc, 0x34, 0x38, 0xb5, 0xa8, 0xcd,
	0xd1, 0x2e, 0xac, 0x59, 0x64, 0xc0, 0x1c, 0x5b, 0x14, 0x0e, 0x85, 0x87, 0x02, 0x0e, 0xfe, 0x49,
	0xbf, 0x09, 0x50, 0x98, 0x12, 0x55, 0xe1, 0x0d, 0xcb, 0x65, 0x50, 0xa8, 0x77, 0xae, 0xb0, 0xe0,
	0xc2, 0x43, 0x6e, 0x54, 0xde, 0x2d, 0xa7, 0x05, 0xa8, 0x3c, 0x47, 0x79, 0x23, 0x83, 0xb7, 0xad,
	0xd9, 0xe3, 0xda, 0x16, 0x6c, 0x4e, 0xa9, 0x90, 0x7e, 0x17, 0x60, 0xab, 0x6e, 0xea, 0x23, 0xd3,
	0xa0, 0x06, 0x3f, 0xa1, 0x1a, 0xbb, 0xa6, 0xd6, 0x18, 0x1d, 0x01, 0xea, 0x5f, 0xd2, 0xfe, 0x95,
	0xe9, 0x70, 0x85, 0x19, 0x8c, 0x33, 0xa2, 0x69, 0x63, 0xcf, 0x9c, 0x75, 0xbc, 0x15, 0xde, 0x34,
	0xc3, 0x0b, 0xf4, 0x25, 0x14, 0x75, 0x6a, 0xdb, 0x44, 0xa5, 0xca, 0x20, 0xa0, 0x10, 0xb3, 0x87,
	0xc2, 0xc3, 0x42, 0xe5, 0x28, 0xdd, 0xf6, 0x53, 0x1f, 0x15, 0xea, 0xc5, 0x9b, 0x7a, 0xf2, 0x40,
	0xfa, 0x27, 0x0b, 0x07, 0x33, 0xe6, 0xd5, 0xbd, 0x44, 0x3b, 0x16, 0xe1, 0xcc, 0x34, 0xd0, 0x73,
	0xb8, 0x35, 0xa0, 0x43, 0xe2, 0x68, 0x7e, 0xbc, 0x5e, 0x5b, 0x67, 0x88, 0x46, 0x4f, 0x61, 0x37,
	0x72, 0x9a, 0x68, 0x5a, 0xcc, 0xf1, 0xac, 0xe7, 0xf8, 0x4e, 0x78, 0x5b, 0xd5, 0xb4, 0x89, 0xef,
	0x43, 0x58, 0x37, 0xaf, 0xa9, 0x65, 0xb1, 0x01, 0x15, 0x73, 0x87, 0xb9, 0x87, 0x1b, 0x95, 0x17,
	0xe9, 0xfa, 0xd3, 0xdd, 0x29, 0x9f, 0x07, 0x64, 0xb2, 0xc1, 0xad, 0x31, 0x8e, 0xb8, 0x4b, 0x1a,
	0xe4, 0x13, 0x57, 0xa8, 0x08, 0xb9, 0x2b, 0xea, 0x27, 0xe5, 0x36, 0x76, 0x7f, 0x22, 0x19, 0x56,
	0xaf, 0x89, 0xe6, 0x50, 0xcf, 0xde, 0x8d, 0xca, 0xf1, 0x6b, 0xda, 0x81, 0x7d, 0xf4, 0x47, 0xd9,
	0x0f, 0x05, 0x89, 0xc1, 0x5e, 0xd5, 0xb6, 0x29, 0xaf, 0x9b, 0x06, 0xa7, 0xdf, 0xf1, 0x64, 0xc4,
	0x5b, 0xf0, 0x96, 0x63, 0x53, 0x65, 0xa4, 0x91, 0xb1, 0xff, 0xec, 0x5c, 0x11, 0x85, 0x0d, 0x15,
	0xe2, 0xf0, 0x4b, 0xd3, 0x62, 0x9c, 0x70, 0x76, 0x4d, 0x83, 0x72, 0x79, 0xe0, 0xd8, 0xf4, 0xc2,
	0x93, 0x0c, 0xb8, 0x9a, 0xc3, 0x6a, 0x5c, 0x4c, 0x92, 0x61, 0xaf, 0x66, 0x3a, 0xc6, 0x80, 0x0e,
	0x3a, 0x44, 0xb5, 0xdb, 0xdc, 0xa2, 0x44, 0x67, 0x86, 0xfa, 0xd2, 0x71, 0x0b, 0x71, 0xc1, 0x2b,
	0x72, 0x9d, 0xe7, 0x44, 0x15, 0xb3, 0x87, 0x39, 0xd7, 0x79, 0x4e, 0x54, 0xe9, 0x31, 0xdc, 0x7d,
	0xae, 0x99, 0x3d, 0xa2, 0x75, 0x88, 0x3a, 0x45, 0x12, 0x08, 0x07, 0x91, 0x72, 0x85, 0x3f, 0x87,
	0xfb, 0xbe, 0x70, 0x14, 0x84, 0x29, 0xc8, 0xdb, 0x50, 0xe8, 0x87, 0x57, 0x8a, 0x41, 0x74, 0x1a,
	0xa0, 0xf3, 0xd1, 0xe9, 0x19, 0xd1, 0xa9, 0xa4, 0xc0, 0x41, 0x60, 0xfb, 0xff, 0x23, 0x8a, 0xf9,
	0x99, 0x4d, 0x74, 0x8b, 0x9f, 0x57, 0xa1, 0x30, 0xc5, 0xf8, 0x3d, 0xec, 0xf7, 0x7c, 0x9d, 0x0a,
	0x27, 0xaa, 0xad, 0xd8, 0xe1, 0xb5, 0xf2, 0xad, 0x7b, 0x1f, 0x34, 0x8d, 0x0f, 0xd2, 0x93, 0xbf,
	0x30, 0xe2, 0x8d, 0x0c, 0xde, 0xeb, 0x2d, 0x4c, 0x07, 0x87, 0x92, 0xea, 0xc5, 0xcd, 0x55, 0x3d,
	0xa3, 0xd9, 0x2f, 0xbb, 0x67, 0xe9, 0x9a, 0x17, 0x24, 0xa9, 0x91, 0xc1, 0x77, 0xd5, 0x05, 0xf9,
	0xfb, 0x49, 0x80, 0xc3, 0x40, 0xed, 0x24, 0x96, 0xd3, 0xca, 0x73, 0x9e, 0xf2, 0x8f, 0x97, 0x51,
	0xbe, 0x20, 0x57, 0x8d, 0x0c, 0xbe, 0xaf, 0xa6, 0x56, 0xc5, 0x2f, 0x02, 0xbc, 0x19, 0xc6, 0x7e,
	0xb1, 0x25, 0x2b, 0x9e, 0x25, 0x9f, 0x2c, 0x95, 0x80, 0xc5, 0xa6, 0x1c, 0xf4, 0xd2, 0x0b, 0xeb,
	0x1b, 0xd8, 0x8e, 0x4c, 0x08, 0x8b, 0x80, 0x0e, 0xc4, 0x55, 0x4f, 0xf9, 0xe3, 0x25, 0x9f, 0xbe,
	0xdd, 0xa6, 0x1c, 0xa3, 0x09, 0x4f, 0x3b, 0xa0, 0x71, 0x27, 0xc5, 0x94, 0x5b, 0xd2, 0x9f, 0x02,
	0xe4, 0x13, 0x40, 0xd4, 0x81, 0x82, 0xdb, 0x27, 0x27, 0xf0, 0xa0, 0xf6, 0x6e, 0xd0, 0x5e, 0xd5,
	0x26, 0x01, 0xb6, 0x1b, 0x19, 0x9c, 0x27, 0xf1, 0x03, 0xd4, 0x87, 0x6d, 0x7b, 0x44, 0xfb, 0x6c,
	0xc8, 0xfa, 0x71, 0x6a, 0xbf, 0xb8, 0x9e, 0xa4, 0x53, 0xb7, 0x03, 0x60, 0x82, 0x1f, 0xd9, 0x33,
	0xa7, 0xb5, 0x4d, 0xc8, 0xc7, 0x12, 0x48, 0xb9, 0xb4, 0x09, 0xf9, 0x84, 0x5d, 0xd2, 0x53, 0x40,
	0xb3, 0x6c, 0xe8, 0x00, 0x20, 0xe1, 0xae, 0xdb, 0x7e, 0x62, 0x27, 0xd2, 0xd7, 0x20, 0x46, 0xd2,
	0xb2, 0xd1, 0x37, 0x07, 0xcc, 0x50, 0xdb, 0x94, 0x73, 0x66, 0xa8, 0xe8, 0x53, 0x58, 0xe1, 0xe3,
	0x11, 0x0d, 0xa6, 0xd4, 0xa3, 0x74, 0x4f, 0x42, 0x70, 0x67, 0x3c, 0xa2, 0xd8, 0xc3, 0x49, 0x7f,
	0x08, 0xb0, 0x73, 0xe1, 0xb6, 0xd1, 0xb0, 0x20, 0x7c, 0x5e, 0x1b, 0xd5, 0xe1, 0x7e, 0xd8, 0x79,
	0xc7, 0xca, 0x25, 0x31, 0x06, 0xee, 0xd0, 0x50, 0xdc, 0xad, 0xc5, 0x1d, 0x65, 0xba, 0x9f, 0x96,
	0x7c, 0x23, 0x83, 0x4b, 0x91, 0x58, 0x23, 0x90, 0xea, 0xf8, 0x42, 0xa7, 0x36, 0xc2, 0xb0, 0x4e,
	0x03, 0x9d, 0x41, 0xac, 0xdf, 0x5f, 0xb2, 0x88, 0xa6, 0xfc, 0xc4, 0x11, 0x4f, 0x6d, 0x1f, 0x4a,
	0x8b, 0x0d, 0x93, 0xfe, 0xca, 0x02, 0x4a, 0x14, 0x94, 0xef, 0x4d, 0x2b, 0x39, 0xcf, 0x37, 0x2a,
	0x95, 0x74, 0x3b, 0xe6, 0x85, 0x64, 0x32, 0xd4, 0x7f, 0x14, 0x60, 0x77, 0xe4, 0x4d, 0xa9, 0x58,
	0xb6, 0x3d, 0x19, 0x6f, 0x78, 0x2c, 0x3f, 0xad, 0x23, 0x03, 0xe7, 0x2a, 0xf4, 0xa7, 0xf5, 0xce,
	0x68, 0xce, 0x55, 0xe9, 0x07, 0xd8, 0x5b, 0x08, 0x99, 0x33, 0xc5, 0x1b, 0xc9, 0x29, 0xfe, 0x5f,
	0xbc, 0x8f, 0x0d, 0xf2, 0x5f, 0xd7, 0x60, 0xbb, 0xe6, 0x2d, 0xdd, 0xc9, 0x19, 0x4e, 0x60, 0x67,
	0x7a, 0x0b, 0x76, 0x23, 0x93, 0xba, 0x3a, 0x04, 0xab, 0x70, 0xf9, 0x0b, 0x0f, 0x58, 0x0d, 0x71,
	0x5e, 0x0f, 0x79, 0x35, 0x73, 0x86, 0xba, 0x33, 0xdb, 0x66, 0xd0, 0xa4, 0xdf, 0xb9, 0xa9, 0xf4,
	0xe3, 0x4b, 0x2b, 0x2e, 0xd0, 0xe4, 0xb6, 0xdc, 0x9d, 0x69, 0x4d, 0xe2, 0x8a, 0x97, 0xc9, 0x1b,
	0x68, 0x93, 0xfd, 0x13, 0x17, 0xec, 0xe9, 0x7e, 0x9a, 0x9f, 0x7c, 0x4d, 0xb8, 0x8f, 0x60, 0x35,
	0xe5, 0x11, 0x24, 0x23, 0xd1, 0x8a, 0xe3, 0xfc, 0x30, 0xe3, 0x24, 0x19, 0xba, 0x82, 0x49, 0x97,
	0x9d, 0xec, 0xc8, 0x6b, 0xcb, 0x4c, 0x8a, 0xf4, 0x7d, 0x11, 0x6f, 0xf5, 0x67, 0xb6, 0xf7, 0x53,
	0x80, 0xc9, 0x67, 0x8a, 0x78, 0xcb, 0x0b, 0xce, 0xd1, 0x12, 0x7e, 0x5c, 0x44, 0x20, 0x1c, 0x23,
	0x40, 0x4a, 0xdc, 0xf6, 0xe8, 0xf5, 0xac, 0x2f, 0xd3, 0x8f, 0x67, 0x5f, 0x4f, 0xcc, 0xde, 0xe8,
	0xc5, 0x13, 0xc8, 0xbb, 0x08, 0x1e, 0xae, 0x92, 0xe2, 0xdf, 0xb7, 0x96, 0xd9, 0x61, 0x16, 0x2e,
	0xa8, 0xb5, 0xac, 0x28, 0xe0, 0x3b, 0x24, 0x76, 0xfd, 0x62, 0x65, 0x5d, 0x28, 0x66, 0x1f, 0x7d,
	0x06, 0x9b, 0x53, 0xdb, 0x3f, 0xda, 0x81, 0x22, 0x96, 0x5b, 0xcd, 0x6a, 0xad, 0x25, 0x2b, 0xe7,
	0xf8, 0x44, 0xc6, 0xf2, 0x49, 0x31, 0x83, 0x76, 0x01, 0x75, 0xcf, 0x66, 0xce, 0x85, 0x47, 0x0e,
	0xdc, 0x89, 0x37, 0x66, 0x74, 0x1b, 0x56, 0x6b, 0xd5, 0x76, 0xb3, 0x5e, 0xcc, 0xa0, 0x7d, 0x10,
	0x6b, 0xcd, 0xb3, 0x2a, 0xfe, 0x4a, 0x39, 0x91, 0x5b, 0x9d, 0xaa, 0x52, 0x3f, 0x3f, 0xbd, 0xc0,
	0x72, 0xbb, 0xdd, 0x3c, 0x3f, 0x2b, 0x0a, 0xe8, 0x1e, 0xdc, 0x7d, 0xd9, 0x95, 0xbb, 0xf2, 0x9c,
	0xcb, 0x2c, 0x7a, 0x00, 0xf7, 0x1a, 0x72, 0x17, 0x37, 0xdb, 0x9d, 0x66, 0x7d, 0x8e, 0x40, 0xae,
	0x56, 0xaa, 0x89, 0x73, 0xde, 0xf0, 0x85, 0xfb, 0xf9, 0xd9, 0x5b, 0xf3, 0xbe, 0x42, 0xdf, 0xfb,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x38, 0x4b, 0xfa, 0xdf, 0x78, 0x0f, 0x00, 0x00,
}
