// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/int/platform/intauthservice/authservice.proto

package improbable_int_platform_intauthservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AddUserRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddUserRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddUserResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddUserResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteUserRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteUserRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteUserResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteUserResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetUsersRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetUsersRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetUsersResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetUsersResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddGroupRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddGroupRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddGroupResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddGroupResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteGroupRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteGroupRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteGroupResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteGroupResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupsRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupsRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupsResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupsResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddUserToGroupRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddUserToGroupRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddUserToGroupResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddUserToGroupResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *RemoveUserFromGroupRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *RemoveUserFromGroupRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *RemoveUserFromGroupResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *RemoveUserFromGroupResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupMembersRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupMembersRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupMembersResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupMembersResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupsWithUserRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupsWithUserRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupsWithUserResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupsWithUserResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddUserPermissionRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddUserPermissionRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddUserPermissionResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddUserPermissionResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *UpdateUserPermissionRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *UpdateUserPermissionRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *UpdateUserPermissionResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *UpdateUserPermissionResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteUserPermissionRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteUserPermissionRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteUserPermissionResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteUserPermissionResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetUserPermissionsRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetUserPermissionsRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetUserPermissionsResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetUserPermissionsResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddGroupPermissionRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddGroupPermissionRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *AddGroupPermissionResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *AddGroupPermissionResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *UpdateGroupPermissionRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *UpdateGroupPermissionRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *UpdateGroupPermissionResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *UpdateGroupPermissionResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteGroupPermissionRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteGroupPermissionRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *DeleteGroupPermissionResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *DeleteGroupPermissionResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupPermissionsRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupPermissionsRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetGroupPermissionsResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetGroupPermissionsResponse) ExtractRequestFields(dst map[string]interface{}) {
}
