// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/scrapetargets/config.proto

package improbable_infra_scrapetargets

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScrapeTargets struct {
	Targets              []*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScrapeTargets) Reset()         { *m = ScrapeTargets{} }
func (m *ScrapeTargets) String() string { return proto.CompactTextString(m) }
func (*ScrapeTargets) ProtoMessage()    {}
func (*ScrapeTargets) Descriptor() ([]byte, []int) {
	return fileDescriptor_90b1a993bc4c76cf, []int{0}
}

func (m *ScrapeTargets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScrapeTargets.Unmarshal(m, b)
}
func (m *ScrapeTargets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScrapeTargets.Marshal(b, m, deterministic)
}
func (m *ScrapeTargets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScrapeTargets.Merge(m, src)
}
func (m *ScrapeTargets) XXX_Size() int {
	return xxx_messageInfo_ScrapeTargets.Size(m)
}
func (m *ScrapeTargets) XXX_DiscardUnknown() {
	xxx_messageInfo_ScrapeTargets.DiscardUnknown(m)
}

var xxx_messageInfo_ScrapeTargets proto.InternalMessageInfo

func (m *ScrapeTargets) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Target struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_90b1a993bc4c76cf, []int{1}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*ScrapeTargets)(nil), "improbable.infra.scrapetargets.ScrapeTargets")
	proto.RegisterType((*Target)(nil), "improbable.infra.scrapetargets.Target")
}

func init() {
	proto.RegisterFile("infra/scrapetargets/config.proto", fileDescriptor_90b1a993bc4c76cf)
}

var fileDescriptor_90b1a993bc4c76cf = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0xcc, 0x4b, 0x2b,
	0x4a, 0xd4, 0x2f, 0x4e, 0x2e, 0x4a, 0x2c, 0x48, 0x2d, 0x49, 0x2c, 0x4a, 0x4f, 0x2d, 0x29, 0xd6,
	0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xcb, 0xcc,
	0x2d, 0x28, 0xca, 0x4f, 0x4a, 0x4c, 0xca, 0x49, 0xd5, 0x03, 0x2b, 0xd6, 0x43, 0x51, 0xac, 0x14,
	0xc8, 0xc5, 0x1b, 0x0c, 0x16, 0x08, 0x81, 0x08, 0x08, 0x39, 0x70, 0xb1, 0x43, 0xe5, 0x24, 0x18,
	0x15, 0x98, 0x35, 0xb8, 0x8d, 0xd4, 0xf4, 0xf0, 0x1b, 0xa1, 0x07, 0xd1, 0x19, 0x04, 0xd3, 0xa6,
	0x24, 0xc3, 0xc5, 0x06, 0x11, 0x12, 0x12, 0xe2, 0x62, 0xc9, 0xc8, 0x2f, 0x2e, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xee, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x30, 0x53, 0x15, 0xfd, 0xbb, 0x00, 0x00, 0x00,
}
