// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/spatialos/playerauth/v2/playerauth.proto

package pb_playerauthv2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/improbable-io/go-proto-logfields"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "improbable.io/proto/improbable/ext/plugin/auth"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateLoginTokenRequest struct {
	PlayerIdentityToken  string             `protobuf:"bytes,1,opt,name=player_identity_token,json=playerIdentityToken,proto3" json:"player_identity_token,omitempty"`
	DeploymentId         string             `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	LifetimeDuration     *duration.Duration `protobuf:"bytes,3,opt,name=lifetime_duration,json=lifetimeDuration,proto3" json:"lifetime_duration,omitempty"`
	WorkerType           string             `protobuf:"bytes,4,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateLoginTokenRequest) Reset()         { *m = CreateLoginTokenRequest{} }
func (m *CreateLoginTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLoginTokenRequest) ProtoMessage()    {}
func (*CreateLoginTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{0}
}

func (m *CreateLoginTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLoginTokenRequest.Unmarshal(m, b)
}
func (m *CreateLoginTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLoginTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateLoginTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLoginTokenRequest.Merge(m, src)
}
func (m *CreateLoginTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLoginTokenRequest.Size(m)
}
func (m *CreateLoginTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLoginTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLoginTokenRequest proto.InternalMessageInfo

func (m *CreateLoginTokenRequest) GetPlayerIdentityToken() string {
	if m != nil {
		return m.PlayerIdentityToken
	}
	return ""
}

func (m *CreateLoginTokenRequest) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *CreateLoginTokenRequest) GetLifetimeDuration() *duration.Duration {
	if m != nil {
		return m.LifetimeDuration
	}
	return nil
}

func (m *CreateLoginTokenRequest) GetWorkerType() string {
	if m != nil {
		return m.WorkerType
	}
	return ""
}

type CreateLoginTokenResponse struct {
	LoginToken           string   `protobuf:"bytes,1,opt,name=login_token,json=loginToken,proto3" json:"login_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLoginTokenResponse) Reset()         { *m = CreateLoginTokenResponse{} }
func (m *CreateLoginTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLoginTokenResponse) ProtoMessage()    {}
func (*CreateLoginTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{1}
}

func (m *CreateLoginTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLoginTokenResponse.Unmarshal(m, b)
}
func (m *CreateLoginTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLoginTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreateLoginTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLoginTokenResponse.Merge(m, src)
}
func (m *CreateLoginTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLoginTokenResponse.Size(m)
}
func (m *CreateLoginTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLoginTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLoginTokenResponse proto.InternalMessageInfo

func (m *CreateLoginTokenResponse) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

type CreatePlayerIdentityTokenRequest struct {
	Provider             string             `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	PlayerIdentifier     string             `protobuf:"bytes,2,opt,name=player_identifier,json=playerIdentifier,proto3" json:"player_identifier,omitempty"`
	ProjectName          string             `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	LifetimeDuration     *duration.Duration `protobuf:"bytes,4,opt,name=lifetime_duration,json=lifetimeDuration,proto3" json:"lifetime_duration,omitempty"`
	DisplayName          string             `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Metadata             []byte             `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreatePlayerIdentityTokenRequest) Reset()         { *m = CreatePlayerIdentityTokenRequest{} }
func (m *CreatePlayerIdentityTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerIdentityTokenRequest) ProtoMessage()    {}
func (*CreatePlayerIdentityTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{2}
}

func (m *CreatePlayerIdentityTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerIdentityTokenRequest.Unmarshal(m, b)
}
func (m *CreatePlayerIdentityTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerIdentityTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlayerIdentityTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerIdentityTokenRequest.Merge(m, src)
}
func (m *CreatePlayerIdentityTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerIdentityTokenRequest.Size(m)
}
func (m *CreatePlayerIdentityTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerIdentityTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerIdentityTokenRequest proto.InternalMessageInfo

func (m *CreatePlayerIdentityTokenRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *CreatePlayerIdentityTokenRequest) GetPlayerIdentifier() string {
	if m != nil {
		return m.PlayerIdentifier
	}
	return ""
}

func (m *CreatePlayerIdentityTokenRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *CreatePlayerIdentityTokenRequest) GetLifetimeDuration() *duration.Duration {
	if m != nil {
		return m.LifetimeDuration
	}
	return nil
}

func (m *CreatePlayerIdentityTokenRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CreatePlayerIdentityTokenRequest) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreatePlayerIdentityTokenResponse struct {
	PlayerIdentityToken  string   `protobuf:"bytes,1,opt,name=player_identity_token,json=playerIdentityToken,proto3" json:"player_identity_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayerIdentityTokenResponse) Reset()         { *m = CreatePlayerIdentityTokenResponse{} }
func (m *CreatePlayerIdentityTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerIdentityTokenResponse) ProtoMessage()    {}
func (*CreatePlayerIdentityTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{3}
}

func (m *CreatePlayerIdentityTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerIdentityTokenResponse.Unmarshal(m, b)
}
func (m *CreatePlayerIdentityTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerIdentityTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreatePlayerIdentityTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerIdentityTokenResponse.Merge(m, src)
}
func (m *CreatePlayerIdentityTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerIdentityTokenResponse.Size(m)
}
func (m *CreatePlayerIdentityTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerIdentityTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerIdentityTokenResponse proto.InternalMessageInfo

func (m *CreatePlayerIdentityTokenResponse) GetPlayerIdentityToken() string {
	if m != nil {
		return m.PlayerIdentityToken
	}
	return ""
}

type DecodePlayerIdentityTokenRequest struct {
	PlayerIdentityToken  string   `protobuf:"bytes,1,opt,name=player_identity_token,json=playerIdentityToken,proto3" json:"player_identity_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecodePlayerIdentityTokenRequest) Reset()         { *m = DecodePlayerIdentityTokenRequest{} }
func (m *DecodePlayerIdentityTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DecodePlayerIdentityTokenRequest) ProtoMessage()    {}
func (*DecodePlayerIdentityTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{4}
}

func (m *DecodePlayerIdentityTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecodePlayerIdentityTokenRequest.Unmarshal(m, b)
}
func (m *DecodePlayerIdentityTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecodePlayerIdentityTokenRequest.Marshal(b, m, deterministic)
}
func (m *DecodePlayerIdentityTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecodePlayerIdentityTokenRequest.Merge(m, src)
}
func (m *DecodePlayerIdentityTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DecodePlayerIdentityTokenRequest.Size(m)
}
func (m *DecodePlayerIdentityTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecodePlayerIdentityTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecodePlayerIdentityTokenRequest proto.InternalMessageInfo

func (m *DecodePlayerIdentityTokenRequest) GetPlayerIdentityToken() string {
	if m != nil {
		return m.PlayerIdentityToken
	}
	return ""
}

type DecodePlayerIdentityTokenResponse struct {
	PlayerIdentityToken  *PlayerIdentityToken `protobuf:"bytes,1,opt,name=player_identity_token,json=playerIdentityToken,proto3" json:"player_identity_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DecodePlayerIdentityTokenResponse) Reset()         { *m = DecodePlayerIdentityTokenResponse{} }
func (m *DecodePlayerIdentityTokenResponse) String() string { return proto.CompactTextString(m) }
func (*DecodePlayerIdentityTokenResponse) ProtoMessage()    {}
func (*DecodePlayerIdentityTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{5}
}

func (m *DecodePlayerIdentityTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecodePlayerIdentityTokenResponse.Unmarshal(m, b)
}
func (m *DecodePlayerIdentityTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecodePlayerIdentityTokenResponse.Marshal(b, m, deterministic)
}
func (m *DecodePlayerIdentityTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecodePlayerIdentityTokenResponse.Merge(m, src)
}
func (m *DecodePlayerIdentityTokenResponse) XXX_Size() int {
	return xxx_messageInfo_DecodePlayerIdentityTokenResponse.Size(m)
}
func (m *DecodePlayerIdentityTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecodePlayerIdentityTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecodePlayerIdentityTokenResponse proto.InternalMessageInfo

func (m *DecodePlayerIdentityTokenResponse) GetPlayerIdentityToken() *PlayerIdentityToken {
	if m != nil {
		return m.PlayerIdentityToken
	}
	return nil
}

type PlayerIdentityToken struct {
	Provider             string               `protobuf:"bytes,1,opt,name=provider,json=prvdr,proto3" json:"provider,omitempty"`
	PlayerIdentifier     string               `protobuf:"bytes,2,opt,name=player_identifier,json=sub,proto3" json:"player_identifier,omitempty"`
	ProjectName          string               `protobuf:"bytes,3,opt,name=project_name,json=prj,proto3" json:"project_name,omitempty"`
	DisplayName          string               `protobuf:"bytes,5,opt,name=display_name,json=dn,proto3" json:"display_name,omitempty"`
	Metadata             []byte               `protobuf:"bytes,6,opt,name=metadata,json=md,proto3" json:"metadata,omitempty"`
	IssuedAtTime         *timestamp.Timestamp `protobuf:"bytes,7,opt,name=issued_at_time,json=iat,proto3" json:"issued_at_time,omitempty"`
	ExpiryTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=expiry_time,json=exp,proto3" json:"expiry_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlayerIdentityToken) Reset()         { *m = PlayerIdentityToken{} }
func (m *PlayerIdentityToken) String() string { return proto.CompactTextString(m) }
func (*PlayerIdentityToken) ProtoMessage()    {}
func (*PlayerIdentityToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{6}
}

func (m *PlayerIdentityToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerIdentityToken.Unmarshal(m, b)
}
func (m *PlayerIdentityToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerIdentityToken.Marshal(b, m, deterministic)
}
func (m *PlayerIdentityToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerIdentityToken.Merge(m, src)
}
func (m *PlayerIdentityToken) XXX_Size() int {
	return xxx_messageInfo_PlayerIdentityToken.Size(m)
}
func (m *PlayerIdentityToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerIdentityToken.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerIdentityToken proto.InternalMessageInfo

func (m *PlayerIdentityToken) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *PlayerIdentityToken) GetPlayerIdentifier() string {
	if m != nil {
		return m.PlayerIdentifier
	}
	return ""
}

func (m *PlayerIdentityToken) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *PlayerIdentityToken) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *PlayerIdentityToken) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PlayerIdentityToken) GetIssuedAtTime() *timestamp.Timestamp {
	if m != nil {
		return m.IssuedAtTime
	}
	return nil
}

func (m *PlayerIdentityToken) GetExpiryTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiryTime
	}
	return nil
}

type LoginToken struct {
	Provider             string               `protobuf:"bytes,1,opt,name=provider,json=prvdr,proto3" json:"provider,omitempty"`
	PlayerIdentifier     string               `protobuf:"bytes,2,opt,name=player_identifier,json=sub,proto3" json:"player_identifier,omitempty"`
	ProjectName          string               `protobuf:"bytes,3,opt,name=project_name,json=prj,proto3" json:"project_name,omitempty"`
	DeploymentId         string               `protobuf:"bytes,4,opt,name=deployment_id,json=dpl,proto3" json:"deployment_id,omitempty"`
	WorkerType           string               `protobuf:"bytes,5,opt,name=worker_type,json=wkt,proto3" json:"worker_type,omitempty"`
	IssuedAtTime         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=issued_at_time,json=iat,proto3" json:"issued_at_time,omitempty"`
	ExpiryTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=expiry_time,json=exp,proto3" json:"expiry_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginToken) Reset()         { *m = LoginToken{} }
func (m *LoginToken) String() string { return proto.CompactTextString(m) }
func (*LoginToken) ProtoMessage()    {}
func (*LoginToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{7}
}

func (m *LoginToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginToken.Unmarshal(m, b)
}
func (m *LoginToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginToken.Marshal(b, m, deterministic)
}
func (m *LoginToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginToken.Merge(m, src)
}
func (m *LoginToken) XXX_Size() int {
	return xxx_messageInfo_LoginToken.Size(m)
}
func (m *LoginToken) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginToken.DiscardUnknown(m)
}

var xxx_messageInfo_LoginToken proto.InternalMessageInfo

func (m *LoginToken) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *LoginToken) GetPlayerIdentifier() string {
	if m != nil {
		return m.PlayerIdentifier
	}
	return ""
}

func (m *LoginToken) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *LoginToken) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *LoginToken) GetWorkerType() string {
	if m != nil {
		return m.WorkerType
	}
	return ""
}

func (m *LoginToken) GetIssuedAtTime() *timestamp.Timestamp {
	if m != nil {
		return m.IssuedAtTime
	}
	return nil
}

func (m *LoginToken) GetExpiryTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiryTime
	}
	return nil
}

type DevelopmentAuthenticationToken struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectName          string               `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	ExpirationTime       *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DevelopmentAuthenticationToken) Reset()         { *m = DevelopmentAuthenticationToken{} }
func (m *DevelopmentAuthenticationToken) String() string { return proto.CompactTextString(m) }
func (*DevelopmentAuthenticationToken) ProtoMessage()    {}
func (*DevelopmentAuthenticationToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{8}
}

func (m *DevelopmentAuthenticationToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevelopmentAuthenticationToken.Unmarshal(m, b)
}
func (m *DevelopmentAuthenticationToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevelopmentAuthenticationToken.Marshal(b, m, deterministic)
}
func (m *DevelopmentAuthenticationToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevelopmentAuthenticationToken.Merge(m, src)
}
func (m *DevelopmentAuthenticationToken) XXX_Size() int {
	return xxx_messageInfo_DevelopmentAuthenticationToken.Size(m)
}
func (m *DevelopmentAuthenticationToken) XXX_DiscardUnknown() {
	xxx_messageInfo_DevelopmentAuthenticationToken.DiscardUnknown(m)
}

var xxx_messageInfo_DevelopmentAuthenticationToken proto.InternalMessageInfo

func (m *DevelopmentAuthenticationToken) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DevelopmentAuthenticationToken) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *DevelopmentAuthenticationToken) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DevelopmentAuthenticationToken) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *DevelopmentAuthenticationToken) GetExpirationTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpirationTime
	}
	return nil
}

type CreateDevelopmentAuthenticationTokenRequest struct {
	ProjectName          string             `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description          string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Lifetime             *duration.Duration `protobuf:"bytes,3,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateDevelopmentAuthenticationTokenRequest) Reset() {
	*m = CreateDevelopmentAuthenticationTokenRequest{}
}
func (m *CreateDevelopmentAuthenticationTokenRequest) String() string {
	return proto.CompactTextString(m)
}
func (*CreateDevelopmentAuthenticationTokenRequest) ProtoMessage() {}
func (*CreateDevelopmentAuthenticationTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{9}
}

func (m *CreateDevelopmentAuthenticationTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDevelopmentAuthenticationTokenRequest.Unmarshal(m, b)
}
func (m *CreateDevelopmentAuthenticationTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDevelopmentAuthenticationTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateDevelopmentAuthenticationTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDevelopmentAuthenticationTokenRequest.Merge(m, src)
}
func (m *CreateDevelopmentAuthenticationTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDevelopmentAuthenticationTokenRequest.Size(m)
}
func (m *CreateDevelopmentAuthenticationTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDevelopmentAuthenticationTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDevelopmentAuthenticationTokenRequest proto.InternalMessageInfo

func (m *CreateDevelopmentAuthenticationTokenRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *CreateDevelopmentAuthenticationTokenRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateDevelopmentAuthenticationTokenRequest) GetLifetime() *duration.Duration {
	if m != nil {
		return m.Lifetime
	}
	return nil
}

type CreateDevelopmentAuthenticationTokenResponse struct {
	DevelopmentAuthenticationToken *DevelopmentAuthenticationToken `protobuf:"bytes,1,opt,name=development_authentication_token,json=developmentAuthenticationToken,proto3" json:"development_authentication_token,omitempty"`
	TokenSecret                    string                          `protobuf:"bytes,2,opt,name=token_secret,json=tokenSecret,proto3" json:"token_secret,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                        `json:"-"`
	XXX_unrecognized               []byte                          `json:"-"`
	XXX_sizecache                  int32                           `json:"-"`
}

func (m *CreateDevelopmentAuthenticationTokenResponse) Reset() {
	*m = CreateDevelopmentAuthenticationTokenResponse{}
}
func (m *CreateDevelopmentAuthenticationTokenResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CreateDevelopmentAuthenticationTokenResponse) ProtoMessage() {}
func (*CreateDevelopmentAuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{10}
}

func (m *CreateDevelopmentAuthenticationTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDevelopmentAuthenticationTokenResponse.Unmarshal(m, b)
}
func (m *CreateDevelopmentAuthenticationTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDevelopmentAuthenticationTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreateDevelopmentAuthenticationTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDevelopmentAuthenticationTokenResponse.Merge(m, src)
}
func (m *CreateDevelopmentAuthenticationTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDevelopmentAuthenticationTokenResponse.Size(m)
}
func (m *CreateDevelopmentAuthenticationTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDevelopmentAuthenticationTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDevelopmentAuthenticationTokenResponse proto.InternalMessageInfo

func (m *CreateDevelopmentAuthenticationTokenResponse) GetDevelopmentAuthenticationToken() *DevelopmentAuthenticationToken {
	if m != nil {
		return m.DevelopmentAuthenticationToken
	}
	return nil
}

func (m *CreateDevelopmentAuthenticationTokenResponse) GetTokenSecret() string {
	if m != nil {
		return m.TokenSecret
	}
	return ""
}

type GetDevelopmentAuthenticationTokenRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDevelopmentAuthenticationTokenRequest) Reset() {
	*m = GetDevelopmentAuthenticationTokenRequest{}
}
func (m *GetDevelopmentAuthenticationTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetDevelopmentAuthenticationTokenRequest) ProtoMessage()    {}
func (*GetDevelopmentAuthenticationTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{11}
}

func (m *GetDevelopmentAuthenticationTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevelopmentAuthenticationTokenRequest.Unmarshal(m, b)
}
func (m *GetDevelopmentAuthenticationTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevelopmentAuthenticationTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetDevelopmentAuthenticationTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevelopmentAuthenticationTokenRequest.Merge(m, src)
}
func (m *GetDevelopmentAuthenticationTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetDevelopmentAuthenticationTokenRequest.Size(m)
}
func (m *GetDevelopmentAuthenticationTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevelopmentAuthenticationTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevelopmentAuthenticationTokenRequest proto.InternalMessageInfo

func (m *GetDevelopmentAuthenticationTokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetDevelopmentAuthenticationTokenResponse struct {
	DevelopmentAuthenticationToken *DevelopmentAuthenticationToken `protobuf:"bytes,1,opt,name=development_authentication_token,json=developmentAuthenticationToken,proto3" json:"development_authentication_token,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                        `json:"-"`
	XXX_unrecognized               []byte                          `json:"-"`
	XXX_sizecache                  int32                           `json:"-"`
}

func (m *GetDevelopmentAuthenticationTokenResponse) Reset() {
	*m = GetDevelopmentAuthenticationTokenResponse{}
}
func (m *GetDevelopmentAuthenticationTokenResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetDevelopmentAuthenticationTokenResponse) ProtoMessage() {}
func (*GetDevelopmentAuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{12}
}

func (m *GetDevelopmentAuthenticationTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevelopmentAuthenticationTokenResponse.Unmarshal(m, b)
}
func (m *GetDevelopmentAuthenticationTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevelopmentAuthenticationTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetDevelopmentAuthenticationTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevelopmentAuthenticationTokenResponse.Merge(m, src)
}
func (m *GetDevelopmentAuthenticationTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetDevelopmentAuthenticationTokenResponse.Size(m)
}
func (m *GetDevelopmentAuthenticationTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevelopmentAuthenticationTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevelopmentAuthenticationTokenResponse proto.InternalMessageInfo

func (m *GetDevelopmentAuthenticationTokenResponse) GetDevelopmentAuthenticationToken() *DevelopmentAuthenticationToken {
	if m != nil {
		return m.DevelopmentAuthenticationToken
	}
	return nil
}

type ListDevelopmentAuthenticationTokensRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	IncludeExpired       bool     `protobuf:"varint,2,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDevelopmentAuthenticationTokensRequest) Reset() {
	*m = ListDevelopmentAuthenticationTokensRequest{}
}
func (m *ListDevelopmentAuthenticationTokensRequest) String() string {
	return proto.CompactTextString(m)
}
func (*ListDevelopmentAuthenticationTokensRequest) ProtoMessage() {}
func (*ListDevelopmentAuthenticationTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{13}
}

func (m *ListDevelopmentAuthenticationTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevelopmentAuthenticationTokensRequest.Unmarshal(m, b)
}
func (m *ListDevelopmentAuthenticationTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevelopmentAuthenticationTokensRequest.Marshal(b, m, deterministic)
}
func (m *ListDevelopmentAuthenticationTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevelopmentAuthenticationTokensRequest.Merge(m, src)
}
func (m *ListDevelopmentAuthenticationTokensRequest) XXX_Size() int {
	return xxx_messageInfo_ListDevelopmentAuthenticationTokensRequest.Size(m)
}
func (m *ListDevelopmentAuthenticationTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevelopmentAuthenticationTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevelopmentAuthenticationTokensRequest proto.InternalMessageInfo

func (m *ListDevelopmentAuthenticationTokensRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *ListDevelopmentAuthenticationTokensRequest) GetIncludeExpired() bool {
	if m != nil {
		return m.IncludeExpired
	}
	return false
}

func (m *ListDevelopmentAuthenticationTokensRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListDevelopmentAuthenticationTokensRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListDevelopmentAuthenticationTokensResponse struct {
	DevelopmentAuthenticationTokens []*DevelopmentAuthenticationToken `protobuf:"bytes,1,rep,name=development_authentication_tokens,json=developmentAuthenticationTokens,proto3" json:"development_authentication_tokens,omitempty"`
	NextPageToken                   string                            `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                          `json:"-"`
	XXX_unrecognized                []byte                            `json:"-"`
	XXX_sizecache                   int32                             `json:"-"`
}

func (m *ListDevelopmentAuthenticationTokensResponse) Reset() {
	*m = ListDevelopmentAuthenticationTokensResponse{}
}
func (m *ListDevelopmentAuthenticationTokensResponse) String() string {
	return proto.CompactTextString(m)
}
func (*ListDevelopmentAuthenticationTokensResponse) ProtoMessage() {}
func (*ListDevelopmentAuthenticationTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{14}
}

func (m *ListDevelopmentAuthenticationTokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevelopmentAuthenticationTokensResponse.Unmarshal(m, b)
}
func (m *ListDevelopmentAuthenticationTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevelopmentAuthenticationTokensResponse.Marshal(b, m, deterministic)
}
func (m *ListDevelopmentAuthenticationTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevelopmentAuthenticationTokensResponse.Merge(m, src)
}
func (m *ListDevelopmentAuthenticationTokensResponse) XXX_Size() int {
	return xxx_messageInfo_ListDevelopmentAuthenticationTokensResponse.Size(m)
}
func (m *ListDevelopmentAuthenticationTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevelopmentAuthenticationTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevelopmentAuthenticationTokensResponse proto.InternalMessageInfo

func (m *ListDevelopmentAuthenticationTokensResponse) GetDevelopmentAuthenticationTokens() []*DevelopmentAuthenticationToken {
	if m != nil {
		return m.DevelopmentAuthenticationTokens
	}
	return nil
}

func (m *ListDevelopmentAuthenticationTokensResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type UpdateDevelopmentAuthenticationTokenRequest struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedLifetime      *duration.Duration `protobuf:"bytes,3,opt,name=updated_lifetime,json=updatedLifetime,proto3" json:"updated_lifetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateDevelopmentAuthenticationTokenRequest) Reset() {
	*m = UpdateDevelopmentAuthenticationTokenRequest{}
}
func (m *UpdateDevelopmentAuthenticationTokenRequest) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateDevelopmentAuthenticationTokenRequest) ProtoMessage() {}
func (*UpdateDevelopmentAuthenticationTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{15}
}

func (m *UpdateDevelopmentAuthenticationTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDevelopmentAuthenticationTokenRequest.Unmarshal(m, b)
}
func (m *UpdateDevelopmentAuthenticationTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDevelopmentAuthenticationTokenRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDevelopmentAuthenticationTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDevelopmentAuthenticationTokenRequest.Merge(m, src)
}
func (m *UpdateDevelopmentAuthenticationTokenRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDevelopmentAuthenticationTokenRequest.Size(m)
}
func (m *UpdateDevelopmentAuthenticationTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDevelopmentAuthenticationTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDevelopmentAuthenticationTokenRequest proto.InternalMessageInfo

func (m *UpdateDevelopmentAuthenticationTokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDevelopmentAuthenticationTokenRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateDevelopmentAuthenticationTokenRequest) GetUpdatedLifetime() *duration.Duration {
	if m != nil {
		return m.UpdatedLifetime
	}
	return nil
}

type UpdateDevelopmentAuthenticationTokenResponse struct {
	DevelopmentAuthenticationToken *DevelopmentAuthenticationToken `protobuf:"bytes,1,opt,name=development_authentication_token,json=developmentAuthenticationToken,proto3" json:"development_authentication_token,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                        `json:"-"`
	XXX_unrecognized               []byte                          `json:"-"`
	XXX_sizecache                  int32                           `json:"-"`
}

func (m *UpdateDevelopmentAuthenticationTokenResponse) Reset() {
	*m = UpdateDevelopmentAuthenticationTokenResponse{}
}
func (m *UpdateDevelopmentAuthenticationTokenResponse) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateDevelopmentAuthenticationTokenResponse) ProtoMessage() {}
func (*UpdateDevelopmentAuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{16}
}

func (m *UpdateDevelopmentAuthenticationTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDevelopmentAuthenticationTokenResponse.Unmarshal(m, b)
}
func (m *UpdateDevelopmentAuthenticationTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDevelopmentAuthenticationTokenResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDevelopmentAuthenticationTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDevelopmentAuthenticationTokenResponse.Merge(m, src)
}
func (m *UpdateDevelopmentAuthenticationTokenResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDevelopmentAuthenticationTokenResponse.Size(m)
}
func (m *UpdateDevelopmentAuthenticationTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDevelopmentAuthenticationTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDevelopmentAuthenticationTokenResponse proto.InternalMessageInfo

func (m *UpdateDevelopmentAuthenticationTokenResponse) GetDevelopmentAuthenticationToken() *DevelopmentAuthenticationToken {
	if m != nil {
		return m.DevelopmentAuthenticationToken
	}
	return nil
}

type ExpireDevelopmentAuthenticationTokenRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpireDevelopmentAuthenticationTokenRequest) Reset() {
	*m = ExpireDevelopmentAuthenticationTokenRequest{}
}
func (m *ExpireDevelopmentAuthenticationTokenRequest) String() string {
	return proto.CompactTextString(m)
}
func (*ExpireDevelopmentAuthenticationTokenRequest) ProtoMessage() {}
func (*ExpireDevelopmentAuthenticationTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{17}
}

func (m *ExpireDevelopmentAuthenticationTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpireDevelopmentAuthenticationTokenRequest.Unmarshal(m, b)
}
func (m *ExpireDevelopmentAuthenticationTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpireDevelopmentAuthenticationTokenRequest.Marshal(b, m, deterministic)
}
func (m *ExpireDevelopmentAuthenticationTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpireDevelopmentAuthenticationTokenRequest.Merge(m, src)
}
func (m *ExpireDevelopmentAuthenticationTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ExpireDevelopmentAuthenticationTokenRequest.Size(m)
}
func (m *ExpireDevelopmentAuthenticationTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpireDevelopmentAuthenticationTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpireDevelopmentAuthenticationTokenRequest proto.InternalMessageInfo

func (m *ExpireDevelopmentAuthenticationTokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ExpireDevelopmentAuthenticationTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpireDevelopmentAuthenticationTokenResponse) Reset() {
	*m = ExpireDevelopmentAuthenticationTokenResponse{}
}
func (m *ExpireDevelopmentAuthenticationTokenResponse) String() string {
	return proto.CompactTextString(m)
}
func (*ExpireDevelopmentAuthenticationTokenResponse) ProtoMessage() {}
func (*ExpireDevelopmentAuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{18}
}

func (m *ExpireDevelopmentAuthenticationTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpireDevelopmentAuthenticationTokenResponse.Unmarshal(m, b)
}
func (m *ExpireDevelopmentAuthenticationTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpireDevelopmentAuthenticationTokenResponse.Marshal(b, m, deterministic)
}
func (m *ExpireDevelopmentAuthenticationTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpireDevelopmentAuthenticationTokenResponse.Merge(m, src)
}
func (m *ExpireDevelopmentAuthenticationTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ExpireDevelopmentAuthenticationTokenResponse.Size(m)
}
func (m *ExpireDevelopmentAuthenticationTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpireDevelopmentAuthenticationTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExpireDevelopmentAuthenticationTokenResponse proto.InternalMessageInfo

type DeleteDevelopmentAuthenticationTokenRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDevelopmentAuthenticationTokenRequest) Reset() {
	*m = DeleteDevelopmentAuthenticationTokenRequest{}
}
func (m *DeleteDevelopmentAuthenticationTokenRequest) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteDevelopmentAuthenticationTokenRequest) ProtoMessage() {}
func (*DeleteDevelopmentAuthenticationTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{19}
}

func (m *DeleteDevelopmentAuthenticationTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDevelopmentAuthenticationTokenRequest.Unmarshal(m, b)
}
func (m *DeleteDevelopmentAuthenticationTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDevelopmentAuthenticationTokenRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDevelopmentAuthenticationTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDevelopmentAuthenticationTokenRequest.Merge(m, src)
}
func (m *DeleteDevelopmentAuthenticationTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDevelopmentAuthenticationTokenRequest.Size(m)
}
func (m *DeleteDevelopmentAuthenticationTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDevelopmentAuthenticationTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDevelopmentAuthenticationTokenRequest proto.InternalMessageInfo

func (m *DeleteDevelopmentAuthenticationTokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDevelopmentAuthenticationTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDevelopmentAuthenticationTokenResponse) Reset() {
	*m = DeleteDevelopmentAuthenticationTokenResponse{}
}
func (m *DeleteDevelopmentAuthenticationTokenResponse) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteDevelopmentAuthenticationTokenResponse) ProtoMessage() {}
func (*DeleteDevelopmentAuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7efaf7166d9d3a5, []int{20}
}

func (m *DeleteDevelopmentAuthenticationTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDevelopmentAuthenticationTokenResponse.Unmarshal(m, b)
}
func (m *DeleteDevelopmentAuthenticationTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDevelopmentAuthenticationTokenResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDevelopmentAuthenticationTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDevelopmentAuthenticationTokenResponse.Merge(m, src)
}
func (m *DeleteDevelopmentAuthenticationTokenResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDevelopmentAuthenticationTokenResponse.Size(m)
}
func (m *DeleteDevelopmentAuthenticationTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDevelopmentAuthenticationTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDevelopmentAuthenticationTokenResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateLoginTokenRequest)(nil), "improbable.spatialos.playerauth.v2.CreateLoginTokenRequest")
	proto.RegisterType((*CreateLoginTokenResponse)(nil), "improbable.spatialos.playerauth.v2.CreateLoginTokenResponse")
	proto.RegisterType((*CreatePlayerIdentityTokenRequest)(nil), "improbable.spatialos.playerauth.v2.CreatePlayerIdentityTokenRequest")
	proto.RegisterType((*CreatePlayerIdentityTokenResponse)(nil), "improbable.spatialos.playerauth.v2.CreatePlayerIdentityTokenResponse")
	proto.RegisterType((*DecodePlayerIdentityTokenRequest)(nil), "improbable.spatialos.playerauth.v2.DecodePlayerIdentityTokenRequest")
	proto.RegisterType((*DecodePlayerIdentityTokenResponse)(nil), "improbable.spatialos.playerauth.v2.DecodePlayerIdentityTokenResponse")
	proto.RegisterType((*PlayerIdentityToken)(nil), "improbable.spatialos.playerauth.v2.PlayerIdentityToken")
	proto.RegisterType((*LoginToken)(nil), "improbable.spatialos.playerauth.v2.LoginToken")
	proto.RegisterType((*DevelopmentAuthenticationToken)(nil), "improbable.spatialos.playerauth.v2.DevelopmentAuthenticationToken")
	proto.RegisterType((*CreateDevelopmentAuthenticationTokenRequest)(nil), "improbable.spatialos.playerauth.v2.CreateDevelopmentAuthenticationTokenRequest")
	proto.RegisterType((*CreateDevelopmentAuthenticationTokenResponse)(nil), "improbable.spatialos.playerauth.v2.CreateDevelopmentAuthenticationTokenResponse")
	proto.RegisterType((*GetDevelopmentAuthenticationTokenRequest)(nil), "improbable.spatialos.playerauth.v2.GetDevelopmentAuthenticationTokenRequest")
	proto.RegisterType((*GetDevelopmentAuthenticationTokenResponse)(nil), "improbable.spatialos.playerauth.v2.GetDevelopmentAuthenticationTokenResponse")
	proto.RegisterType((*ListDevelopmentAuthenticationTokensRequest)(nil), "improbable.spatialos.playerauth.v2.ListDevelopmentAuthenticationTokensRequest")
	proto.RegisterType((*ListDevelopmentAuthenticationTokensResponse)(nil), "improbable.spatialos.playerauth.v2.ListDevelopmentAuthenticationTokensResponse")
	proto.RegisterType((*UpdateDevelopmentAuthenticationTokenRequest)(nil), "improbable.spatialos.playerauth.v2.UpdateDevelopmentAuthenticationTokenRequest")
	proto.RegisterType((*UpdateDevelopmentAuthenticationTokenResponse)(nil), "improbable.spatialos.playerauth.v2.UpdateDevelopmentAuthenticationTokenResponse")
	proto.RegisterType((*ExpireDevelopmentAuthenticationTokenRequest)(nil), "improbable.spatialos.playerauth.v2.ExpireDevelopmentAuthenticationTokenRequest")
	proto.RegisterType((*ExpireDevelopmentAuthenticationTokenResponse)(nil), "improbable.spatialos.playerauth.v2.ExpireDevelopmentAuthenticationTokenResponse")
	proto.RegisterType((*DeleteDevelopmentAuthenticationTokenRequest)(nil), "improbable.spatialos.playerauth.v2.DeleteDevelopmentAuthenticationTokenRequest")
	proto.RegisterType((*DeleteDevelopmentAuthenticationTokenResponse)(nil), "improbable.spatialos.playerauth.v2.DeleteDevelopmentAuthenticationTokenResponse")
}

func init() {
	proto.RegisterFile("improbable/spatialos/playerauth/v2/playerauth.proto", fileDescriptor_e7efaf7166d9d3a5)
}

var fileDescriptor_e7efaf7166d9d3a5 = []byte{
	// 1680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x99, 0xcd, 0x53, 0x1b, 0x47,
	0x16, 0xc0, 0x77, 0x46, 0x80, 0xe1, 0x89, 0xcf, 0xc6, 0x36, 0x42, 0x2e, 0x23, 0x31, 0xc6, 0x36,
	0x18, 0x21, 0xed, 0x8a, 0x5d, 0xdb, 0xbb, 0xac, 0xcb, 0x1e, 0x8c, 0xbd, 0x45, 0x15, 0x6b, 0xd8,
	0x81, 0xf5, 0x7a, 0xfd, 0x35, 0x35, 0xd2, 0x34, 0xa2, 0xcd, 0x48, 0x33, 0x3b, 0x33, 0x12, 0xe0,
	0x8f, 0xc3, 0x5e, 0x52, 0x39, 0xa4, 0x72, 0xca, 0xc1, 0xe1, 0x10, 0x57, 0x5c, 0x95, 0x8b, 0xfd,
	0x1f, 0xa4, 0x2a, 0x47, 0x1f, 0x92, 0xff, 0x20, 0x5c, 0xa0, 0x38, 0xa4, 0xf2, 0x27, 0xe4, 0x90,
	0xaa, 0xa4, 0x66, 0x7a, 0x24, 0x8d, 0xa4, 0x91, 0xd4, 0x38, 0x54, 0xca, 0x3e, 0x49, 0xdd, 0xef,
	0xbd, 0xee, 0xf7, 0x7b, 0x1f, 0x7a, 0x6d, 0x60, 0x96, 0xe4, 0x0d, 0x53, 0xcf, 0x28, 0x19, 0x0d,
	0xa7, 0x2c, 0x43, 0xb1, 0x89, 0xa2, 0xe9, 0x56, 0xca, 0xd0, 0x94, 0x1d, 0x6c, 0x2a, 0x45, 0x7b,
	0x23, 0x55, 0x4a, 0xfb, 0xbe, 0x25, 0x0d, 0x53, 0xb7, 0x75, 0x24, 0x54, 0x95, 0x92, 0x15, 0xa5,
	0xa4, 0x4f, 0xac, 0x94, 0x8e, 0xce, 0xe5, 0x88, 0xbd, 0x51, 0xcc, 0x24, 0xb3, 0x7a, 0x3e, 0x55,
	0x15, 0x9f, 0x21, 0x7a, 0x2a, 0xa7, 0xcf, 0xb8, 0x66, 0x66, 0x34, 0x3d, 0xb7, 0x4e, 0xb0, 0xa6,
	0x5a, 0xa9, 0xca, 0x27, 0x7a, 0x40, 0xf4, 0xb2, 0x4f, 0x39, 0xbf, 0x45, 0xec, 0x4d, 0x7d, 0xab,
	0xaa, 0x56, 0x52, 0x34, 0xa2, 0x2a, 0xb6, 0x6e, 0x5a, 0xa9, 0xca, 0x47, 0x4f, 0x6f, 0x24, 0xa7,
	0xeb, 0x39, 0x0d, 0xa7, 0x14, 0x83, 0xa4, 0xb2, 0x1a, 0xc1, 0x05, 0xdb, 0xdb, 0x88, 0xf9, 0x36,
	0xdc, 0x93, 0xe4, 0x0c, 0xde, 0x50, 0x4a, 0xa4, 0xa2, 0x39, 0xe6, 0x09, 0xb8, 0xdf, 0x32, 0xc5,
	0xf5, 0x94, 0x5a, 0x34, 0x15, 0x9b, 0xe8, 0x85, 0x3a, 0x03, 0x95, 0x7d, 0x9b, 0xe4, 0xb1, 0x65,
	0x2b, 0x79, 0xc3, 0x13, 0xb8, 0xe0, 0x03, 0x89, 0xb7, 0xed, 0x94, 0xa1, 0x15, 0x73, 0xa4, 0x90,
	0x72, 0x19, 0x1a, 0xd8, 0xcc, 0x7b, 0xae, 0x09, 0x9f, 0xf3, 0x30, 0x72, 0xd3, 0xc4, 0x8a, 0x8d,
	0x97, 0xf4, 0x1c, 0x29, 0xac, 0xe9, 0x9b, 0xb8, 0x20, 0xe1, 0xff, 0x15, 0xb1, 0x65, 0xa3, 0x2b,
	0x70, 0x8a, 0x42, 0x94, 0x89, 0x8a, 0x0b, 0x36, 0xb1, 0x77, 0x64, 0xdb, 0xd9, 0x8f, 0x70, 0x71,
	0x6e, 0xb2, 0x67, 0x3e, 0x74, 0x20, 0xf2, 0xd2, 0x30, 0x95, 0x58, 0xf4, 0x04, 0x5c, 0x7d, 0x34,
	0x07, 0x7d, 0x2a, 0x36, 0x34, 0x7d, 0x27, 0x8f, 0x0b, 0xb6, 0x4c, 0xd4, 0x08, 0xef, 0x2a, 0x9c,
	0x3e, 0x10, 0xf9, 0xd7, 0x6f, 0xc7, 0x06, 0xea, 0x76, 0xa5, 0xde, 0xea, 0xd7, 0x45, 0x15, 0xdd,
	0x86, 0x21, 0x8d, 0xac, 0x63, 0xc7, 0x21, 0xb9, 0xec, 0x75, 0x24, 0x14, 0xe7, 0x26, 0xc3, 0xe9,
	0xd1, 0x24, 0x75, 0x3b, 0x59, 0x76, 0x3b, 0xb9, 0xe0, 0x09, 0x48, 0x83, 0x65, 0x9d, 0xf2, 0x0a,
	0xba, 0x01, 0xe1, 0x2d, 0xdd, 0xdc, 0xc4, 0xa6, 0x6c, 0xef, 0x18, 0x38, 0xd2, 0xe1, 0x5e, 0x21,
	0x76, 0xb8, 0x1f, 0x3b, 0x03, 0xa3, 0x8f, 0x27, 0x9e, 0x3f, 0x7e, 0xa0, 0xcc, 0x3c, 0x15, 0x67,
	0xee, 0xff, 0x71, 0xe6, 0xaf, 0xf2, 0xcc, 0xa3, 0x67, 0xb3, 0x89, 0x3f, 0xa5, 0xaf, 0xbe, 0x98,
	0x90, 0x80, 0xea, 0xac, 0xed, 0x18, 0x58, 0x98, 0x83, 0x48, 0x23, 0x1a, 0xcb, 0xd0, 0x0b, 0x16,
	0x46, 0x31, 0x08, 0x6b, 0xce, 0xaa, 0x9f, 0x88, 0x04, 0x5a, 0x45, 0x50, 0xf8, 0x9e, 0x87, 0x38,
	0xd5, 0x5e, 0x69, 0x24, 0x54, 0x26, 0x7c, 0x1e, 0xba, 0x0d, 0x53, 0x2f, 0x11, 0x15, 0x9b, 0x1e,
	0xd4, 0x9e, 0x03, 0x91, 0x3f, 0xdc, 0x8f, 0xf1, 0xf7, 0x38, 0xa9, 0xb2, 0x85, 0x2e, 0xc3, 0x50,
	0x4d, 0x20, 0xd6, 0x09, 0x36, 0x3d, 0xa6, 0x3e, 0xf9, 0x41, 0x7f, 0x28, 0x1c, 0x11, 0xb4, 0x0c,
	0xbd, 0x86, 0xa9, 0x3f, 0xc1, 0x59, 0x5b, 0x2e, 0x28, 0x79, 0xec, 0x52, 0xec, 0x99, 0x4f, 0xd0,
	0x30, 0xf4, 0xd7, 0x6e, 0x1e, 0xee, 0xc7, 0x86, 0x61, 0xc8, 0xa5, 0xe2, 0x20, 0x71, 0x88, 0xcc,
	0xa6, 0x5f, 0x4c, 0x48, 0x61, 0x4f, 0xe8, 0x8e, 0x92, 0xc7, 0xc1, 0xb1, 0xe9, 0x38, 0x7a, 0x6c,
	0xc6, 0xa1, 0x57, 0x25, 0x96, 0x73, 0x5f, 0x7a, 0xb1, 0x4e, 0x17, 0x5f, 0xd8, 0x5b, 0x73, 0x8f,
	0x8a, 0x42, 0x77, 0x1e, 0xdb, 0x8a, 0xaa, 0xd8, 0x4a, 0xa4, 0x2b, 0xce, 0x4d, 0xf6, 0x4a, 0x95,
	0xef, 0xc2, 0x7f, 0x60, 0xbc, 0x05, 0x5a, 0x2f, 0x42, 0xe9, 0x96, 0xd9, 0x1b, 0x98, 0xb8, 0x82,
	0x02, 0xf1, 0x05, 0x9c, 0xd5, 0xd5, 0x56, 0x31, 0xbb, 0xd6, 0xba, 0x2a, 0x7c, 0x01, 0x09, 0x3c,
	0xe2, 0x25, 0x07, 0xe3, 0x2d, 0xce, 0xf0, 0x2e, 0x6f, 0xb5, 0x3a, 0x24, 0x9c, 0xbe, 0x92, 0x6c,
	0xdf, 0xf2, 0x92, 0x01, 0xf6, 0xe7, 0xbb, 0x9c, 0xab, 0xc5, 0x9b, 0x5c, 0xed, 0x4b, 0x1e, 0x86,
	0x03, 0x94, 0xd0, 0x48, 0x7d, 0x96, 0x4a, 0x9d, 0x86, 0x59, 0x52, 0x4d, 0x34, 0xd6, 0x34, 0x2f,
	0xa5, 0x90, 0x55, 0xcc, 0xa0, 0x74, 0x60, 0xfe, 0x8d, 0x34, 0x4b, 0xb5, 0x90, 0x61, 0x3e, 0x41,
	0x91, 0xc0, 0xd4, 0xe0, 0xd5, 0x02, 0x3a, 0xd9, 0x90, 0x11, 0x7c, 0x5e, 0x45, 0x57, 0xa0, 0x9f,
	0x58, 0x56, 0x11, 0xab, 0xb2, 0x62, 0xcb, 0x4e, 0x92, 0x45, 0x4e, 0xb8, 0x88, 0xa2, 0x0d, 0xf9,
	0xb8, 0x56, 0x6e, 0x91, 0x52, 0x88, 0x28, 0x36, 0xfa, 0x33, 0x84, 0xf1, 0xb6, 0x41, 0xcc, 0x1d,
	0xaa, 0xd5, 0xdd, 0x5e, 0x0b, 0x6f, 0x1b, 0xc2, 0x17, 0x3c, 0x40, 0xb5, 0x1d, 0xfc, 0xbe, 0x68,
	0xa2, 0xf5, 0x6d, 0xb5, 0x83, 0xda, 0x53, 0x0d, 0x0d, 0x45, 0x6a, 0xbb, 0x1d, 0xa5, 0x16, 0xda,
	0xda, 0xb4, 0x03, 0x00, 0x75, 0xbd, 0x17, 0xa0, 0x13, 0x6c, 0x80, 0xde, 0xf1, 0x30, 0xb6, 0x80,
	0x4b, 0x58, 0xd3, 0x0d, 0xe7, 0x9a, 0x62, 0xd1, 0xde, 0x70, 0xfc, 0xcf, 0xba, 0x85, 0x4f, 0xa1,
	0x09, 0xc0, 0x13, 0xd5, 0x2b, 0x17, 0xf4, 0xfa, 0xed, 0x58, 0x37, 0x74, 0xa9, 0x8a, 0xe3, 0x90,
	0x57, 0x37, 0x3c, 0x51, 0x1b, 0x5a, 0x17, 0xed, 0x76, 0x89, 0xc0, 0xbe, 0x75, 0x1a, 0x4e, 0xfa,
	0xbb, 0x79, 0x70, 0xeb, 0x9a, 0x84, 0xb0, 0x8a, 0xad, 0xac, 0x49, 0x8c, 0xca, 0x0f, 0x4a, 0x0f,
	0x2d, 0x87, 0x7b, 0x9c, 0xe4, 0xdf, 0x42, 0xd7, 0xa1, 0x2f, 0xeb, 0x74, 0x17, 0xa2, 0x17, 0xa8,
	0xe7, 0x1d, 0x6d, 0x3d, 0xef, 0x2d, 0x2b, 0x38, 0x4b, 0xe8, 0x26, 0x0c, 0xb8, 0xe0, 0x7c, 0x26,
	0x3a, 0xdb, 0x9a, 0xe8, 0xaf, 0xaa, 0x38, 0x8b, 0xc2, 0x8f, 0x1c, 0x4c, 0xd3, 0x26, 0xd7, 0x9a,
	0x66, 0xb9, 0x2d, 0x49, 0x75, 0xc0, 0x28, 0xde, 0x54, 0xb3, 0x5e, 0xcf, 0xc4, 0x2c, 0x59, 0xcb,
	0x8c, 0xc6, 0xa0, 0x97, 0x36, 0xb8, 0x4e, 0xe3, 0x0f, 0xdb, 0xdf, 0xd6, 0x91, 0xfb, 0x0b, 0x74,
	0x97, 0x5b, 0x7d, 0xfb, 0x5f, 0xec, 0x8a, 0xa8, 0x70, 0xc0, 0x41, 0x82, 0xcd, 0x55, 0xaf, 0x3b,
	0x7e, 0xc2, 0x41, 0x5c, 0xad, 0x8a, 0xca, 0x4a, 0x8d, 0x6c, 0x4d, 0xa7, 0x9c, 0x67, 0xe9, 0x94,
	0x6d, 0x8e, 0x1d, 0x53, 0x5b, 0xe7, 0xf3, 0x38, 0xf4, 0xba, 0x47, 0xca, 0x16, 0xce, 0x9a, 0xd8,
	0xf6, 0xca, 0x3c, 0xec, 0xae, 0xad, 0xba, 0x4b, 0xc2, 0xbf, 0x60, 0xf2, 0x1f, 0xd8, 0x66, 0x8b,
	0xe4, 0x79, 0x5f, 0x79, 0x9c, 0xa2, 0xf1, 0x0b, 0xa8, 0x10, 0xe1, 0x6b, 0x0e, 0xa6, 0x18, 0x6c,
	0x7e, 0x90, 0xc8, 0x84, 0xff, 0xf3, 0x70, 0x69, 0x89, 0x58, 0x6d, 0x6e, 0x6f, 0x95, 0x91, 0x3c,
	0x08, 0x4c, 0xee, 0xab, 0xcd, 0x92, 0x3b, 0x06, 0x67, 0x27, 0x1f, 0x3f, 0xbc, 0x34, 0x31, 0xf5,
	0x7c, 0x32, 0x28, 0xc9, 0xa7, 0x6a, 0xb3, 0xfc, 0x22, 0x0c, 0x90, 0x42, 0x56, 0x2b, 0xaa, 0x58,
	0x76, 0x6b, 0x10, 0xd3, 0x79, 0xb5, 0x5b, 0xea, 0xf7, 0x96, 0x6f, 0xd1, 0x55, 0x94, 0x84, 0x1e,
	0x43, 0xc9, 0x61, 0xd9, 0x22, 0x4f, 0x69, 0x7e, 0x77, 0xce, 0x0f, 0x1d, 0xee, 0xc7, 0xfa, 0x06,
	0x7f, 0x29, 0xff, 0xe3, 0x22, 0xb3, 0x52, 0xb7, 0x23, 0xb3, 0x4a, 0x9e, 0x62, 0x74, 0x16, 0xc0,
	0x95, 0xa7, 0x70, 0x69, 0xb3, 0x76, 0x2d, 0x50, 0x06, 0x3f, 0x70, 0x30, 0xcd, 0xc4, 0xc0, 0x0b,
	0xe1, 0xa7, 0x1c, 0x8c, 0xb7, 0x0b, 0xa1, 0x15, 0xe1, 0xe2, 0xa1, 0x63, 0x8a, 0x61, 0xac, 0x75,
	0x0c, 0x2d, 0x74, 0x01, 0x06, 0x0a, 0x78, 0xdb, 0x96, 0x7d, 0x4e, 0xd2, 0xd4, 0xef, 0x73, 0x96,
	0x57, 0x2a, 0x8e, 0xbe, 0xe3, 0x60, 0xfa, 0xdf, 0x86, 0xca, 0xdc, 0xca, 0xd8, 0x0a, 0x00, 0x4d,
	0x05, 0x75, 0xa7, 0x13, 0x87, 0xfb, 0xb1, 0x50, 0x43, 0x63, 0x5a, 0x80, 0xc1, 0xa2, 0x7b, 0x01,
	0x55, 0x66, 0x6f, 0x50, 0x03, 0x9e, 0xca, 0x52, 0xb9, 0x4f, 0x7d, 0xc3, 0x41, 0x82, 0xcd, 0x8f,
	0x0f, 0xb3, 0xe8, 0xd6, 0x60, 0x9a, 0xa6, 0xf2, 0xb1, 0xf6, 0xa1, 0x24, 0x24, 0xd8, 0xac, 0x52,
	0x28, 0xce, 0x2d, 0x16, 0xb0, 0x86, 0xed, 0x63, 0xbf, 0x05, 0x9b, 0x55, 0x7a, 0x8b, 0xf4, 0xcf,
	0xc3, 0x30, 0x44, 0x67, 0x5d, 0x47, 0x6a, 0x15, 0x9b, 0x25, 0x92, 0xc5, 0xe8, 0x27, 0x0e, 0x06,
	0xeb, 0x9f, 0x7c, 0x68, 0x8e, 0x25, 0x34, 0x4d, 0xde, 0xd0, 0xd1, 0xbf, 0xbf, 0x9f, 0xb2, 0xc7,
	0x8a, 0xec, 0x89, 0xe7, 0x6a, 0x46, 0xbe, 0x44, 0xe0, 0xab, 0x60, 0xf7, 0x95, 0x70, 0x1d, 0xa2,
	0x46, 0xc5, 0x9d, 0xbb, 0xe9, 0x95, 0x62, 0x46, 0x23, 0x59, 0xcf, 0xee, 0x1a, 0x1a, 0x7f, 0xb0,
	0xf5, 0xe8, 0x6f, 0x86, 0xf9, 0x24, 0xf5, 0x4c, 0x31, 0x73, 0xee, 0xd3, 0xdf, 0xe9, 0x7e, 0x2f,
	0x7c, 0xff, 0x95, 0x82, 0x5e, 0xf2, 0x30, 0xda, 0xf4, 0x51, 0x85, 0x16, 0xd8, 0xdd, 0x68, 0xfe,
	0x74, 0x8a, 0xde, 0xfa, 0x8d, 0x56, 0x3c, 0x2a, 0x85, 0x3d, 0xf1, 0xa2, 0xbf, 0xe3, 0x27, 0xca,
	0x23, 0x78, 0xa2, 0x61, 0xe4, 0xde, 0x7d, 0x25, 0xdc, 0x80, 0x33, 0xcd, 0xc8, 0xac, 0x2c, 0x32,
	0xa1, 0xf9, 0x88, 0x87, 0xd1, 0xa6, 0x4f, 0x36, 0x36, 0x34, 0xed, 0x5e, 0x95, 0x6c, 0x68, 0xda,
	0xbe, 0x1b, 0x85, 0x87, 0x7b, 0xe2, 0xa9, 0x66, 0x29, 0x12, 0x08, 0xc2, 0x33, 0xe9, 0x82, 0x30,
	0xdb, 0x81, 0x78, 0xc3, 0xc3, 0x04, 0xcb, 0xa0, 0x86, 0x96, 0xd9, 0x03, 0xcd, 0xd4, 0x05, 0xa2,
	0x2b, 0xc7, 0x67, 0xd0, 0x23, 0x25, 0xef, 0x89, 0x91, 0x9a, 0x24, 0xf2, 0xfd, 0x5e, 0xb4, 0xce,
	0x9a, 0x05, 0x91, 0x29, 0x6b, 0x3e, 0xe6, 0x61, 0xbc, 0xed, 0x7c, 0x86, 0x96, 0x58, 0x1c, 0x63,
	0x1d, 0x1d, 0xa3, 0xff, 0x3c, 0x26, 0x6b, 0x1e, 0xa3, 0xdb, 0x7b, 0x22, 0x4f, 0xd4, 0xdd, 0x57,
	0xc2, 0x35, 0x88, 0x34, 0xd2, 0x70, 0xec, 0x88, 0x4c, 0x79, 0xb3, 0xcb, 0xc3, 0x39, 0x86, 0x49,
	0x07, 0xdd, 0x61, 0xb9, 0x3e, 0xfb, 0xd8, 0x18, 0x5d, 0x3e, 0x36, 0x7b, 0x1e, 0x10, 0x69, 0x4f,
	0xac, 0x99, 0x35, 0x9b, 0x35, 0x5e, 0xd7, 0xa6, 0xb8, 0x66, 0xb1, 0xc0, 0xf9, 0x8a, 0x87, 0x09,
	0x96, 0xa9, 0x82, 0xad, 0xa8, 0x8e, 0x30, 0x67, 0xb1, 0x15, 0xd5, 0x51, 0x06, 0x1e, 0xe1, 0xfe,
	0x9e, 0x38, 0x4c, 0xd4, 0x44, 0xfd, 0xac, 0xd5, 0xac, 0x9e, 0x3c, 0xdb, 0x6c, 0xf5, 0xf4, 0x19,
	0x0f, 0x13, 0x2c, 0x83, 0x06, 0x1b, 0xa7, 0x23, 0x0c, 0x42, 0x6c, 0x9c, 0x8e, 0x34, 0x03, 0x2d,
	0x96, 0x0b, 0x2b, 0x10, 0x8b, 0x67, 0x8a, 0x1d, 0x0b, 0xcb, 0xe4, 0xc3, 0x86, 0xe5, 0x08, 0x93,
	0x19, 0x1b, 0x96, 0xa3, 0x0c, 0x65, 0x6d, 0xb0, 0x78, 0xa6, 0x98, 0xb0, 0x44, 0xcf, 0x7e, 0x27,
	0x3a, 0x75, 0x69, 0xaf, 0xeb, 0x66, 0x3e, 0xa9, 0x18, 0xc4, 0x7f, 0x57, 0xa2, 0xcf, 0xff, 0xf7,
	0x7e, 0xba, 0xfd, 0x5f, 0x9a, 0xe6, 0x8c, 0x8c, 0x5c, 0x5d, 0x28, 0xa5, 0xdf, 0xf0, 0xc2, 0x62,
	0xd5, 0xca, 0x2a, 0x55, 0x5a, 0x5e, 0x4d, 0x56, 0xe7, 0xc8, 0xe4, 0xdd, 0x74, 0xa6, 0xcb, 0x7d,
	0x49, 0xcc, 0xfe, 0x1a, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xf8, 0x5f, 0xfd, 0xcb, 0x1a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlayerAuthServiceClient is the client API for PlayerAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerAuthServiceClient interface {
	CreateLoginToken(ctx context.Context, in *CreateLoginTokenRequest, opts ...grpc.CallOption) (*CreateLoginTokenResponse, error)
	CreatePlayerIdentityToken(ctx context.Context, in *CreatePlayerIdentityTokenRequest, opts ...grpc.CallOption) (*CreatePlayerIdentityTokenResponse, error)
	DecodePlayerIdentityToken(ctx context.Context, in *DecodePlayerIdentityTokenRequest, opts ...grpc.CallOption) (*DecodePlayerIdentityTokenResponse, error)
	CreateDevelopmentAuthenticationToken(ctx context.Context, in *CreateDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*CreateDevelopmentAuthenticationTokenResponse, error)
	GetDevelopmentAuthenticationToken(ctx context.Context, in *GetDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*GetDevelopmentAuthenticationTokenResponse, error)
	ListDevelopmentAuthenticationTokens(ctx context.Context, in *ListDevelopmentAuthenticationTokensRequest, opts ...grpc.CallOption) (*ListDevelopmentAuthenticationTokensResponse, error)
	UpdateDevelopmentAuthenticationToken(ctx context.Context, in *UpdateDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*UpdateDevelopmentAuthenticationTokenResponse, error)
	ExpireDevelopmentAuthenticationToken(ctx context.Context, in *ExpireDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*ExpireDevelopmentAuthenticationTokenResponse, error)
	DeleteDevelopmentAuthenticationToken(ctx context.Context, in *DeleteDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*DeleteDevelopmentAuthenticationTokenResponse, error)
}

type playerAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerAuthServiceClient(cc grpc.ClientConnInterface) PlayerAuthServiceClient {
	return &playerAuthServiceClient{cc}
}

func (c *playerAuthServiceClient) CreateLoginToken(ctx context.Context, in *CreateLoginTokenRequest, opts ...grpc.CallOption) (*CreateLoginTokenResponse, error) {
	out := new(CreateLoginTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreateLoginToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) CreatePlayerIdentityToken(ctx context.Context, in *CreatePlayerIdentityTokenRequest, opts ...grpc.CallOption) (*CreatePlayerIdentityTokenResponse, error) {
	out := new(CreatePlayerIdentityTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreatePlayerIdentityToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) DecodePlayerIdentityToken(ctx context.Context, in *DecodePlayerIdentityTokenRequest, opts ...grpc.CallOption) (*DecodePlayerIdentityTokenResponse, error) {
	out := new(DecodePlayerIdentityTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/DecodePlayerIdentityToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) CreateDevelopmentAuthenticationToken(ctx context.Context, in *CreateDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*CreateDevelopmentAuthenticationTokenResponse, error) {
	out := new(CreateDevelopmentAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreateDevelopmentAuthenticationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) GetDevelopmentAuthenticationToken(ctx context.Context, in *GetDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*GetDevelopmentAuthenticationTokenResponse, error) {
	out := new(GetDevelopmentAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/GetDevelopmentAuthenticationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) ListDevelopmentAuthenticationTokens(ctx context.Context, in *ListDevelopmentAuthenticationTokensRequest, opts ...grpc.CallOption) (*ListDevelopmentAuthenticationTokensResponse, error) {
	out := new(ListDevelopmentAuthenticationTokensResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/ListDevelopmentAuthenticationTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) UpdateDevelopmentAuthenticationToken(ctx context.Context, in *UpdateDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*UpdateDevelopmentAuthenticationTokenResponse, error) {
	out := new(UpdateDevelopmentAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/UpdateDevelopmentAuthenticationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) ExpireDevelopmentAuthenticationToken(ctx context.Context, in *ExpireDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*ExpireDevelopmentAuthenticationTokenResponse, error) {
	out := new(ExpireDevelopmentAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/ExpireDevelopmentAuthenticationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerAuthServiceClient) DeleteDevelopmentAuthenticationToken(ctx context.Context, in *DeleteDevelopmentAuthenticationTokenRequest, opts ...grpc.CallOption) (*DeleteDevelopmentAuthenticationTokenResponse, error) {
	out := new(DeleteDevelopmentAuthenticationTokenResponse)
	err := c.cc.Invoke(ctx, "/improbable.spatialos.playerauth.v2.PlayerAuthService/DeleteDevelopmentAuthenticationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerAuthServiceServer is the server API for PlayerAuthService service.
type PlayerAuthServiceServer interface {
	CreateLoginToken(context.Context, *CreateLoginTokenRequest) (*CreateLoginTokenResponse, error)
	CreatePlayerIdentityToken(context.Context, *CreatePlayerIdentityTokenRequest) (*CreatePlayerIdentityTokenResponse, error)
	DecodePlayerIdentityToken(context.Context, *DecodePlayerIdentityTokenRequest) (*DecodePlayerIdentityTokenResponse, error)
	CreateDevelopmentAuthenticationToken(context.Context, *CreateDevelopmentAuthenticationTokenRequest) (*CreateDevelopmentAuthenticationTokenResponse, error)
	GetDevelopmentAuthenticationToken(context.Context, *GetDevelopmentAuthenticationTokenRequest) (*GetDevelopmentAuthenticationTokenResponse, error)
	ListDevelopmentAuthenticationTokens(context.Context, *ListDevelopmentAuthenticationTokensRequest) (*ListDevelopmentAuthenticationTokensResponse, error)
	UpdateDevelopmentAuthenticationToken(context.Context, *UpdateDevelopmentAuthenticationTokenRequest) (*UpdateDevelopmentAuthenticationTokenResponse, error)
	ExpireDevelopmentAuthenticationToken(context.Context, *ExpireDevelopmentAuthenticationTokenRequest) (*ExpireDevelopmentAuthenticationTokenResponse, error)
	DeleteDevelopmentAuthenticationToken(context.Context, *DeleteDevelopmentAuthenticationTokenRequest) (*DeleteDevelopmentAuthenticationTokenResponse, error)
}

// UnimplementedPlayerAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerAuthServiceServer struct {
}

func (*UnimplementedPlayerAuthServiceServer) CreateLoginToken(ctx context.Context, req *CreateLoginTokenRequest) (*CreateLoginTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoginToken not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) CreatePlayerIdentityToken(ctx context.Context, req *CreatePlayerIdentityTokenRequest) (*CreatePlayerIdentityTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayerIdentityToken not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) DecodePlayerIdentityToken(ctx context.Context, req *DecodePlayerIdentityTokenRequest) (*DecodePlayerIdentityTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodePlayerIdentityToken not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) CreateDevelopmentAuthenticationToken(ctx context.Context, req *CreateDevelopmentAuthenticationTokenRequest) (*CreateDevelopmentAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDevelopmentAuthenticationToken not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) GetDevelopmentAuthenticationToken(ctx context.Context, req *GetDevelopmentAuthenticationTokenRequest) (*GetDevelopmentAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevelopmentAuthenticationToken not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) ListDevelopmentAuthenticationTokens(ctx context.Context, req *ListDevelopmentAuthenticationTokensRequest) (*ListDevelopmentAuthenticationTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevelopmentAuthenticationTokens not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) UpdateDevelopmentAuthenticationToken(ctx context.Context, req *UpdateDevelopmentAuthenticationTokenRequest) (*UpdateDevelopmentAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevelopmentAuthenticationToken not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) ExpireDevelopmentAuthenticationToken(ctx context.Context, req *ExpireDevelopmentAuthenticationTokenRequest) (*ExpireDevelopmentAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireDevelopmentAuthenticationToken not implemented")
}
func (*UnimplementedPlayerAuthServiceServer) DeleteDevelopmentAuthenticationToken(ctx context.Context, req *DeleteDevelopmentAuthenticationTokenRequest) (*DeleteDevelopmentAuthenticationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevelopmentAuthenticationToken not implemented")
}

func RegisterPlayerAuthServiceServer(s *grpc.Server, srv PlayerAuthServiceServer) {
	s.RegisterService(&_PlayerAuthService_serviceDesc, srv)
}

func _PlayerAuthService_CreateLoginToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoginTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).CreateLoginToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreateLoginToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).CreateLoginToken(ctx, req.(*CreateLoginTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_CreatePlayerIdentityToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerIdentityTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).CreatePlayerIdentityToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreatePlayerIdentityToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).CreatePlayerIdentityToken(ctx, req.(*CreatePlayerIdentityTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_DecodePlayerIdentityToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodePlayerIdentityTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).DecodePlayerIdentityToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/DecodePlayerIdentityToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).DecodePlayerIdentityToken(ctx, req.(*DecodePlayerIdentityTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_CreateDevelopmentAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDevelopmentAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).CreateDevelopmentAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreateDevelopmentAuthenticationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).CreateDevelopmentAuthenticationToken(ctx, req.(*CreateDevelopmentAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_GetDevelopmentAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevelopmentAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).GetDevelopmentAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/GetDevelopmentAuthenticationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).GetDevelopmentAuthenticationToken(ctx, req.(*GetDevelopmentAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_ListDevelopmentAuthenticationTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevelopmentAuthenticationTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).ListDevelopmentAuthenticationTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/ListDevelopmentAuthenticationTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).ListDevelopmentAuthenticationTokens(ctx, req.(*ListDevelopmentAuthenticationTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_UpdateDevelopmentAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDevelopmentAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).UpdateDevelopmentAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/UpdateDevelopmentAuthenticationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).UpdateDevelopmentAuthenticationToken(ctx, req.(*UpdateDevelopmentAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_ExpireDevelopmentAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireDevelopmentAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).ExpireDevelopmentAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/ExpireDevelopmentAuthenticationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).ExpireDevelopmentAuthenticationToken(ctx, req.(*ExpireDevelopmentAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerAuthService_DeleteDevelopmentAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDevelopmentAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerAuthServiceServer).DeleteDevelopmentAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.spatialos.playerauth.v2.PlayerAuthService/DeleteDevelopmentAuthenticationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerAuthServiceServer).DeleteDevelopmentAuthenticationToken(ctx, req.(*DeleteDevelopmentAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayerAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "improbable.spatialos.playerauth.v2.PlayerAuthService",
	HandlerType: (*PlayerAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoginToken",
			Handler:    _PlayerAuthService_CreateLoginToken_Handler,
		},
		{
			MethodName: "CreatePlayerIdentityToken",
			Handler:    _PlayerAuthService_CreatePlayerIdentityToken_Handler,
		},
		{
			MethodName: "DecodePlayerIdentityToken",
			Handler:    _PlayerAuthService_DecodePlayerIdentityToken_Handler,
		},
		{
			MethodName: "CreateDevelopmentAuthenticationToken",
			Handler:    _PlayerAuthService_CreateDevelopmentAuthenticationToken_Handler,
		},
		{
			MethodName: "GetDevelopmentAuthenticationToken",
			Handler:    _PlayerAuthService_GetDevelopmentAuthenticationToken_Handler,
		},
		{
			MethodName: "ListDevelopmentAuthenticationTokens",
			Handler:    _PlayerAuthService_ListDevelopmentAuthenticationTokens_Handler,
		},
		{
			MethodName: "UpdateDevelopmentAuthenticationToken",
			Handler:    _PlayerAuthService_UpdateDevelopmentAuthenticationToken_Handler,
		},
		{
			MethodName: "ExpireDevelopmentAuthenticationToken",
			Handler:    _PlayerAuthService_ExpireDevelopmentAuthenticationToken_Handler,
		},
		{
			MethodName: "DeleteDevelopmentAuthenticationToken",
			Handler:    _PlayerAuthService_DeleteDevelopmentAuthenticationToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "improbable/spatialos/playerauth/v2/playerauth.proto",
}
