// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/int/platform/billing/report.proto

package improbable_int_platform_billing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *BillingReport) LogFields() map[string]string {
	return map[string]string{}
}

func (this *BillingReport) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *ListBillingReportRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *ListBillingReportRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *ListBillingReportResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *ListBillingReportResponse) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetBillingReportRequest) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetBillingReportRequest) ExtractRequestFields(dst map[string]interface{}) {
}

func (this *GetBillingReportResponse) LogFields() map[string]string {
	return map[string]string{}
}

func (this *GetBillingReportResponse) ExtractRequestFields(dst map[string]interface{}) {
}
