// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/int/platform/fabric_nanny/fabric_nanny.proto

package improbable_int_platform_fabric_nanny

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunCommandRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	Dir                  string   `protobuf:"bytes,3,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Env                  []string `protobuf:"bytes,4,rep,name=Env,proto3" json:"Env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunCommandRequest) Reset()         { *m = RunCommandRequest{} }
func (m *RunCommandRequest) String() string { return proto.CompactTextString(m) }
func (*RunCommandRequest) ProtoMessage()    {}
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a0ab9fc9e6dca9f, []int{0}
}

func (m *RunCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunCommandRequest.Unmarshal(m, b)
}
func (m *RunCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunCommandRequest.Marshal(b, m, deterministic)
}
func (m *RunCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunCommandRequest.Merge(m, src)
}
func (m *RunCommandRequest) XXX_Size() int {
	return xxx_messageInfo_RunCommandRequest.Size(m)
}
func (m *RunCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunCommandRequest proto.InternalMessageInfo

func (m *RunCommandRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *RunCommandRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RunCommandRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *RunCommandRequest) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type RunCommandResponse struct {
	StdOut               string   `protobuf:"bytes,1,opt,name=StdOut,proto3" json:"StdOut,omitempty"`
	StdErr               string   `protobuf:"bytes,2,opt,name=StdErr,proto3" json:"StdErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunCommandResponse) Reset()         { *m = RunCommandResponse{} }
func (m *RunCommandResponse) String() string { return proto.CompactTextString(m) }
func (*RunCommandResponse) ProtoMessage()    {}
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a0ab9fc9e6dca9f, []int{1}
}

func (m *RunCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunCommandResponse.Unmarshal(m, b)
}
func (m *RunCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunCommandResponse.Marshal(b, m, deterministic)
}
func (m *RunCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunCommandResponse.Merge(m, src)
}
func (m *RunCommandResponse) XXX_Size() int {
	return xxx_messageInfo_RunCommandResponse.Size(m)
}
func (m *RunCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunCommandResponse proto.InternalMessageInfo

func (m *RunCommandResponse) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *RunCommandResponse) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

func init() {
	proto.RegisterType((*RunCommandRequest)(nil), "improbable.int.platform.fabric_nanny.RunCommandRequest")
	proto.RegisterType((*RunCommandResponse)(nil), "improbable.int.platform.fabric_nanny.RunCommandResponse")
}

func init() {
	proto.RegisterFile("improbable/int/platform/fabric_nanny/fabric_nanny.proto", fileDescriptor_3a0ab9fc9e6dca9f)
}

var fileDescriptor_3a0ab9fc9e6dca9f = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xb1, 0x4e, 0xf3, 0x30,
	0x18, 0x54, 0x92, 0x2a, 0x52, 0x3d, 0xfd, 0xbf, 0x07, 0x64, 0x75, 0x21, 0xaa, 0x18, 0xba, 0xd4,
	0x96, 0x40, 0xa2, 0xac, 0xd0, 0x86, 0x11, 0x24, 0xf7, 0x01, 0x90, 0x93, 0xb8, 0xc1, 0x22, 0xb6,
	0xc3, 0x17, 0x27, 0x15, 0x13, 0x4f, 0xc1, 0xf3, 0x21, 0xf1, 0x24, 0xc8, 0x49, 0x69, 0x8b, 0x58,
	0x60, 0xbb, 0xef, 0x74, 0x77, 0x9f, 0xee, 0xd0, 0x42, 0xe9, 0x1a, 0x6c, 0x26, 0xb2, 0x4a, 0x32,
	0x65, 0x1c, 0xab, 0x2b, 0xe1, 0x36, 0x16, 0x34, 0xdb, 0x88, 0x0c, 0x54, 0xfe, 0x60, 0x84, 0x31,
	0x2f, 0xdf, 0x0e, 0x5a, 0x83, 0x75, 0x16, 0x9f, 0x1d, 0x8c, 0x54, 0x19, 0x47, 0xbf, 0x8c, 0xf4,
	0x58, 0x3b, 0xb9, 0x2c, 0x95, 0x7b, 0x6c, 0x33, 0x9a, 0x5b, 0xcd, 0xf4, 0x56, 0xb9, 0x27, 0xbb,
	0x65, 0xa5, 0x9d, 0xf7, 0x11, 0xf3, 0x4e, 0x54, 0xaa, 0x10, 0xce, 0x42, 0xc3, 0xf6, 0x70, 0x48,
	0x9f, 0x4a, 0xf4, 0x9f, 0xb7, 0x66, 0x69, 0xb5, 0x16, 0xa6, 0xe0, 0xf2, 0xb9, 0x95, 0x8d, 0xc3,
	0x04, 0x45, 0x4b, 0x5d, 0x90, 0x20, 0x09, 0x66, 0xe3, 0x9b, 0xf8, 0xe3, 0xfd, 0x34, 0x4c, 0x02,
	0xee, 0x29, 0x8c, 0xd1, 0xe8, 0x1a, 0xca, 0x86, 0x84, 0x49, 0x34, 0x1b, 0xf3, 0x1e, 0xe3, 0x7f,
	0x28, 0x5a, 0x29, 0x20, 0x91, 0x57, 0x73, 0x0f, 0x3d, 0x93, 0x9a, 0x8e, 0x8c, 0x7a, 0x91, 0x87,
	0xd3, 0x15, 0xc2, 0xc7, 0x6f, 0x9a, 0xda, 0x9a, 0x46, 0xe2, 0x13, 0x14, 0xaf, 0x5d, 0x71, 0xdf,
	0xba, 0xe1, 0x15, 0xdf, 0x5d, 0x3b, 0x3e, 0x05, 0x20, 0xe1, 0x9e, 0x4f, 0x01, 0xce, 0xdf, 0x02,
	0x84, 0x6f, 0xfb, 0xd6, 0x77, 0xbe, 0xf4, 0x5a, 0x42, 0xa7, 0x72, 0x89, 0x5f, 0x11, 0x3a, 0x84,
	0xe3, 0x05, 0xfd, 0xcd, 0x60, 0xf4, 0x47, 0xeb, 0xc9, 0xd5, 0xdf, 0x8d, 0x43, 0x8f, 0x2c, 0xee,
	0xb7, 0xbc, 0xf8, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x45, 0xc6, 0x3f, 0x35, 0xe4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FabricNannyServiceClient is the client API for FabricNannyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FabricNannyServiceClient interface {
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error)
}

type fabricNannyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricNannyServiceClient(cc grpc.ClientConnInterface) FabricNannyServiceClient {
	return &fabricNannyServiceClient{cc}
}

func (c *fabricNannyServiceClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error) {
	out := new(RunCommandResponse)
	err := c.cc.Invoke(ctx, "/improbable.int.platform.fabric_nanny.FabricNannyService/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabricNannyServiceServer is the server API for FabricNannyService service.
type FabricNannyServiceServer interface {
	RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error)
}

// UnimplementedFabricNannyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFabricNannyServiceServer struct {
}

func (*UnimplementedFabricNannyServiceServer) RunCommand(ctx context.Context, req *RunCommandRequest) (*RunCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}

func RegisterFabricNannyServiceServer(s *grpc.Server, srv FabricNannyServiceServer) {
	s.RegisterService(&_FabricNannyService_serviceDesc, srv)
}

func _FabricNannyService_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricNannyServiceServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.int.platform.fabric_nanny.FabricNannyService/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricNannyServiceServer).RunCommand(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FabricNannyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "improbable.int.platform.fabric_nanny.FabricNannyService",
	HandlerType: (*FabricNannyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCommand",
			Handler:    _FabricNannyService_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "improbable/int/platform/fabric_nanny/fabric_nanny.proto",
}
