// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/ext/postie/events/unreal/unreal.proto

package improbable_ext_postie_events_unreal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	SubjectId            string   `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	SdkVersion           string   `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	UnrealVersion        string   `protobuf:"bytes,5,opt,name=unreal_version,json=unrealVersion,proto3" json:"unreal_version,omitempty"`
	Origin               string   `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c5abf78dcd0226, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetSubjectId() string {
	if m != nil {
		return m.SubjectId
	}
	return ""
}

func (m *Header) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Header) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Header) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

func (m *Header) GetUnrealVersion() string {
	if m != nil {
		return m.UnrealVersion
	}
	return ""
}

func (m *Header) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type LocalDeploymentStarted struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ProjectVersion       string   `protobuf:"bytes,2,opt,name=project_version,json=projectVersion,proto3" json:"project_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalDeploymentStarted) Reset()         { *m = LocalDeploymentStarted{} }
func (m *LocalDeploymentStarted) String() string { return proto.CompactTextString(m) }
func (*LocalDeploymentStarted) ProtoMessage()    {}
func (*LocalDeploymentStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c5abf78dcd0226, []int{1}
}

func (m *LocalDeploymentStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalDeploymentStarted.Unmarshal(m, b)
}
func (m *LocalDeploymentStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalDeploymentStarted.Marshal(b, m, deterministic)
}
func (m *LocalDeploymentStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalDeploymentStarted.Merge(m, src)
}
func (m *LocalDeploymentStarted) XXX_Size() int {
	return xxx_messageInfo_LocalDeploymentStarted.Size(m)
}
func (m *LocalDeploymentStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalDeploymentStarted.DiscardUnknown(m)
}

var xxx_messageInfo_LocalDeploymentStarted proto.InternalMessageInfo

func (m *LocalDeploymentStarted) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LocalDeploymentStarted) GetProjectVersion() string {
	if m != nil {
		return m.ProjectVersion
	}
	return ""
}

type LocalDeploymentStopped struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ProjectVersion       string   `protobuf:"bytes,2,opt,name=project_version,json=projectVersion,proto3" json:"project_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalDeploymentStopped) Reset()         { *m = LocalDeploymentStopped{} }
func (m *LocalDeploymentStopped) String() string { return proto.CompactTextString(m) }
func (*LocalDeploymentStopped) ProtoMessage()    {}
func (*LocalDeploymentStopped) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c5abf78dcd0226, []int{2}
}

func (m *LocalDeploymentStopped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalDeploymentStopped.Unmarshal(m, b)
}
func (m *LocalDeploymentStopped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalDeploymentStopped.Marshal(b, m, deterministic)
}
func (m *LocalDeploymentStopped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalDeploymentStopped.Merge(m, src)
}
func (m *LocalDeploymentStopped) XXX_Size() int {
	return xxx_messageInfo_LocalDeploymentStopped.Size(m)
}
func (m *LocalDeploymentStopped) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalDeploymentStopped.DiscardUnknown(m)
}

var xxx_messageInfo_LocalDeploymentStopped proto.InternalMessageInfo

func (m *LocalDeploymentStopped) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LocalDeploymentStopped) GetProjectVersion() string {
	if m != nil {
		return m.ProjectVersion
	}
	return ""
}

type LocalInspectorLaunched struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ProjectVersion       string   `protobuf:"bytes,2,opt,name=project_version,json=projectVersion,proto3" json:"project_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalInspectorLaunched) Reset()         { *m = LocalInspectorLaunched{} }
func (m *LocalInspectorLaunched) String() string { return proto.CompactTextString(m) }
func (*LocalInspectorLaunched) ProtoMessage()    {}
func (*LocalInspectorLaunched) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c5abf78dcd0226, []int{3}
}

func (m *LocalInspectorLaunched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalInspectorLaunched.Unmarshal(m, b)
}
func (m *LocalInspectorLaunched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalInspectorLaunched.Marshal(b, m, deterministic)
}
func (m *LocalInspectorLaunched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalInspectorLaunched.Merge(m, src)
}
func (m *LocalInspectorLaunched) XXX_Size() int {
	return xxx_messageInfo_LocalInspectorLaunched.Size(m)
}
func (m *LocalInspectorLaunched) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalInspectorLaunched.DiscardUnknown(m)
}

var xxx_messageInfo_LocalInspectorLaunched proto.InternalMessageInfo

func (m *LocalInspectorLaunched) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LocalInspectorLaunched) GetProjectVersion() string {
	if m != nil {
		return m.ProjectVersion
	}
	return ""
}

type PropertiesSaved struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertiesSaved) Reset()         { *m = PropertiesSaved{} }
func (m *PropertiesSaved) String() string { return proto.CompactTextString(m) }
func (*PropertiesSaved) ProtoMessage()    {}
func (*PropertiesSaved) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c5abf78dcd0226, []int{4}
}

func (m *PropertiesSaved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertiesSaved.Unmarshal(m, b)
}
func (m *PropertiesSaved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertiesSaved.Marshal(b, m, deterministic)
}
func (m *PropertiesSaved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertiesSaved.Merge(m, src)
}
func (m *PropertiesSaved) XXX_Size() int {
	return xxx_messageInfo_PropertiesSaved.Size(m)
}
func (m *PropertiesSaved) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertiesSaved.DiscardUnknown(m)
}

var xxx_messageInfo_PropertiesSaved proto.InternalMessageInfo

func (m *PropertiesSaved) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "improbable.ext.postie.events.unreal.Header")
	proto.RegisterType((*LocalDeploymentStarted)(nil), "improbable.ext.postie.events.unreal.LocalDeploymentStarted")
	proto.RegisterType((*LocalDeploymentStopped)(nil), "improbable.ext.postie.events.unreal.LocalDeploymentStopped")
	proto.RegisterType((*LocalInspectorLaunched)(nil), "improbable.ext.postie.events.unreal.LocalInspectorLaunched")
	proto.RegisterType((*PropertiesSaved)(nil), "improbable.ext.postie.events.unreal.PropertiesSaved")
}

func init() {
	proto.RegisterFile("improbable/ext/postie/events/unreal/unreal.proto", fileDescriptor_b4c5abf78dcd0226)
}

var fileDescriptor_b4c5abf78dcd0226 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0xcf, 0x4a, 0x2b, 0x31,
	0x14, 0xc6, 0x99, 0x7b, 0x75, 0xb4, 0xa7, 0xd8, 0x42, 0x16, 0x65, 0x10, 0x44, 0xa9, 0x88, 0x82,
	0x90, 0x11, 0x7d, 0x04, 0x5d, 0x58, 0xe8, 0x42, 0x5a, 0xe8, 0xb6, 0x64, 0x26, 0x47, 0x1b, 0x3b,
	0xcd, 0x09, 0x49, 0x5a, 0xea, 0x0b, 0xf8, 0x56, 0xbe, 0x9b, 0x98, 0xa4, 0x75, 0xe3, 0xc2, 0x85,
	0xe8, 0x6a, 0x38, 0xdf, 0x1f, 0xf8, 0x7d, 0x61, 0xe0, 0x4a, 0x2d, 0x8c, 0xa5, 0x4a, 0x54, 0x0d,
	0x96, 0xb8, 0xf6, 0xa5, 0x21, 0xe7, 0x15, 0x96, 0xb8, 0x42, 0xed, 0x5d, 0xb9, 0xd4, 0x16, 0x45,
	0x93, 0x3e, 0xdc, 0x58, 0xf2, 0xc4, 0x4e, 0x3f, 0x1b, 0x1c, 0xd7, 0x9e, 0xc7, 0x06, 0x8f, 0x0d,
	0x1e, 0xa3, 0xfd, 0xb7, 0x0c, 0xf2, 0x7b, 0x14, 0x12, 0x2d, 0x3b, 0x02, 0x70, 0xcb, 0xea, 0x19,
	0x6b, 0x3f, 0x55, 0xb2, 0xc8, 0x4e, 0xb2, 0x8b, 0xd6, 0xa8, 0x95, 0x94, 0x81, 0x64, 0x87, 0xb0,
	0x6f, 0x1a, 0xe1, 0x1f, 0xc9, 0x2e, 0x8a, 0x7f, 0xc1, 0xdc, 0xde, 0xac, 0x80, 0x3d, 0x63, 0xe9,
	0x23, 0x58, 0xfc, 0x0f, 0xd6, 0xe6, 0x64, 0xc7, 0xd0, 0x76, 0x72, 0x3e, 0x5d, 0xa1, 0x75, 0x8a,
	0x74, 0xb1, 0x13, 0x5c, 0x70, 0x72, 0x3e, 0x89, 0x0a, 0x3b, 0x83, 0x4e, 0x44, 0xd9, 0x66, 0x76,
	0x43, 0xe6, 0x20, 0xaa, 0x9b, 0x58, 0x0f, 0x72, 0xb2, 0xea, 0x49, 0xe9, 0x22, 0x0f, 0x76, 0xba,
	0xfa, 0xaf, 0x19, 0xf4, 0x86, 0x54, 0x8b, 0xe6, 0x0e, 0x4d, 0x43, 0x2f, 0x0b, 0xd4, 0x7e, 0xec,
	0x85, 0xf5, 0x28, 0xd9, 0x2d, 0xe4, 0xb3, 0xb0, 0x2c, 0x6c, 0x69, 0x5f, 0x5f, 0xf2, 0x6f, 0x3c,
	0x08, 0x8f, 0x8f, 0x31, 0x4a, 0x55, 0x76, 0x0e, 0xdd, 0x34, 0x65, 0xcb, 0x17, 0xc7, 0x77, 0x92,
	0x9c, 0x00, 0xbf, 0x06, 0x21, 0x63, 0xfe, 0x0e, 0x64, 0xa0, 0x9d, 0xc1, 0xda, 0x93, 0x1d, 0x8a,
	0xa5, 0xae, 0x67, 0xbf, 0x0e, 0x32, 0x81, 0xee, 0x83, 0x25, 0x83, 0xd6, 0x2b, 0x74, 0x63, 0xb1,
	0xfa, 0x21, 0x80, 0x2a, 0x0f, 0xbf, 0xf7, 0xcd, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x66,
	0x30, 0xf6, 0x12, 0x03, 0x00, 0x00,
}
