// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: improbable/platform/history/snapshot.proto

package improbable_platform_history

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/improbable-io/go-proto-logfields"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "improbable.io/proto/improbable/ext/plugin/auth"
	_ "improbable.io/proto/improbable/platform"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SnapshotId) Validate() error {
	if nil == this.HistoryId {
		return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", fmt.Errorf("message must exist"))
	}
	if this.HistoryId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.HistoryId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", err)
		}
	}
	return nil
}

var _regex_Snapshot_Tags = regexp.MustCompile(`^[a-zA-Z0-9_:.-]{2,32}$`)

func (this *Snapshot) Validate() error {
	if nil == this.SnapshotId {
		return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", fmt.Errorf("message must exist"))
	}
	if this.SnapshotId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SnapshotId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", err)
		}
	}
	for _, item := range this.Tags {
		if !_regex_Snapshot_Tags.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9_:.-]{2,32}$"`, item))
		}
	}
	if this.CreationTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreationTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreationTime", err)
		}
	}
	return nil
}

var _regex_ListSnapshotRequest_Tags = regexp.MustCompile(`^[a-zA-Z0-9_:.-]{2,32}$`)

func (this *ListSnapshotRequest) Validate() error {
	if nil == this.HistoryId {
		return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", fmt.Errorf("message must exist"))
	}
	if this.HistoryId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.HistoryId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", err)
		}
	}
	for _, item := range this.Tags {
		if !_regex_ListSnapshotRequest_Tags.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9_:.-]{2,32}$"`, item))
		}
	}
	if this.BeforeTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.BeforeTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("BeforeTime", err)
		}
	}
	if this.AfterTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AfterTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AfterTime", err)
		}
	}
	return nil
}
func (this *ListPagedRequest) Validate() error {
	if nil == this.HistoryId {
		return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", fmt.Errorf("message must exist"))
	}
	if this.HistoryId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.HistoryId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", err)
		}
	}
	return nil
}
func (this *ListPagedResponse) Validate() error {
	for _, item := range this.Snapshots {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Snapshots", err)
			}
		}
	}
	return nil
}

var _regex_CreationRequest_Tags = regexp.MustCompile(`^[a-zA-Z0-9_:.-]{2,32}$`)

func (this *CreationRequest) Validate() error {
	if nil == this.HistoryId {
		return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", fmt.Errorf("message must exist"))
	}
	if this.HistoryId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.HistoryId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", err)
		}
	}
	for _, item := range this.Tags {
		if !_regex_CreationRequest_Tags.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9_:.-]{2,32}$"`, item))
		}
	}
	return nil
}

var _regex_CloneRequest_Tags = regexp.MustCompile(`^[a-zA-Z0-9_:.-]{2,32}$`)

func (this *CloneRequest) Validate() error {
	if nil == this.SnapshotId {
		return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", fmt.Errorf("message must exist"))
	}
	if this.SnapshotId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SnapshotId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", err)
		}
	}
	if nil == this.NewHistory {
		return github_com_mwitkow_go_proto_validators.FieldError("NewHistory", fmt.Errorf("message must exist"))
	}
	if this.NewHistory != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.NewHistory); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("NewHistory", err)
		}
	}
	for _, item := range this.Tags {
		if !_regex_CloneRequest_Tags.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9_:.-]{2,32}$"`, item))
		}
	}
	return nil
}
func (this *CreationResponse) Validate() error {
	if nil == this.SnapshotId {
		return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", fmt.Errorf("message must exist"))
	}
	if this.SnapshotId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SnapshotId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", err)
		}
	}
	return nil
}

var _regex_GetLatestRequest_Tags = regexp.MustCompile(`^[a-zA-Z0-9_:.-]{2,32}$`)

func (this *GetLatestRequest) Validate() error {
	if nil == this.HistoryId {
		return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", fmt.Errorf("message must exist"))
	}
	if this.HistoryId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.HistoryId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("HistoryId", err)
		}
	}
	for _, item := range this.Tags {
		if !_regex_GetLatestRequest_Tags.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9_:.-]{2,32}$"`, item))
		}
	}
	return nil
}
func (this *GenerateUploadUrlRequest) Validate() error {
	if nil == this.SnapshotId {
		return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", fmt.Errorf("message must exist"))
	}
	if this.SnapshotId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SnapshotId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SnapshotId", err)
		}
	}
	return nil
}
func (this *GenerateUploadUrlResponse) Validate() error {
	return nil
}
func (this *ListSupportedFileStorageProvidersRequest) Validate() error {
	return nil
}
func (this *ListSupportedFileStorageProvidersResponse) Validate() error {
	return nil
}
